Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-12, with the labels that each got.

#1537 Fan - Fix letters with accents and how they work with searching
  src/actions/projectMembers.js
  src/components/Badge/AssignBadge.jsx
  src/components/Reports/Reports.jsx
  src/components/Teams/MembersAutoComplete.jsx
  src/components/Teams/Teams.jsx
  src/components/UserManagement/UserManagement.jsx
  src/utils/search.js
Labels: High Priority - Please Review First

#1589 Ruike_filter_active_user
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
Labels: High Priority - Please Review First

#1414 Leo_fix_issue_update_with_updating_existing_password
  src/__tests__/UpdatePassword/UpdatePassword.test.js
  src/components/UpdatePassword/UpdatePassword.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
Labels: Moved to Final Review

#1546 Obeda radio unit test
  src/components/common/Radio/Radio.jsx
  src/components/common/Radio/Radio.test.jsx
Labels: High Priority - Please Review First

#1623 Yi fix profile page formatting issues
  src/components/UserProfile/Badge.css
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
Labels: High Priority - Please Review First

#1403 Obeda fix another person view dashboard view header
  src/components/Header/Header.jsx
  src/utils/permissions.js
Labels: High Priority - Please Review First

#1548 Nathan permission categories
  src/components/PermissionsManagement/NewRolePopUp.jsx
  src/components/PermissionsManagement/PermissionList.jsx
  src/components/PermissionsManagement/PermissionListItem.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/PermissionsManagement/Preset.jsx
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
Labels: High Priority - Please Review First

#1499 Shiwani AssignBadgePopup component Unit Test
  src/__tests__/AssignBadgePopup.test.js
Labels: Moved to Final Review

#1688 vishala added large resource class
  .circleci/config.yml
Labels: do not review

#1693 Vishala adding surge dep
  package-lock.json
  package.json
Labels: do not review

#1584 ruike_avoid_overlap
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First

#1634 Ruike make email not case sensitive
  src/components/Login/Login.jsx
  src/components/UserManagement/setupNewUserPopup.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: High Priority - Please Review First

#1699 vishala large resource class for beta
  .circleci/config.yml
Labels: do not review

#1672 Wanting_UnitTest_AddWBS.jsx
  src/components/Projects/WBS/AddWBS/AddWBS.test.jsx
Labels: Moved to Final Review

#1639 Wanting_UnitTest_ProjectTableHeader
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.test.jsx
Labels: Moved to Final Review

#1709 Fixed modified date for badges
  src/components/Badge/BadgeReport.jsx
Labels: do not review

#1650 Shihao - FeaturedBadges Unit Test
  src/components/UserProfile/BadgeImage.jsx
  src/components/UserProfile/FeaturedBadges/FeaturedBadges.jsx
  src/components/UserProfile/FeaturedBadges/__test__/FeaturedBadges.test.js
  src/components/UserProfile/FeaturedBadges/__test__/mockData.js
  src/components/UserProfile/FeaturedBadges/index.js
Labels: Moved to Final Review

#1497 Shrey add unit test cases for Input
  src/components/common/Input/Input.test.jsx
Labels: Moved to Final Review

#1721 yihan fix "Set inactive" button on confirm deletion modal
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Projects.jsx
  src/components/Teams/Team.jsx
Labels: High Priority - Please Review First

#1727 Sucheta - Fix Task Name entry-box formatting (Add Task)
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: High Priority - Please Review First

#1658 Nathan separate reports from weekly summaries
  src/components/Header/Header.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/routes.js
  src/utils/routePermissions.js
Labels: High Priority - Please Review First

#1454 Ruike enforce no space in file name
  .gitignore
  src/components/Projects/WBS/WBSDetail/components/TagSent_2.jsx
  src/components/Projects/WBS/WBSDetail/components/TagsSearch_2.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/ReportCard_2.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/ReportCard_2.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/index_2.js
  src/components/common/Clipboard/CopyToClipboard_2.jsx
  src/components/common/Clipboard/style_2.css
Labels: Moved to Final Review

#1708 Wanting unit test for `ProjectTableHeader.jsx`
  src/components/Projects/ProjectTableHeader/__tests__/ProjectTableHeader.test.jsx
Labels: Moved to Final Review

#1485 Wanting new make 5 letter codes editable only by admin&owner
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#1585 Ruike message after submit task
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: Moved to Final Review, High Priority - Please Review First
