Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-10, with the labels that each got.

#1346 Shihao - Fix Badges' Display Issue
  .eslintignore
  .prettierignore
  src/components/WeeklySummariesReport/BioFunction.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/TotalValidSummaries.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: do not review, Moved to Final Review

#1367 Xiao F Hotfix Differentiate Personal Max Badge Part C Number of Hours
  src/components/Badge/Badge.jsx
  src/components/Badge/BadgeImage.jsx
  src/components/UserProfile/BadgeImage.jsx
Labels: Moved to Final Review

#1208 yihan add team code permission
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review

#1236 Yubo - feature- warning popup in editing media links
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
Labels: Moved to Final Review

#1330 Olga - design project details page
  package-lock.json
  package.json
  src/components/BMDashboard/ProjectDetails/LogBar.jsx
  src/components/BMDashboard/ProjectDetails/Materials/MaterialCard.jsx
  src/components/BMDashboard/ProjectDetails/Materials/Materials.jsx
  src/components/BMDashboard/ProjectDetails/Materials/MaterialsDisplay.jsx
  src/components/BMDashboard/ProjectDetails/ProjectDetails.css
  src/components/BMDashboard/ProjectDetails/ProjectDetails.jsx
  src/components/BMDashboard/ProjectDetails/ProjectLog.jsx
  src/components/BMDashboard/ProjectDetails/RentedTools/RentedToolsDisplay.jsx
  src/components/BMDashboard/ProjectDetails/RentedTools/ToolCard.jsx
  src/components/BMDashboard/ProjectDetails/RentedTools/ToolCards.jsx
  src/routes.js
Labels: Moved to Final Review

#1398 Vishala_Timelog_React_warning_key_prop
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#1384 Olga design projects summary view
  .gitattributes
  src/components/BMDashboard/BMDashboard.css
  src/components/BMDashboard/BMDashboard.jsx
  src/components/BMDashboard/Projects/ProjectDetails/LogBar.jsx
  src/components/BMDashboard/Projects/ProjectDetails/Materials/MaterialCard.jsx
  src/components/BMDashboard/Projects/ProjectDetails/Materials/Materials.jsx
  src/components/BMDashboard/Projects/ProjectDetails/Materials/MaterialsDisplay.jsx
  src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.css
  src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.jsx
  src/components/BMDashboard/Projects/ProjectDetails/ProjectLog.jsx
  src/components/BMDashboard/Projects/ProjectDetails/RentedTools/RentedToolsDisplay.jsx
  src/components/BMDashboard/Projects/ProjectDetails/RentedTools/ToolCard.jsx
  src/components/BMDashboard/Projects/ProjectDetails/RentedTools/ToolCards.jsx
  src/components/BMDashboard/Projects/ProjectSelectForm.jsx
  src/components/BMDashboard/Projects/ProjectSummary.jsx
  src/components/BMDashboard/Projects/ProjectsList.jsx
  src/routes.js
Labels: Moved to Final Review

#1374 Nathan reset permissions to default
  src/actions/rolePermissionPresets.js
  src/components/PermissionsManagement/PermissionsPresetsModal.jsx
  src/components/PermissionsManagement/Preset.jsx
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/PermissionsManagement/UserRoleTab.css
  src/constants/rolePermissionPresets.js
  src/reducers/index.js
  src/reducers/rolePresetReducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#1418 Update FormattedReport.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: Moved to Final Review

#1401 Tim add Materials List page
  .eslintignore
  .gitattributes
  src/actions/bmdashboard/materialsActions.js
  src/components/BMDashboard/BMDashboard.jsx
  src/components/BMDashboard/Login/BMLogin.jsx
  src/components/BMDashboard/Login/index.js
  src/components/BMDashboard/MaterialsList/MaterialsList.css
  src/components/BMDashboard/MaterialsList/MaterialsList.jsx
  src/components/BMDashboard/MaterialsList/MaterialsTable.jsx
  src/components/BMDashboard/MaterialsList/RecordsModal.css
  src/components/BMDashboard/MaterialsList/RecordsModal.jsx
  src/components/BMDashboard/MaterialsList/SelectForm.jsx
  src/components/BMDashboard/MaterialsList/index.js
  src/components/BMDashboard/Projects/ProjectDetails/LogBar.jsx
  src/components/BMDashboard/Projects/ProjectDetails/Materials/MaterialsDisplay.jsx
  src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.jsx
  src/components/BMDashboard/Projects/ProjectDetails/ProjectLog.jsx
  src/components/BMDashboard/Projects/ProjectDetails/RentedTools/RentedToolsDisplay.jsx
  src/components/BMDashboard/Projects/ProjectDetails/RentedTools/ToolCard.jsx
  src/components/BMDashboard/Projects/ProjectSelectForm.jsx
  src/components/BMDashboard/Projects/ProjectSummary.jsx
  src/components/BMDashboard/Projects/ProjectsList.jsx
  src/components/BMDashboard/index.js
  src/components/BMDashboard/shared/BMError.css
  src/components/BMDashboard/shared/BMError.jsx
  src/constants/bmdashboard/materialsConstants.js
  src/reducers/bmdashboard/materialsReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: Moved to Final Review

#1396 Yuri - Design navigation bar
  .eslintignore
  src/components/BMDashboard/BMHeader/BMHeader.css
  src/components/BMDashboard/BMHeader/BMHeader.jsx
  src/components/BMDashboard/BMHeader/index.js
  src/languages/en/ui.js
  src/routes.js
Labels: Moved to Final Review

#1439 Obeda lint fix AutoUpdate components
  .eslintignore
  .prettierignore
  src/components/AutoUpdate/AutoUpdate.jsx
  src/components/AutoUpdate/index.js
Labels: Moved to Final Review

#1435 Shiwani lint fix for constants
  .eslintignore
  .prettierignore
  src/constants/bmdashboard/materialsConstants.js
  src/constants/information.js
  src/constants/ownerMessageConstants.js
  src/constants/ownerStandardMessageConstants.js
  src/constants/project.js
  src/constants/team.js
  src/constants/timer.js
  src/constants/userProjects.js
Labels: Moved to Final Review

#1438 Shrey create a toggle switch to have active and all users
  src/components/Projects/Members/Members.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
Labels: Moved to Final Review

#1444 removed line 14 in public/index.html that was redundant and causing …
  public/index.html
Labels: do not review

#1412 Shiwani Fix Log time entry for other users at other user’s timelog page
  src/actions/timeEntries.js
  src/actions/userProfile.js
  src/components/Timelog/TimeEntry.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.jsx
  src/components/Timer/Timer.jsx
Labels: Moved to Final Review

#1428 Luis summary intro btn
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.scss
Labels: Moved to Final Review

#1455 XiaoW Add tooltip to new timer and cleanup old timer
  src/__tests__/ForcePasswordUpdate.test.js
  src/__tests__/Leaderboard.test.js
  src/__tests__/LoginPage.test.js
  src/__tests__/Logout.test.js
  src/__tests__/Projects/Projects.WBS.test.js
  src/actions/timer.js
  src/components/BMDashboard/BMHeader/BMHeader.jsx
  src/components/Header/Header.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timer/Countdown.jsx
  src/components/Timer/Countdown.module.css
  src/components/Timer/NewTimer.jsx
  src/components/Timer/Timer.css
  src/components/Timer/Timer.jsx
  src/components/Timer/Timer.module.css
  src/components/Timer/TimerStatus.jsx
  src/constants/timer.js
  src/reducers/index.js
  src/reducers/timerReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review

#1389 Harshida fix user management changes
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
Labels: Moved to Final Review
