Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-07, with the labels that each got.

#927 Nida Fix - Save changes for endDate
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.scss
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.css
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: Moved to Final Review

#960 Nida Fix - Save Changes Fix on User Profile
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#959 yihan modify layout of “Create New User” form
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.scss
Labels: do not review, Moved to Final Review

#925 Leon fix congratulatory text in badge section of user profile
  src/components/Badge/Badge.jsx
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/Badges.test.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#971 Xiaoyu Fix 951
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: do not review

#963 yihan make task summary refresh after edit and save
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: Moved to Final Review

#958 lawrence - make time logged to non tasks obvious
  src/components/TeamMemberTasks/FilteredTimeEntries.jsx
Labels: Moved to Final Review

#956 Edwin - Create way to show how many times a deadline has been updated
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/style.css
Labels: Moved to Final Review

#992 yihan make task summary refresh after edit and save
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: do not review

#981 Omar - Display only active users on create task modal
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: Moved to Final Review

#949 Papia - Added approve button functionality on taskSuggestionPage
  src/actions/task.js
  src/components/Header/Header.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionRow.jsx
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionsModal.jsx
  src/components/TaskEditSuggestions/TaskEditSuggestions.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#868 Alex- Weekly Summary| update placeholder text and add check boxes
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WeeklySummary.test.jsx
Labels: Moved to Final Review

#993 Jonathan - Add Edit Weekly Summary Options to Permissions
  src/components/PermissionsManagement/UserRoleTab.jsx
Labels: Moved to Final Review

#936 yihan eliminate need for additional “save” with adding Projects or Teams
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
  src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
  src/components/UserProfile/TeamsAndProjects/ProjectsTab.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.css
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.css
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#962 Eduardo add skeleton loading feature to all components
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/common/SkeletonLoading/SkeletonLoading.css
  src/components/common/SkeletonLoading/SkeletonLoading.jsx
  src/components/common/SkeletonLoading/index.js
Labels: Moved to Final Review

#994 Nida - Make devadmin@hgn.net password on the Dev editable only Jae
  src/__tests__/UserManagement/ResetPasswordButton.test.js
  src/__tests__/UserManagement/UserTableData.test.js
  src/components/Header/Header.jsx
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/utils/permissions.js
Labels: Moved to Final Review
