Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-06, with the labels that each got.

#852 Bada - filter members for only active
  src/components/Projects/Members/Members.jsx
Labels: Moved to Final Review

#859 Jinchao add icon to invisible users on leaderboard
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
Labels: Moved to Final Review

#837 Alex - Create a Pull Request Template
  .github/pull_request_template.md
Labels: Moved to Final Review

#849 Lucas optimize resolve task dismiss notification
  src/actions/task.js
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
Labels: Moved to Final Review

#704 Sav - Fix Profile Weekly Committed Hours Input
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: Moved to Final Review

#836 Lucile - add work confirmation improvements to people report
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
Labels: Moved to Final Review

#883 Nida - AddTaskModal & EditTaskModal - Table overflowing Modal css updates for the bug fix
  src/components/OwnerMessage/OwnerMessage.css
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: Moved to Final Review

#899 Edwin - Added new permission seeAllReports to allow users with this permissio…
  src/components/Header/Header.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/common/ProtectedRoute/ProtectedRoute.jsx
  src/routes.js
  src/utils/routePermissions.js
Labels: Moved to Final Review

#890 Alex- Add Current Prompt modal to Weekly Summary and a copy prompt function
  src/components/WeeklySummary/CurrentPromptModal.jsx
  src/components/WeeklySummary/WeeklySummary.css
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#909 Yongjian - Create back to top button on index page (NEW)
  public/index.html
  src/App.css
Labels: Moved to Final Review

#903 Sneha - Info modal for admin permission management
  src/components/PermissionsManagement/RolePermissions.jsx
Labels: Moved to Final Review

#802 Lucas fix notification icon
  package-lock.json
  src/actions/task.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
  src/components/TeamMemberTasks/reducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#901 Nathan Fix key, tbody, and required prop warnings
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/WeeklySummaries.jsx
Labels: Moved to Final Review

#906 Jinchao fixed project/task field of timeEntry component
  src/components/Timelog/TimeEntry.jsx
Labels: Moved to Final Review

#904 Jianjun - Fix the permission of changing user status
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/UserManagement/ActiveCell.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#908 Lucas revert to time log
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#905 XiaoW - optimize the request for user tasks to one post request
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#891 Nida - WeeklySummaryReportPage- Refreshing the Weekly Summaries page stay on the same summary tab
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx
Labels: Moved to Final Review

#917 fixed weekly committed hrs cannot be saved
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: Moved to Final Review

#886 Kurtis - Fix default cursor appearing on timeEntryForm in the Notes section
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
Labels: Moved to Final Review

#916 Jianjun - fix the permission of editing or deleting time entry from other users
  src/components/Timelog/TimeEntry.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#918 XiaoW Improve loading speed of new tasks resources
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
Labels: Moved to Final Review

#930 Xiaoyu - Make moving summary to another week reset the summary checkmark
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#934 Xiaow improve loading speed of wbs pages
  src/__tests__/reducers/allTasksReducer.test.js
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/reducers/allTasksReducer.js
Labels: do not review

#928 Lucile_T_make_cursor_start_in_fields
  src/components/Projects/Members/Members.jsx
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/ReportTableSearchPanel.jsx
  src/components/Teams/TeamTableSearchPanel.jsx
  src/components/UserManagement/UserSearchPanel.jsx
Labels: Moved to Final Review

#920 Edwin - Changed location and function of red x to remove a user from a task
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
  src/components/TeamMemberTasks/style.css
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#840 yihan fix weekly summary submission date
  src/__tests__/WeeklySummary.test.js
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#929 Xiaoyu Add “Media/DropBox Link” field to the new-user setup page
  src/actions/weeklySummaries.js
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WeeklySummary.test.jsx
Labels: high priority

#941 Xiaoyu Modified Modal (Add “Media/DropBox Link” field to the new-user setup page)
  src/actions/weeklySummaries.js
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WeeklySummary.test.jsx
Labels: do not review

#950 Xiaoyu separate summaryLink/Google Link
  src/actions/weeklySummaries.js
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: do not review

#952 Xiaoyu-swap name/placefolder resolve formatting issues
  src/actions/weeklySummaries.js
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: do not review

#957 Xiaoyu modify move Obtain save and separate save func
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: do not review
