Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-08, with the labels that each got.

#1030 Yufei - make intangible time numbers having a mouseover explanation editable by the owner
  package-lock.json
  package.json
  src/actions/mouseoverTextAction.js
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.css
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/Leaderboard.test.jsx
  src/components/mouseoverText/MouseoverTextTotalTimeEditButton.jsx
  src/constants/mouseoverTextConstants.js
  src/reducers/index.js
  src/reducers/mouseoverTextReducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#1089 Yufei recover mouseovertext
  src/actions/mouseoverTextAction.js
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/Leaderboard.test.jsx
  src/components/mouseoverText/MouseoverTextTotalTimeEditButton.jsx
  src/constants/mouseoverTextConstants.js
  src/reducers/index.js
  src/reducers/mouseoverTextReducer.js
  src/utils/URL.js
Labels: do not review

#1090 Yufei add new files into .eslintignore and .prettierignore.
  .eslintignore
  .prettierignore
  src/components/mouseoverText/MouseoverTextTotalTimeEditButton.jsx
Labels: do not review

#1032 Xiaow task system improvement
  src/__tests__/reducers/allTasksReducer.test.js
  src/actions/task.js
  src/actions/wbs.js
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/ControllerRow/ControllerRow.jsx
  src/components/Projects/WBS/WBSDetail/ControllerRow/index.js
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/ImportTask/ImportTask.jsx
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSDetail/Task/task.css
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
  src/reducers/allTasksReducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#982 Jinchao add seeSummaryIndicator and seeVisibilityIcon permissions
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
Labels: do not review, Moved to Final Review

#998 Papia create suggestion icon
  src/components/SummaryBar/SummaryBar.css
  src/components/SummaryBar/SummaryBar.jsx
  src/components/SummaryBar/suggestions_icon.png
Labels: Moved to Final Review

#1027 Lucile fix user filter if found users is less than 10
  src/components/UserManagement/UserTableFooter.jsx
Labels: Moved to Final Review

#1040 Lucile T make cursor start in fields second part
  src/components/Admin/Admin.jsx
  src/components/Badge/AssignBadge.jsx
  src/components/Projects/WBS/AddWBS/AddWBS.jsx
  src/components/Teams/CreateNewTeamPopup.jsx
  src/components/Teams/MembersAutoComplete.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/UserManagement/SetUpFinalDayPopUp.jsx
Labels: Moved to Final Review

#973 Edwin - Make total valid weekly summaries editable by owner/admin
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review

#980 Zubing add GoogleDoc&Dropbox links on the profile
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
Labels: Moved to Final Review

#1006 Kaixiang - make bio announcement obvious
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review

#991 Lucas fix another user dashboard
  src/__tests__/ForcePasswordUpdate.test.js
  src/__tests__/LoginPage.test.js
  src/__tests__/Timelog/TimeEntry.test.js
  src/__tests__/Timelog/TimeEntryForm.test.js
  src/__tests__/Timelog/TimeEntryForm_edit.test.js
  src/components/App.jsx
  src/components/Header/Header.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.jsx
  src/components/Timer/Timer.jsx
  src/routes.js
Labels: Moved to Final Review

#1025 Xiaoyu - Add editable role info and editable mouseover modal
  src/actions/information.js
  src/actions/userManagement.js
  src/actions/weeklySummaries.js
  src/components/PermissionsManagement/PermissionsManagement.css
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/PermissionsManagement.test.js
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.css
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/EditableModal/__mocks__/EditableMockData.js
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx
  src/constants/information.js
  src/reducers/allUserProfilesReducer.js
  src/reducers/index.js
  src/reducers/informationReducer.js
  src/routes.js
  src/services/informationService.js
  src/services/userProfileService.js
  src/utils/URL.js
  src/utils/associatedPermissions.js
Labels: Moved to Final Review

#1134 Bk/fix modal backdrop
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTaskIconsInfo.jsx
  src/components/TeamMemberTasks/infoTaskIconContent.js
Labels: Moved to Final Review

#1141 Hotfix 1025
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: do not review

#1081 Lucas create blue square reason scheduler
  src/actions/reasonsActions.js
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#1106 Lawrence - Hide sensitive data
  .circleci/config.yml
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: Moved to Final Review

#1123 Fix badge earned date
  src/actions/badgeManagement.js
  src/components/Badge/BadgeReport.jsx
Labels: Moved to Final Review

#1150 Xiaoyu- add styling and notification for 1025
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/components/UserProfile/TimeZoneDropDown.jsx
Labels: do not review

#1127 Tim fix modify own badge amount
  src/components/Badge/Badge.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/Badges.test.jsx
Labels: Moved to Final Review

#1145 Yubo-create media folder link using mediaUrl in Weekly Summary
  src/actions/weeklySummaries.js
Labels: do not review

#1135 Masasa - Rearranged permissions and indented sub_permissions
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
Labels: Moved to Final Review

#1013 yihan create submit for review button
  src/components/TeamMemberTasks/ReviewButton.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/reviewButton.css
Labels: Moved to Final Review

#1165 Xiaoyu Align fix hotfix
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.css
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/TimeZoneDropDown.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: do not review

#1116 show badges in weekly report
  src/components/Badge/Badge.css
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/BadgeTableHeader.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx
Labels: Moved to Final Review

#1005 Jianjun - all three total report feature
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalReport.css
  src/components/Reports/TotalReport/TotalReportBarGraph.css
  src/components/Reports/TotalReport/TotalReportBarGraph.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
  src/components/Reports/reportsPage.css
Labels: Moved to Final Review

#1082 Kurtis - Fix date format inconsistencies in app
  src/components/Badge/BadgeReport.jsx
  src/components/Projects/WBS/SingleTask/SingleTask.js
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleTable.js
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummary/DueDateTime.jsx
  src/utils/formatDateFromDescriptionString.js
  src/utils/formattedDate.js
Labels: Moved to Final Review

#1022 Eduardo make reports page and all reports look as good as possible on phones
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleTable.js
  src/components/Reports/PeopleTableDetails.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.css
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectTable.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TasksDetail/TasksDetail.css
  src/components/Reports/TasksDetail/TasksDetail.jsx
  src/components/Reports/TeamReport/TeamReport.css
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Reports/TeamReport/components/PieChartInfoDetail.js
  src/components/Reports/TeamReport/components/ReportCharts.css
  src/components/Reports/TeamReport/components/ReportLogs.css
  src/components/Reports/TeamReport/components/TeamReportCharts.jsx
  src/components/Reports/TeamReport/components/TeamReportLogs.jsx
  src/components/Reports/TeamReport/components/UserLoginPrivileges.jsx
  src/components/Reports/TeamTable.jsx
  src/components/Reports/WbsTable/WbsTable.css
  src/components/Reports/WbsTable/WbsTable.jsx
  src/components/Reports/reports.css
  src/components/Reports/reportsPage.css
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
Labels: Moved to Final Review

#1205 Bailey - Remove owner as creation and fix start date input field (Hot Fix)
  src/components/Reports/reportsPage.css
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/utils/permissions.js
Labels: do not review

#1201 Get user profile before time entry
  src/__tests__/Timelog/TimeEntryForm.test.js
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
Labels: do not review
