Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2023-05, with the labels that each got.

#810 Aishwarya review only --> Alan mark task done dashboard
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
Labels: do not review

#799 Ayush - Update env file to store the default password
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: do not review

#783 vitor redesign permissions page and user permission component
  src/components/PermissionsManagement/PermissionsManagement.css
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/PermissionsManagement.test.js
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
Labels: Moved to Final Review

#807 add bio requested status to report page
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
Labels: Moved to Final Review

#809 Papia fix header height
  src/components/Header/Header.css
Labels: Moved to Final Review

#817 Require node version 14
  .npmrc
  package.json
Labels: Moved to Final Review

#805 yihan fix save changes warning
  src/components/Badge/BadgeReport.jsx
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#804 Jinchao fix visibility issues in leaderboard
  src/components/LeaderBoard/LeaderBoard.container.jsx
Labels: Moved to Final Review

#808 Angelina - return to dashboard after entering weekly summaries
  src/components/Dashboard/Dashboard.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#800 Kaixiang - Create 24/48/72 hours button on team member tasks tab
  src/components/TeamMemberTasks/FilteredTimeEntries.jsx
  src/components/TeamMemberTasks/TaskButton.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/actions.js
  src/components/TeamMemberTasks/filteredTimeEntries.css
  src/components/TeamMemberTasks/reducer.js
  src/components/TeamMemberTasks/style.css
Labels: Moved to Final Review

#827 Remove ability for anyone but Owners/Admins to see the green check by…
  package-lock.json
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: Moved to Final Review

#815 add active and total member count to project report page [new]
  src/actions/projectMembers.js
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
Labels: Moved to Final Review

#831 Edwin - Added copy button to copy task names to clipboard
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
  src/components/common/Clipboard/CopyToClipboard.jsx
  src/components/common/Clipboard/style.css
Labels: Moved to Final Review

#841 Fix WBS Bug
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: Moved to Final Review

#823 Jianjun - Add bio status to weekly report
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
Labels: Moved to Final Review

#830 Added color bar for time logs
  src/components/TeamMemberTasks/FilteredTimeEntries.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/filteredTimeEntries.css
  src/constants/colors.js
Labels: Moved to Final Review

#762 Jianjun and RJ - Performance Optimization
  src/components/Dashboard/Dashboard.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#847 Edwin - Removed option for Admins to reset password for Owners
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
  src/utils/userTableDataPermissions.js
Labels: Moved to Final Review

#846 Abdel make reports buttons obvious when clicked
  src/App.css
  src/components/Reports/PeopleTable.js
  src/components/Reports/ProjectTable.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TeamTable.jsx
  src/components/Reports/reportsPage.css
Labels: Moved to Final Review

#722 Angelina - ability for manager role and above to submit weekly summary for other users
  src/components/Dashboard/Dashboard.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/PopUpBar/PopUpBar.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#806 Urgent - Ayush - Designed the star and the dot according to the logic
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: high priority

#858 only admin can edit bio in weekly summaries report
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review
