Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-08, with the labels that each got.

#2394 Harsh Weekly volunteer summary dashboard
  package-lock.json
  package.json
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/actions/totalOrgSummary.js
  src/components/Header/Header.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TotalOrgSummary/AccordianWrapper/AccordianWrapper.css
  src/components/TotalOrgSummary/AccordianWrapper/AccordianWrapper.jsx
  src/components/TotalOrgSummary/LineChart.jsx
  src/components/TotalOrgSummary/PieChart.jsx
  src/components/TotalOrgSummary/StatsCard.css
  src/components/TotalOrgSummary/StatsCard.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/VolunteerHoursDistribution/VolunteerHoursDistribution.jsx
  src/components/TotalOrgSummary/VolunteerStats.jsx
  src/components/TotalOrgSummary/WeeklyVolunteerSummary.css
  src/components/TotalOrgSummary/barChart.jsx
  src/components/TotalOrgSummary/index.js
  src/components/common/Clipboard/__tests__/CopyToClipBoard.test.js
  src/components/common/SkeletonLoading/SkeletonLoading.jsx
  src/constants/totalOrgSummary.js
  src/languages/en/ui.js
  src/reducers/index.js
  src/reducers/totalOrgSummaryReducer.js
  src/routes.js
  src/utils/URL.js
  src/utils/routePermissions.js
Labels: High Priority - Please Review First

#2262 Ishan -- > Tapan - fix timelogs tab reverting to user instead of staying on person you are viewing
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#2201 Tapan Fixed the Pagination UI in Members Table for Project Reports
  package-lock.json
  src/components/Projects/Members/Members.jsx
  src/components/Projects/Members/members.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
Labels: Needs New Developer, do not review

#2496 Peizhou_fix the assigning blue square with future date issue
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2501 Jay unit test for InfoModal component
  src/components/BMDashboard/Equipment/List/EquipmentsTable.jsx
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
  src/components/Teams/__tests__/InfoModal.test.js
Labels: Moved to Final Review

#2276 Gowtham fix team location search error
  src/components/TeamLocations/TeamLocations.jsx
Labels: High Priority - Please Review First

#2521 Select color multiselect in Weekly Summaries Report overlaps with toggle buttons
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
Labels: High Priority - Please Review First

#2430 Abdel fix followup style
  src/components/TeamMemberTasks/FollowUpCheckButton.css
  src/components/TeamMemberTasks/FollowUpInfoModal.css
  src/components/TeamMemberTasks/FollowUpInfoModal.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/__tests__/TeamMemberTasks.test.js
  src/components/TeamMemberTasks/style.css
  src/components/Timelog/Timelog.css
  src/components/Timelog/Timelog.jsx
Labels: do not review

#2516 akshit added warning when team already exists
  src/components/Teams/CreateNewTeamPopup.jsx
Labels: High Priority - Please Review First

#2519 Akshit fix map remove option for users
  src/components/TeamLocations/ListUsersPopUp.jsx
  src/components/TeamLocations/MarkerPopup.jsx
Labels: Moved to Final Review

#2529 Jiadong - Replace Badges Section on Dashboard
  src/actions/badgeManagement.js
  src/components/Dashboard/Dashboard.jsx
  src/components/Timelog/Timelog.jsx
  src/constants/badge.js
  src/reducers/badgeReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2523 Ambika - do not allow picture additions in timelog and summaries
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/WeeklySummaries.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#2431 Jiayu add standard time entry and description to "add lost time"
  src/components/Reports/LostTime/AddLostTime.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2005 Akshit taking over for Yixiao - Improve tasks contributed section report
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.css
  src/components/Reports/PeopleTableDetails.css
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/TableFilter/TableFilter.jsx
  src/components/Reports/TasksTable/TasksTable.css
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/UserManagement/TextSearchBox.jsx
  src/components/UserManagement/TextSuggestion.jsx
Labels: High Priority - Please Review First

#2538 Chetan added the redirection part to the current user
  src/components/Header/Header.jsx
Labels: Moved to Final Review

#2332 Peterson implement toast when user is already in a team
  src/actions/allTeamsAction.js
  src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
  src/components/UserProfile/TeamsAndProjects/AddTeamsAutoComplete.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/TeamsAndProjects/__tests__/AddTeamPopup.test.js
Labels: High Priority - Please Review First

#2507 Shrada Fix missing form validation in user profile page
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: Moved to Final Review

#2541 ambika volunteer should not be able to complete reviews for their own tasks
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: High Priority - Please Review First

#2560 Rama fixed text color darkmode
  src/components/Badge/BadgeReport.jsx
Labels: Moved to Final Review

#2524 Howie accurate end date
  src/actions/timeEntries.js
  src/actions/userManagement.js
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2421 Yili fix permissions management info icon
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/PermissionsManagement/RolePermissions.jsx
Labels: High Priority - Please Review First

#2552 Ishan -> Reports Page on Mobile dimensions can’t scroll horizontally for results
  src/components/Reports/PeopleTable.js
  src/components/Reports/reports.css
Labels: Moved to Final Review

#2492 Howie fix team scroll bar
  src/components/Teams/Team.css
  src/components/Teams/Teams.jsx
Labels: Moved to Final Review

#2559 Chetan Fixed email validation and location of success message
  src/actions/sendEmails.js
  src/components/Announcements/index.jsx
Labels: Moved to Final Review, medium priority

#2383 Huijie fix times on timelog and profile page don't match
  src/components/Timelog/EffortBar.jsx
Labels: High Priority - Please Review First, high priority

#2451 Shrada Fix Projects Page UI
  src/components/Projects/Overview/Overview.jsx
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/projects.css
Labels: Moved to Final Review

#2515 Logeshwari - Fixed Blank Page error on Team Location search
  src/components/TeamLocations/TeamLocations.css
  src/components/TeamLocations/TeamLocations.jsx
  src/components/TeamLocations/TeamLocationsTable.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2503 Carlos Volunteer Hours Distribution
  src/actions/allUsersTimeEntries.js
  src/actions/index.js
  src/components/Header/Header.jsx
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.jsx
  src/components/Reports/ProjectReport/ProjectPieChart/ProjectPieChart.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectReport/WbsPiechart/WbsPieChart.jsx
  src/components/TotalOrgSummary/HoursWorkList/HoursWorkList.jsx
  src/components/TotalOrgSummary/HoursWorkedPieChart/HoursWorkedPieChart.jsx
  src/components/TotalOrgSummary/NumbersVolunteerWorked/NumbersVolunteerWorked.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/VolunteerHoursDistribution/VolunteerHoursDistribution.jsx
  src/constants/allUsersTimeEntries.js
  src/reducers/allUsersTimeEntriesReducer.js
  src/reducers/index.js
Labels: High Priority - Please Review First

#2469 Ramakrishna edit all team code at Once
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#2488 Vishavdeep fix timelog page UI issues for 375px and up
  src/components/Timelog/Timelog.css
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#2532 Ivy-Fix the incomplete Members list when the ALL-TIME button is selected
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
Labels: Moved to Final Review

#2602 Ishan- hotfix for teams table and badge redirection issues
  src/components/Reports/TeamTable.css
  src/components/Reports/TeamTable.jsx
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#2603 Ivy-isSet-finalday
  src/components/UserManagement/SetUpFinalDayButton.jsx
Labels: High Priority - Please Review First

#2326 Jay fix color discrepancy for pie chart in PeopleReport
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
  src/components/common/PieChart/PieChart.css
  src/components/common/PieChart/PieChart.jsx
Labels: Moved to Final Review

#2606 Satya_Improve_modal_efficiency_for_adding_Teams
  src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
Labels: Moved to Final Review

#2601 Ishan fix profile page formatting
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.css
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: High Priority - Please Review First

#2297 Jay unit tests for SetUpFinalDayPopUp
  src/components/UserManagement/__tests__/SetUpFinalDayButton.test.js
Labels: Moved to Final Review

#2462 Jay unit tests for SameFolderTasks component
  src/components/BMDashboard/Equipment/List/EquipmentsTable.jsx
  src/components/Projects/WBS/SameFolderTasks/SameFolderTasks.js
  src/components/Projects/WBS/__tests__/SameFolderTasks.test.js
Labels: Moved to Final Review

#2623 Move App from Surge to Netlify
  LICENSE
  README.md
  src/components/Footer/NetlifyPoweredLink.js
  src/components/Login/Login.jsx
Labels: High Priority - Please Review First

#2440 Diya Changes to display specific error
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First
