Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-04, with the labels that each got.

#2103 fixed the edit time off request validation
  src/components/UserManagement/logTimeOffPopUp.jsx
  src/components/UserManagement/usermanagement.css
Labels: do not review

#1940 Zuhang_fix_blue_circle_for_three_digit_numbers
  src/components/Badge/Badge.css
Labels: Moved to Final Review

#2091 Nahiyan_Fixed white screen error on dashboard and timelog
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
Labels: do not review

#2067 Pratima Active Checkbox Toggle Fix
  src/components/Reports/TasksTable/TasksTable.jsx
  src/components/common/Checkbox/Checkbox.jsx
Labels: do not review, Moved to Final Review

#1987 Nahiyan_Add a project page title and the most relevant project information
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
  src/components/Reports/ProjectReport/selectors.js
  src/components/Reports/TasksDetail/TasksDetail.jsx
  src/components/Reports/WbsTable/WbsTable.jsx
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/ReportHeader.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/ReportHeader.jsx
  src/components/common/Paging/Paging.jsx
Labels: Moved to Final Review

#2075 Gabriele - Fix layout in add task modal in projects/wbs
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: Moved to Final Review

#2065 Gabriele - Fix user management inputs layout
  src/components/UserManagement/DropDownSearchBox.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
Labels: Moved to Final Review

#2124 Sucheta - Adds user's ability to check entered password to reveal the weeklySummaryRecipient for Authorized users only
  src/components/WeeklySummariesReport/PasswordInputModal.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummaryRecepientsPopup.jsx
Labels: High Priority - Please Review First

#1331 Yongjian remove admin or owner ability to delete themselves
  src/components/Timer/Countdown.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
Labels: Moved to Final Review

#1915 Leo Add more specific link validation for GDoc links
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
  src/utils/checkValidURL.js
Labels: Moved to Final Review

#1976 Sai deepak character countdown desc
  package-lock.json
  src/components/BMDashboard/BMDashboard.css
  src/components/BMDashboard/Equipment/Add/AddTypeForm.jsx
Labels: Moved to Final Review

#2079 Nahiyan_Fix Basic Information tab UI (Tablet View)
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: Moved to Final Review

#1931 Nahiyan-Project's tab overhaul
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2096 Shiqing restore reports page formatting
  src/components/Reports/Reports.jsx
  src/components/Reports/reportsPage.css
Labels: Moved to Final Review, High Priority - Please Review First

#1889 Nathan permissions unit test utility
  src/__tests__/mockStates.js
  src/components/PermissionsManagement/PermissionsConst.js
Labels: High Priority - Please Review First

#2032 Jingyi-User Profile: Rehireable / Notrehireable Check Box
  src/actions/userManagement.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/UserProfile/UserProfile.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#2125 Abdel time off summary on user profile
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.css
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.css
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.jsx
  src/components/UserProfile/TimeOffRequestsTable/TimeOffRequestsTable.css
  src/components/UserProfile/TimeOffRequestsTable/TimeOffRequestsTable.jsx
  src/components/UserProfile/UserProfile.scss
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
Labels: do not review

#2084 Shiqing fix weekly summaries submission page formatting
  src/components/WeeklySummary/WeeklySummary.css
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: Moved to Final Review

#2111 Shiwani WBSTasks unit test
  src/components/Projects/WBS/WBSDetail/__tests__/WBSTasks.test.js
Labels: Moved to Final Review

#2100 created projectstab's test file
  src/components/UserProfile/TeamsAndProjects/__tests__/ProjectsTab.test.js
Labels: Moved to Final Review

#2101 Ramya Unit Test : BioFunction
  src/components/WeeklySummariesReport/__tests__/BioFunction.test.js
Labels: Moved to Final Review

#2105 Nahiyan_dark mode on Dashboard and Timelog page
  src/App.css
  src/__tests__/mockStates.js
  src/components/Badge/Badge.css
  src/components/Badge/Badge.jsx
  src/components/Badge/NewBadges.jsx
  src/components/Badge/OldBadges.jsx
  src/components/Badge/__tests__/Badge.test.js
  src/components/Badge/__tests__/NewBadges.test.js
  src/components/Badge/__tests__/OldBadges.test.js
  src/components/Dashboard/Dashboard.jsx
  src/components/Header/DarkModeButton.css
  src/components/Header/DarkModeButton.jsx
  src/components/Header/Header.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
  src/components/Reports/BadgeSummaryViz.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/TeamMemberTasks/ReviewButton.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTaskIconsInfo.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/__tests__/TeamMemberTask.test.js
  src/components/Timelog/Timelog.css
  src/components/Timelog/Timelog.jsx
  src/components/Timelog/WeeklySummaries.jsx
  src/components/WeeklySummary/CountdownTimer.jsx
  src/components/WeeklySummary/CurrentPromptModal.jsx
  src/components/WeeklySummary/DueDateTime.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/common/Clipboard/CopyToClipboard.jsx
  src/components/common/Clipboard/__tests__/CopyToClipBoard.test.js
  src/reducers/index.js
  src/reducers/themeReducer.js
  src/styles.js
Labels: Moved to Final Review

#2130 Yaohong improve report apearance
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleTableDetails.jsx
Labels: do not review, Moved to Final Review

#2158 Gayathri_lint_fix_for_common_component
  .eslintignore
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/common/BMDashboard/BMProtectedRoute/BMProtectedRoute.jsx
  src/components/common/BMDashboard/BMProtectedRoute/index.js
  src/components/common/Checkbox/Checkbox.jsx
  src/components/common/Checkbox/index.js
  src/components/common/CheckboxCollection/CheckboxCollection.jsx
  src/components/common/CheckboxCollection/index.js
  src/components/common/Clipboard/CopyToClipboard.jsx
  src/components/common/Clipboard/CopyToClipboard_2.jsx
  src/components/common/DragAndDrop/DragAndDrop.jsx
  src/components/common/Dropdown/Dropdown.jsx
  src/components/common/Dropdown/index.js
  src/components/common/FileUpload/FileUpload.jsx
  src/components/common/FileUpload/index.js
  src/components/common/Form/Form.jsx
  src/components/common/Form/index.js
  src/components/common/GoogleDocIcon/GoogleDocIcon.jsx
  src/components/common/Image/Image.jsx
  src/components/common/Image/index.js
  src/components/common/Input/Input.jsx
  src/components/common/Input/index.js
  src/components/common/Loading/Loading.jsx
  src/components/common/Loading/index.js
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/index.js
  src/components/common/NewModal/NewModal.jsx
  src/components/common/NewModal/index.js
  src/components/common/Paging/Paging.jsx
  src/components/common/Paging/Paging.test.jsx
  src/components/common/Paging/index.js
  src/components/common/PhoneInput/PhoneInput.jsx
  src/components/common/PieChart/PieChart.jsx
  src/components/common/PieChart/colorsGenerator.js
  src/components/common/PieChart/index.js
  src/components/common/ProtectedRoute/ProtectedRoute.jsx
  src/components/common/ProtectedRoute/index.js
  src/components/common/Radio/Radio.jsx
  src/components/common/Radio/index.js
  src/components/common/ShowSaveWarning.jsx
  src/components/common/SkeletonLoading/SkeletonLoading.jsx
  src/components/common/SkeletonLoading/index.js
  src/components/common/Stub/Stub.jsx
  src/components/common/Stub/index.js
  src/components/common/TinyceEditor/index.js
  src/components/common/TinyceEditor/tinymceEditor.jsx
Labels: medium priority

#2086 Shengjie unit test codes for TagSent in WBS
  src/components/Projects/WBS/__tests__/TagSent.WBS.test.js
Labels: Moved to Final Review

#2112 Nahiyan dark mode for login screen
  src/__tests__/__snapshots__/ForcePasswordUpdate.test.js.snap
  src/components/ForcePasswordUpdate/ForcePasswordUpdate.jsx
  src/components/Login/ForgotPassword.jsx
  src/components/Login/ForgotPassword.test.jsx
  src/components/Login/Login.jsx
  src/components/UpdatePassword/UpdatePassword.jsx
  src/components/UpdatePassword/__tests__/UpdatePassword.test.js
  src/components/common/Form/Form.jsx
  src/components/common/Input/Input.jsx
Labels: High Priority - Please Review First

#2126 Nahiyan dark mode for reports page
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Reports/BadgeSummaryPreview.jsx
  src/components/Reports/InfringementsViz.jsx
  src/components/Reports/LostTime/EditHistoryModal.jsx
  src/components/Reports/LostTime/LostTimeHistory.jsx
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
  src/components/Reports/PeopleReport/selectors.js
  src/components/Reports/PeopleTable.js
  src/components/Reports/PeopleTableDetails.css
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.css
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
  src/components/Reports/ProjectTable.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TasksDetail/TasksDetail.jsx
  src/components/Reports/TasksTable/TasksTable.jsx
  src/components/Reports/TeamReport/TeamReport.css
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Reports/TeamReport/components/PieChartInfoDetail.js
  src/components/Reports/TeamReport/components/TeamReportCharts.jsx
  src/components/Reports/TeamReport/components/TeamReportLogs.jsx
  src/components/Reports/TeamReport/components/TeamsReportCharts.jsx
  src/components/Reports/TeamReport/components/TeamsReportLogs.jsx
  src/components/Reports/TeamReport/components/UserLoginPrivileges.jsx
  src/components/Reports/TeamTable.jsx
  src/components/Reports/TimeEntriesViz.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
  src/components/Reports/WbsTable/WbsTable.jsx
  src/components/Reports/reports.css
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/Reports/sharedComponents/ReportPage/ReportPage.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/ReportHeader.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/ReportHeader.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
  src/components/common/Checkbox/Checkbox.jsx
  src/components/common/Loading/Loading.jsx
  src/components/common/Paging/Paging.css
  src/components/common/Paging/Paging.jsx
  src/components/common/PieChart/PieChart.jsx
  src/components/common/Stub/Stub.jsx
Labels: do not review

#2131 XiaoW_Refactor of time entry controller and fix edit history issue
  src/actions/task.js
  src/actions/timeEntries.js
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/Timelog/DeleteModal.jsx
  src/components/Timelog/TimeEntry.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/__tests__/DeleteModal.test.js
  src/utils/checkNegativeHours.js
  src/utils/fixDiscrepancy.js
Labels: High Priority - Please Review First

#935 Abdel deadline follow up tracking solution
  package-lock.json
  src/actions/followUpActions.js
  src/components/TeamMemberTasks/FollowUpCheckButton.css
  src/components/TeamMemberTasks/FollowUpInfoModal.css
  src/components/TeamMemberTasks/FollowUpInfoModal.jsx
  src/components/TeamMemberTasks/FollowupCheckButton.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/style.css
  src/constants/followUpConstants.js
  src/reducers/followUpReducer.js
  src/reducers/index.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2175 Fix issue with time off request updates not being reflected for the o…
  src/components/UserProfile/UserProfile.jsx
Labels: do not review

#2031 Tapan - Fixed UI for Create New Role Without Name and Permission
  src/components/PermissionsManagement/NewRolePopUp.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#1784 Haoji new email sender
  src/components/Announcements/index.jsx
Labels: High Priority - Please Review First

#2174 Shereen Unit Test UserProfileAdd
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/AddNewUserProfile/__test__/UserProfileAdd.test.js
Labels: Moved to Final Review

#2162 Nahiyan dark mode for user profile page
  src/components/UserManagement/PauseAndResumeButton.jsx
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserProfile/Badge.css
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.css
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.jsx
  src/components/UserProfile/TeamWeeklySummaries/TeamWeeklySummaries.jsx
  src/components/UserProfile/TeamsAndProjects/ProjectsTab.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/TimeEntryEditHistory.jsx
  src/components/UserProfile/TimeOffRequestsTable/TimeOffRequestsTable.jsx
  src/components/UserProfile/UserLinkLayout/UserLinkLayout.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/LinkModButton.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.module.scss
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: High Priority - Please Review First

#2127 Nahiyan dark mode for weekly summaries reports page
  src/components/TeamLocations/TeamLocations.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/GeneratePdfReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/common/SkeletonLoading/SkeletonLoading.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#2128 Nahiyan dark mode for user badge and permissions management
  src/components/Badge/AssignBadge.jsx
  src/components/Badge/BadgeDevelopment.jsx
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/BadgeManagement.jsx
  src/components/Badge/BadgeTableFilter.jsx
  src/components/Badge/BadgeTableHeader.jsx
  src/components/Badge/__tests__/AssignBadge.test.js
  src/components/Badge/__tests__/BadgeDevelopmentTable.test.js
  src/components/PermissionsManagement/PermissionChangeLogTable.css
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
  src/components/PermissionsManagement/PermissionList.jsx
  src/components/PermissionsManagement/PermissionListItem.jsx
  src/components/PermissionsManagement/PermissionsManagement.css
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/PermissionsManagement.test.js
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/PermissionsManagement/__tests__/UserRoleTab.test.js
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableFooter.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
Labels: High Priority - Please Review First

#2010 Ilya - Consumables: Single Update
  src/actions/bmdashboard/consumableActions.js
  src/components/BMDashboard/ConsumableList/ConsumableListView.jsx
  src/components/BMDashboard/UpdateConsumables/UpdateConsumable.css
  src/components/BMDashboard/UpdateConsumables/UpdateConsumable.jsx
  src/components/BMDashboard/UpdateConsumables/UpdateConsumableModal.jsx
  src/constants/bmdashboard/consumableConstants.js
  src/reducers/bmdashboard/consumablesReducer.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2050 Shengwei add stop blue sqaure added to new user
  src/actions/notificationAction.js
  src/components/Header/Header.jsx
  src/components/Notification/notificationCard.jsx
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleTable.js
  src/components/Reports/Reports.jsx
  src/components/Reports/__tests__/PeopleTable.test.js
  src/components/Teams/Teams.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/UserManagement/NewUserPopup.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/setupNewUserPopup.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/UserProfileEdit.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/constants/notification.js
  src/reducers/index.js
  src/reducers/notificationReducer.js
  src/reducers/notificationsReducer.js
  src/reducers/userTeamMembersReducer.js
  src/utils/formatDate.js
Labels: high priority, High Priority - Please Review First

#2192 Nahiyan_dark mode on taskeditsuggestions
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionRow.jsx
  src/components/TaskEditSuggestions/TaskEditSuggestions.jsx
  src/components/TaskEditSuggestions/__tests__/TaskEditSuggestions.test.js
  src/components/TaskEditSuggestions/__tests__/selectors.test.js
  src/components/TaskEditSuggestions/selectors.js
  src/components/TeamMemberTasks/FollowUpInfoModal.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTaskIconsInfo.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/common/Clipboard/CopyToClipboard.jsx
Labels: High Priority - Please Review First

#2089 Xiaohan fix profile assign badge
  src/components/Header/Header.jsx
  src/components/UserProfile/Badges.jsx
  src/utils/routePermissions.js
Labels: Moved to Final Review, High Priority - Please Review First

#2177 Yixiao summarybar unittest
  src/components/SummaryBar/__tests__/SummaryBar.test.js
Labels: High Priority - Please Review First

#2165 Shengjie unittest tinyce
  src/components/common/TinyceEditor/TinymceEditor.test.jsx
Labels: Moved to Final Review

#1582 Shrey_unit_test_TinymceEditor
  src/components/common/TinyceEditor/TinymceEditor.test.jsx
Labels: Moved to Final Review, Needs New Developer

#2147 Nahiyan dark mode on projects and teams page
  src/components/Announcements/index.jsx
  src/components/Inventory/Inventory.jsx
  src/components/Projects/Members/FoundUser/FoundUser.jsx
  src/components/Projects/Members/Member/Member.jsx
  src/components/Projects/Members/Members.jsx
  src/components/Projects/Project/Project.jsx
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/ImportTask/ImportTask.jsx
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/__tests__/WBSTasks.test.js
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/wbs.jsx
  src/components/Teams/Team.jsx
  src/components/Teams/TeamTableHeader.jsx
  src/components/Teams/TeamTableSearchPanel.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/TeamsOverview.jsx
  src/components/Teams/__tests__/Team.test.js
Labels: High Priority - Please Review First
