Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-03, with the labels that each got.

#1969 Shiwani WBSItem unit test
  src/components/Projects/WBS/WBSItem/__tests__/WBSItem.test.js
Labels: Moved to Final Review

#1977 Shereen - Unit tests for SaveButton component.
  src/components/UserProfile/UserProfileEdit/__test__/SaveButton.test.js
Labels: Moved to Final Review

#1978 Shiwani ProjectReport unit test
  src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
Labels: Moved to Final Review

#2003 Masasa_Fixed the inactive and active issue sorting
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
Labels: Moved to Final Review

#1967 Nahiyan_Added padding to the projects and teams report container
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
Labels: Moved to Final Review

#1773 Shiwani AddNewTeamModal Unit Test
  src/components/UserProfile/__tests__/AddNewTeamModal.test.js
Labels: Moved to Final Review

#2009 Abdel update bleu square scheduler
  src/actions/reasonsActions.js
  src/actions/timeOffRequestAction.js
  src/components/Dashboard/TimeOffRequestDetailModal.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
  src/components/UserManagement/logTimeOffPopUp.jsx
  src/components/UserManagement/usermanagement.css
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/ScheduleExplanationModal/ScheduleExplanationModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.css
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModalCard.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/UserProfileEdit.scss
  src/utils/URL.js
Labels: do not review

#1676 Palak - AssignTableRow Unit Test Cases
  src/components/Badge/AssignTableRow.test.js
Labels: do not review

#1560 TuanDinh_TeamsReportLogs_UnitTest
  src/components/Reports/TeamReport/components/__tests__/TeamsReportLogs.test.js
Labels: Moved to Final Review

#1980 Shuhua add google doc icon
  src/assets/images/google_doc_icon.png
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/google_doc_icon_gray.png
  src/components/common/GoogleDocIcon/GoogleDocIcon.jsx
  src/components/common/GoogleDocIcon/index.js
  src/components/common/GoogleDocIcon/style.css
Labels: High Priority - Please Review First

#1985 Christy - make WBS names active links
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/WbsTable/WbsTable.jsx
  src/utils/viewWBSpermissionsRequired.js
Labels: Moved to Final Review

#2006 Sucheta - Create Summary Report Recipient Button
  src/actions/weeklySummariesReportRecepients.js
  src/components/Teams/MembersAutoComplete.jsx
  src/components/WeeklySummariesReport/PasswordInputModal.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummaryRecepientsPopup.jsx
  src/constants/weeklySummariesReport.js
  src/reducers/index.js
  src/reducers/weeklySummaryRecipientsReducer.js
  src/utils/URL.js
Labels: do not review

#2024 Yi - User Profile: Remove inactive accounts from summary intro
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#1991 Renanluiz add missing shadow style
  src/components/Badge/Badge.css
  src/components/Badge/Badge.jsx
  src/components/LeaderBoard/Leaderboard.css
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/reports.css
  src/components/Timelog/Timelog.css
  src/components/Timelog/Timelog.jsx
  src/components/UserProfile/TeamsAndProjects/AddProjectsAutoComplete.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.css
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#2051 Abdel Rebuilding the new blue square scheduler
  src/actions/timeOffRequestAction.js
  src/components/Dashboard/TimeOffRequestDetailModal.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
  src/components/UserManagement/logTimeOffPopUp.jsx
  src/components/UserManagement/usermanagement.css
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/ScheduleExplanationModal/ScheduleExplanationModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.css
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModalCard.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/UserProfileEdit.scss
Labels: do not review

#2055 fixed explanation modal
  src/components/UserProfile/ScheduleExplanationModal/ScheduleExplanationModal.jsx
Labels: do not review

#2056 Fix thank you message for home country option not showing
  src/components/SetupProfile/SetupProfileUserEntry.jsx
  src/components/SetupProfile/homeCountryModal.jsx
Labels: do not review

#1511 Yixiao_TaskEditSuggestionRow_unittest
  src/components/TaskEditSuggestions/Components/__tests__/TaskEditSuggestionRow.test.js
Labels: Moved to Final Review

#1935 Yixiao_form_unittest
  src/components/TaskEditSuggestions/__tests__/thunks.test.js
  src/components/common/Form/Form.jsx
  src/components/common/Form/__tests__/Form.test.js
Labels: Moved to Final Review

#1588 Roberto - enhances save changes modal to notify request is still processing
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/components/UserProfile/UserProfileModal/EditConfirmModal.jsx
Labels: Moved to Final Review

#1843 Changhao - added new unit tests for usertablesearchheader
  src/components/UserManagement/__test__/UserTableSearchHeader.test.js
Labels: Moved to Final Review

#1979 Chengyan phase2 reusable purchase item form frontend
  src/actions/bmdashboard/invTypeActions.js
  src/actions/bmdashboard/reusableActions.js
  src/components/BMDashboard/MaterialPurchaseRequest/PurchaseForm.css
  src/components/BMDashboard/MaterialPurchaseRequest/PurchaseForm.jsx
  src/components/BMDashboard/MaterialPurchaseRequest/PurchaseMaterials.css
  src/components/BMDashboard/MaterialPurchaseRequest/PurchaseMaterials.jsx
  src/components/BMDashboard/MaterialPurchaseRequest/index.js
  src/components/BMDashboard/PurchaseRequests/MaterialPurchaseRequest/MaterialPurchaseForm.jsx
  src/components/BMDashboard/PurchaseRequests/MaterialPurchaseRequest/index.js
  src/components/BMDashboard/PurchaseRequests/PurchaseForm.css
  src/components/BMDashboard/PurchaseRequests/PurchaseForm.jsx
  src/components/BMDashboard/PurchaseRequests/ReusablePurchaseRequest/ReusablePurchaseForm.jsx
  src/components/BMDashboard/PurchaseRequests/ReusablePurchaseRequest/index.js
  src/constants/bmdashboard/inventoryTypeConstants.js
  src/reducers/bmdashboard/inventoryTypeReducer.js
  src/routes.js
  src/utils/URL.js
Labels: Moved to Final Review

#2026 Shengwei add Jae related account edit permission for timelog and timeoff
  src/components/Dashboard/Dashboard.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/utils/permissions.js
Labels: do not review

#2066 Nahiyan_Add view password eye
  src/__tests__/__snapshots__/ForcePasswordUpdate.test.js.snap
  src/components/Login/ForgotPassword.jsx
  src/components/UpdatePassword/UpdatePassword.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/input.css
Labels: low priority

#2080 fix invalid date in the blue square description
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
Labels: do not review

#2082 Fix leaderboard time off indicator
  src/components/Dashboard/TimeOffRequestDetailModal.jsx
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/style.css
  src/reducers/timeOffRequestReducer.js
Labels: do not review

#1908 John Add new total row to Leaderboard
  src/components/LeaderBoard/Leaderboard.css
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/utils/leaderboardPermissions.js
Labels: Moved to Final Review

#2068 Shengjie new badges unit test cont
  .prettierignore
  src/components/Badge/__tests__/NewBadges.test.js
Labels: Moved to Final Review

#2047 Nahiyan_Fix the badge development table so it displays correctly on smaller screen sizes.
  src/components/Badge/Badge.css
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/BadgeManagement.jsx
  src/components/Badge/BadgeTableFilter.jsx
  src/components/Badge/BadgeTableHeader.jsx
Labels: medium priority

#2095 Fix user initial setup style and home country modal
  src/components/Announcements/Announcements.css
  src/components/Announcements/index.jsx
  src/components/SetupProfile/SetupProfileUserEntry.css
  src/components/SetupProfile/SetupProfileUserEntry.jsx
  src/components/SetupProfile/homeCountryModal.jsx
Labels: do not review

#2074 Navneeth add implementation for resolveTask permission
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#2072 Jerry - Unit test NewRolePopUp.jsx
  src/components/PermissionsManagement/__tests__/NewRolePopUp.test.js
Labels: Moved to Final Review

#2042 Jerry - Unit test AssignBadge.jsx
  src/components/Badge/AssignBadge.jsx
  src/components/Badge/__tests__/AssignBadge.test.js
Labels: Moved to Final Review

#2069 Tareq - Fix map component scrolling
  src/components/TeamLocations/TeamLocations.css
  src/components/TeamLocations/TeamLocations.jsx
Labels: Moved to Final Review

#1845 Roberto fix view other user dashboard
  src/components/Dashboard/Dashboard.jsx
  src/components/Header/Header.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
  src/components/Logout/Logout.jsx
  src/components/PopUpBar/PopUpBar.css
  src/components/PopUpBar/PopUpBar.jsx
  src/components/PopUpBar/__tests__/PopUpBar.test.jsx
  src/components/PopUpBar/index.js
  src/components/SummaryBar/SummaryBar.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#2076 Shiwani UserRoleTab unit test
  src/components/PermissionsManagement/__tests__/UserRoleTab.test.js
Labels: Moved to Final Review

#2073 Nahiyan_Added a confirm password input
  src/__tests__/__snapshots__/ForcePasswordUpdate.test.js.snap
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/common/Input/Input.jsx
Labels: High Priority - Please Review First
