Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-11, with the labels that each got.

#2780 Jatin improve report loading time
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
  test.json
Labels: High Priority - Please Review First

#2810 Rishitha user management lint fix
  .circleci/config.yml
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/ActivationDatePopup.jsx
  src/components/UserManagement/ActiveCell.jsx
  src/components/UserManagement/ActiveCell.test.js
  src/components/UserManagement/ActiveInactiveConfirmationPopup.jsx
  src/components/UserManagement/DeleteUserPopup.jsx
  src/components/UserManagement/DropDownSearchBox.jsx
  src/components/UserManagement/DuplicateNamePopup.jsx
  src/components/UserManagement/NewUserPopup.jsx
  src/components/UserManagement/PauseAndResumeButton.jsx
  src/components/UserManagement/ProfileNavDot.jsx
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserManagement/SetUpFinalDayPopUp.jsx
  src/components/UserManagement/SetupHistoryPopup.jsx
  src/components/UserManagement/TextSearchBox.jsx
  src/components/UserManagement/TextSuggestion.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableFooter.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
  src/components/UserManagement/__test__/ResetPasswordPopup.test.js
  src/components/UserManagement/__tests__/ActivationDatePopup.test.js
  src/components/UserManagement/__tests__/ActiveCell.test.js
  src/components/UserManagement/__tests__/ActiveInactiveConfirmationPopup.test.js
  src/components/UserManagement/__tests__/DeleteUserPopup.test.js
  src/components/UserManagement/__tests__/DropDownSearchBox.test.js
  src/components/UserManagement/__tests__/DuplicateNamePopup.test.js
  src/components/UserManagement/__tests__/NewUserPopup.test.js
  src/components/UserManagement/__tests__/PauseAndResumeButton.test.js
  src/components/UserManagement/__tests__/ResetPasswordButton.test.js
  src/components/UserManagement/__tests__/ResetPasswordPopup.test.js
  src/components/UserManagement/__tests__/SetUpFinalDayButton.test.js
  src/components/UserManagement/__tests__/TextSearchBox.test.js
  src/components/UserManagement/__tests__/UserSearchPanel.test.js
  src/components/UserManagement/__tests__/UserTableData.test.js
  src/components/UserManagement/__tests__/UserTableFooter.test.js
  src/components/UserManagement/__tests__/UserTableHeader.test.js
  src/components/UserManagement/__tests__/UserTableSearchHeader.test.js
  src/components/UserManagement/logTimeOffPopUp.jsx
  src/components/UserManagement/setupNewUserPopup.jsx
Labels: High Priority - Please Review First

#2799 Shreya leaderboard unit test
  jest.config.js
  package-lock.json
  package.json
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.js
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
Labels: medium priority

#2309 Sai Preetham taking over for Clemar add a reminder to save changes modal to permissions management page
  src/components/App.jsx
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.jsx
  src/components/PermissionsManagement/PermissionListItem.jsx
  src/components/PermissionsManagement/PermissionsManagement.css
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/PermissionsManagement.test.js
  src/components/PermissionsManagement/ReminderModal.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/PermissionsManagement/__tests__/NewRolePopUp.test.js
  src/components/PermissionsManagement/__tests__/RolePermissions.test.js
  src/components/PermissionsManagement/__tests__/UserPermissionsPopup.test.js
  src/components/PermissionsManagement/__tests__/UserRoleTab.test.js
  src/context/ModalContext.jsx
Labels: High Priority - Please Review First

#2692 Shefali PeopleReport selectors unit test
  src/components/Reports/PeopleReport/__tests__/selectors.test.js
Labels: Moved to Final Review

#2672 Shefali unit test pie chart
  src/components/common/PieChart/PieChart.test.jsx
  src/components/common/PieChart/__tests__/PieChart.test.js
  src/components/common/PieChart/__tests__/colorsGenerator.test.js
Labels: Moved to Final Review

#2670 Shefali colorsGenerator Unit Test
  src/components/common/PieChart/__tests__/colorsGenerator.test.js
Labels: Moved to Final Review

#2832 Ziyu-add-unit-test-for-QuickSetupModal
  src/components/UserProfile/QuickSetupModal/__mock__/mockData.js
  src/components/UserProfile/QuickSetupModal/__test__/QuickSetupModal.test.js
Labels: Moved to Final Review

#1907 Changhao-added new unit tests for weeklysummariesreport.test.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2595 Angela - MailChimp Replacement
  src/components/Announcements/index.jsx
Labels: High Priority - Please Review First

#2817 Swathi Add a button to display paused tasks on the top of the table.
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
Labels: High Priority - Please Review First

#2760 Deepthi add title with info icon to Teams page
  src/components/Teams/Team.css
  src/components/Teams/Teams.jsx
Labels: High Priority - Please Review First

#2547 Anand_Implemented Task Deadline Count Update in Dashboard
  src/actions/dashboardActions.js
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionsModal.jsx
  src/components/TaskEditSuggestions/TaskEditSuggestions.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/reducers/dashboardReducer.js
  src/reducers/index.js
Labels: High Priority - Please Review First, Moved to Final Review

#2796 Ambika fix reports teams calendar cropping issue
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.css
Labels: High Priority - Please Review First

#2676 Ajay - fix person name search on project page frontend
  src/actions/userProfile.js
  src/components/Projects/Projects.jsx
  src/components/Projects/projects.css
  src/components/SearchProjectByPerson/SearchProjectByPerson.jsx
  src/constants/userProfile.js
  src/utils/URL.js
Labels: medium priority

#2849 Ajay - Add title and sort functions to Projects WBS Pages Other
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/__tests__/WBSTasks.test.js
  src/components/Projects/WBS/wbs.jsx
  src/reducers/index.js
Labels: High Priority - Please Review First

#2685 Peterson implement default error page to be created and redirected to
  public/imagePage404.png
  public/imagePage404DarkMode.png
  src/components/Logout/Logout.jsx
  src/components/Notification/__tests__/notification.test.js
  src/components/Notification/notificationCard.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/not-found/notFoundPage.css
  src/components/not-found/notFoundPage.jsx
  src/routes.js
Labels: do not review

#2858 Peterson_implement_improvements_in_the_My_Team_filter
  src/components/Dashboard/Dashboard.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/__tests__/TaskButton.test.js
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/ProfileNavDot.jsx
  src/components/UserProfile/TeamsAndProjects/autoComplete.css
Labels: do not review

#2830 Dhrumil-Badge-Management-Page-Refresh-Fix
  src/components/Badge/AssignBadge.jsx
Labels: Moved to Final Review

#2762 Dhrumil - Added tests cases for UserManagement.
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/__tests__/UserManagement.test.js
Labels: Moved to Final Review, do not review

#2730 Aditya-Added-UnitTest-DeleteModal
  src/components/Timelog/__tests__/DeleteModal.test.js
Labels: Moved to Final Review

#2733 Aditya-Added-Tests-For-Badges
  src/components/UserProfile/__tests__/Badges.test.jsx
Labels: Moved to Final Review

#2734 Aditya-Added-Testing-for-Login
  src/components/Login/Login.test.jsx
  src/components/Login/__tests__/Login.test.jsx
Labels: Moved to Final Review

#2756 Vedant Fix inventory type list, add sort and search functionality
  src/components/BMDashboard/shared/CheckTypes.jsx
Labels: Moved to Final Review

#2845 Rishitha_Fix_team_code_requirement_new_users
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: Moved to Final Review

#2848 Sharadha Ready for Review Dropdown is Cropped
  src/components/TeamMemberTasks/reviewButton.css
Labels: Moved to Final Review

#2789 Swathi Fix resources dot centering on Tasks pages
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#2710 Huijie fix add lost hours editing deleting
  src/components/Reports/LostTime/AddLostTime.jsx
  src/components/UserProfile/TeamsAndProjects/AddTeamsAutoComplete.jsx
  src/components/UserProfile/TeamsAndProjects/__tests__/AddTeamsAutoComplete.test.jsx
Labels: High Priority - Please Review First
