Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-05, with the labels that each got.

#2043 Yi - Add permission control for wbs related pages
  src/routes.js
  src/utils/routePermissions.js
Labels: Moved to Final Review, High Priority - Please Review First

#2030 Yi - Dashboard: refine editable info modal tooltips text
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#2023 Peterson_Fix_Weekly_Summaries_edit_Last_week
  src/actions/weeklySummaries.js
  src/components/Timelog/WeeklySummaries.jsx
Labels: Moved to Final Review

#2092 Yaohong create Quick Setup Modal for new team members
  .eslintignore
  .eslintrc.js
  .github/pull_request_template.md
  .prettierignore
  package-lock.json
  src/actions/title.js
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignProjectField.jsx
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamField.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupCodes.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.css
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/store.js
  src/utils/URL.js
Labels: Moved to Final Review

#2141 Shiwani Role Permissions unit test
  src/components/PermissionsManagement/__tests__/RolePermissions.test.js
Labels: Moved to Final Review

#2048 Shiwani UserPermissionsPopup unit test
  src/components/PermissionsManagement/PermissionListItem.jsx
  src/components/PermissionsManagement/__tests__/UserPermissionsPopup.test.js
Labels: Moved to Final Review

#2213 Chris update equipment frontend
  src/components/BMDashboard/Equipment/Update/UpdateEquipment.css
  src/components/BMDashboard/Equipment/Update/UpdateEquipment.jsx
  src/routes.js
Labels: High Priority - Please Review First

#2239 Nahiyan_Update pull_request_template for dark mode
  .github/pull_request_template.md
Labels: do not review

#2232 Shengwei_migrate_TinyMCE
  .circleci/config.yml
  .eslintignore
  .gitignore
  README.md
  package-lock.json
  package.json
  postinstall.js
  public/index.html
  src/components/Admin/PopupText/PopupText.jsx
  src/components/Announcements/index.jsx
  src/components/Announcements/tinyMCE.js
  src/components/Projects/WBS/SingleTask/SingleTask.js
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/WeeklySummaries.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/Teamsview.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/common/TinyceEditor/tinymceEditor.jsx
Labels: High Priority - Please Review First

#1992 Shengwei create setup history modal
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/SetupProfile/SetupProfile.jsx
  src/components/SetupProfile/SetupProfileInvalidToken.jsx
  src/components/SetupProfile/SetupProfileUserEntry.jsx
  src/components/UserManagement/SetupHistoryPopup.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/setupNewUserPopup.jsx
  src/components/UserManagement/usermanagement.css
  src/utils/URL.js
Labels: High Priority - Please Review First

#2226 Abdel - Set schedule blue square scheduler limit to 4.
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/ScheduleExplanationModal/ScheduleExplanationModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
Labels: do not review

#1696 Shiwani TagsSearch unit test
  src/components/Projects/WBS/WBSDetail/components/__tests__/TagsSearch.test.js
Labels: Moved to Final Review

#2246 Gowtham fix weekly remaining summaries submission page formatting
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: High Priority - Please Review First

#2176 Shiqing fix reports view of team name further
  package-lock.json
  package.json
  src/components/Reports/TeamReport/TeamReport.jsx
Labels: High Priority - Please Review First

#2252 Create New User permission
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/__test__/UserSearchPanel.test.js
  src/components/UserManagement/__tests__/UserSearchPanel.test.js
Labels: High Priority - Please Review First

#2261 Nahiyan_Dark mode on Teams page modals
  src/components/Header/DarkMode.css
  src/components/Header/DarkModeButton.jsx
  src/components/Teams/CreateNewTeamPopup.jsx
  src/components/Teams/DeleteTeamPopup.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Teams/TeamStatusPopup.jsx
  src/components/Teams/__tests__/DeleteTeamPopup.test.js
  src/components/Teams/__tests__/TeamMembersPopup.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2268 chris fix show total project/people/team reports
  src/components/BMDashboard/_tests_/BMDashboard.test.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First

#2193 Ilya - Tools table
  src/actions/bmdashboard/toolActions.js
  src/components/BMDashboard/ItemList/SelectItem.jsx
  src/components/BMDashboard/ToolItemList/ToolItemListView.css
  src/components/BMDashboard/ToolItemList/ToolItemListView.jsx
  src/components/BMDashboard/ToolItemList/ToolItemsTable.jsx
  src/components/BMDashboard/ToolItemList/ToolRecordsModal.css
  src/components/BMDashboard/ToolItemList/ToolRecordsModal.jsx
  src/components/BMDashboard/Tools/ToolsList.jsx
  src/components/BMDashboard/UpdateTools/UpdateTool.css
  src/components/BMDashboard/UpdateTools/UpdateToolModal.jsx
  src/constants/bmdashboard/toolsConstants.js
  src/reducers/bmdashboard/toolReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2275 Chris_teamMemberTasks_actions_unittest
  src/components/TeamMemberTasks/__tests__/actions.test.js
Labels: High Priority - Please Review First

#2273 Chris_teamMemberTask_taskButton_unittest
  src/components/TeamMemberTasks/__tests__/TaskButton.test.js
Labels: High Priority - Please Review First

#2205 Imran manage admin links in user profile
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
  src/components/UserProfile/UserProfileModal/EditLinkModal.test.js
Labels: High Priority - Please Review First

#1937 Aishwaryak - Equipment_List_View_Frontend
  src/actions/bmdashboard/equipmentActions.js
  src/actions/bmdashboard/invTypeActions.js
  src/components/BMDashboard/EquipmentsList/Equipments.css
  src/components/BMDashboard/EquipmentsList/EquipmentsInputs.jsx
  src/components/BMDashboard/EquipmentsList/EquipmentsTable.jsx
  src/components/BMDashboard/EquipmentsList/EquipmentsView.jsx
  src/components/BMDashboard/EquipmentsList/EquipmentsViewModal.jsx
  src/constants/bmdashboard/equipmentsConstants.js
  src/reducers/bmdashboard/equipmentsReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: Moved to Final Review

#2256 Nahiyan_Dark Mode Modals on Projects/WBS page
  src/components/Projects/Members/Member/Member.jsx
  src/components/Projects/ProjectInfoModal.jsx
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/ControllerRow/ControllerRow.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/ImportTask/ImportTask.jsx
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/WBSItem/__tests__/WBSItem.test.js
  src/components/Projects/WBS/wbs.jsx
  src/components/common/Modal/Modal.jsx
Labels: High Priority - Please Review First

#2259 Ramakrishna create different view for summary
  src/components/SummaryBar/SummaryBar.jsx
Labels: Moved to Final Review

#1941 Shuhua - Create different view for ! summary
  src/components/SummaryBar/SummaryBar.jsx
Labels: Needs New Developer

#2294 Nahiyan_Added dark mode for popup in team locations
  src/components/TeamLocations/MarkerPopup.jsx
  src/components/TeamLocations/TeamLocations.css
  src/components/TeamLocations/TeamLocations.jsx
Labels: do not review

#2282 Meet BadgeReport unit tests
  src/components/Badge/__tests__/BadgeReport.test.js
Labels: Moved to Final Review
