Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-07, with the labels that each got.

#2163 Hoang add copy functionality and fix project report table
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.css
  src/components/Reports/WbsTable/WbsTable.css
  src/components/Reports/WbsTable/WbsTable.jsx
  src/components/Reports/__tests__/WbsTable.test.js
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/common/Paging/Paging.css
Labels: High Priority - Please Review First

#2319 Jiayu fix bug manual add lost volunteer time
  src/actions/timeEntries.js
  src/components/Reports/LostTime/AddLostTime.jsx
  src/components/Reports/LostTime/EditHistoryModal.jsx
Labels: High Priority - Please Review First

#2409 Carlos new pie chart hour visualization by team member project reports
  package-lock.json
  package.json
  src/actions/index.js
  src/components/BMDashboard/ItemList/ItemsTable.jsx
  src/components/BMDashboard/LogTools/LogTools.jsx
  src/components/BMDashboard/ToolItemList/ToolItemsTable.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.css
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.jsx
  src/components/Reports/ProjectReport/ProjectPieChart/ProjectPieChart.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectReport/TriMembersStateToggleSwitch/TriMembersStateToggleSwitch.css
  src/components/Reports/ProjectReport/TriMembersStateToggleSwitch/TriMembersStateToggleSwitch.jsx
  src/components/Reports/ProjectReport/WbsPiechart/WbsPieChart.jsx
  src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
  src/components/Timer/Countdown.jsx
  src/components/Timer/Timer.jsx
  src/components/WeeklySummary/WeeklySummaryModal.jsx
Labels: High Priority - Please Review First

#2423 harshb added wrapper accordian with css
  package-lock.json
  package.json
  src/components/TotalOrgSummary/AccordianWrapper/AccordianWrapper.css
  src/components/TotalOrgSummary/AccordianWrapper/AccordianWrapper.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/WeeklyVolunteerSummary.css
Labels: do not review

#2424 Shengwei hotfix (TimeEnty): Jae's account info deletion
  src/components/Timelog/TimeEntry.jsx
Labels: High Priority - Please Review First

#2425 Nahiyan_Dark mode on single task page
  src/components/Projects/WBS/SingleTask/SingleTask.js
Labels: High Priority - Please Review First

#2402 Jiayu Add WBS icon in userprofile page projects
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2392 Nathalia new filter project by user name
  src/actions/userProfile.js
  src/components/Projects/Projects.jsx
  src/components/SearchProjectByPerson/SearchProjectByPerson.jsx
  src/constants/userProfile.js
  src/reducers/index.js
  src/reducers/userProjectsByUserNameReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2348 Nathalia remove note from editable modals
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
Labels: medium priority

#2344 Chris_ignore_spaces_inputs_user_management_search
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
Labels: High Priority - Please Review First

#2401 Ramakrishna Teamcode Regex change and select All with No Team code option fix
  src/components/Reports/TeamTable.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First

#2359 Shereen- Equipment List View Component
  src/actions/bmdashboard/equipmentActions.js
  src/components/BMDashboard/Equipment/List/EquipmentList.jsx
  src/components/BMDashboard/Equipment/List/EquipmentListModal.jsx
  src/components/BMDashboard/Equipment/List/Equipments.css
  src/components/BMDashboard/Equipment/List/EquipmentsInputs.jsx
  src/components/BMDashboard/Equipment/List/EquipmentsTable.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First

#2306 Shereen Add Tool - Created API call
  src/actions/bmdashboard/invTypeActions.js
  src/components/BMDashboard/Tools/AddToolForm.css
  src/components/BMDashboard/Tools/AddToolForm.jsx
  src/constants/bmdashboard/inventoryTypeConstants.js
  src/reducers/bmdashboard/inventoryTypeReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2389 Shereen_Bulk Reusables Update component
  src/actions/bmdashboard/reusableActions.js
  src/components/BMDashboard/UpdateReusables/UpdateReusable.jsx
  src/components/BMDashboard/UpdateReusables/UpdateReusablesBulk/UpdateReusablesBulk.css
  src/components/BMDashboard/UpdateReusables/UpdateReusablesBulk/UpdateReusablesBulk.jsx
  src/components/BMDashboard/UpdateReusables/UpdateReusablesBulk/UpdateReusablesBulkInputs.jsx
  src/components/BMDashboard/UpdateReusables/UpdateReusablesBulk/UpdateReusablesBulkTable.jsx
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/constants/bmdashboard/reusableConstants.js
  src/reducers/bmdashboard/reusablesReducer.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#1595 Shiwani Unit Test for CurrentPromptModal
  src/__tests__/CurrentPromptModal.test.js
Labels: Moved to Final Review

#2119 Report Page and report components testfiles added
  src/components/Reports/sharedComponents/ReportPage/__test__/ReportPage.test.js
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/__test__/ReportBlock.test.js
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard.test.js
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard_2.test.js
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/__test__/ReportHeader.test.js
Labels: Moved to Final Review

#2412 Jiayu add teams limit see all
  src/actions/allTeamsAction.js
  src/components/Teams/InfoModal.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/ToggleSwitch/ToggleSwitch.jsx
  src/components/Teams/ToggleSwitch/ToggleSwitch.module.scss
  src/components/Teams/__tests__/TeamMembersPopup.test.js
  src/constants/allTeamsConstants.js
  src/reducers/allTeamsReducer.js
  src/reducers/teamsTeamMembersReducer.js
Labels: High Priority - Please Review First

#2013 Nahiyan_Added a "Edit Tasks" button to reduce the number of requests
  src/__tests__/TaskTable/Selectors.test.js
  src/__tests__/TaskTable/TasksTable.test.js
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.jsx
  src/components/Reports/ProjectReport/ProjectReport.css
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/TasksDetail/TasksDetail.css
  src/components/Reports/TasksDetail/TasksDetail.jsx
  src/components/Reports/TasksTable/TasksTable.css
  src/components/Reports/TasksTable/TasksTable.jsx
  src/components/Reports/TasksTable/selectors.js
Labels: High Priority - Please Review First

#2315 Nathalia fix discrepancies in the total hours for the project on the project report page
  src/components/Reports/ProjectReport/ProjectReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2448 Shiwani Projects.jsx unit test
  src/components/Projects/__tests__/Projects.test.jsx
Labels: Moved to Final Review

#2397 akshit_improve_loading_resources_list
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.css
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
  src/components/Projects/WBS/WBSDetail/components/__tests__/TagsSearch.test.js
Labels: Moved to Final Review

#2299 Kaushik Integrate GEMINI AI
  src/components/Header/Header.css
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WriteForMeModal.jsx
  src/utils/URL.js
  src/utils/permissions.js
Labels: High Priority - Please Review First

#2366 kaushik_fix_usermanagement_delete_finalday_button
  src/components/UserManagement/UserTableData.jsx
Labels: Moved to Final Review

#2422 Hiral Fix edit button on narrow screens
  package-lock.json
  src/components/Projects/WBS/WBSDetail/ControllerRow/ControllerRow.jsx
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
Labels: High Priority - Please Review First

#1610 Cheng-Yun Project.jsx Unit Test
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Project/Project.test.jsx
Labels: do not review

#2455 hotfix: fix issue on load application
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WriteForMeModal.jsx
Labels: High Priority - Please Review First, hotfix

#2347 Hoang make mark task as done and remove task from user more efficient
  src/components/TeamMemberTasks/ReviewButton.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2078 Peterson impl feature finish my team filter or tasks tab
  src/components/Badge/__tests__/NewBadges.test.js
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
Labels: Moved to Final Review

#2460 Diya Teams Page Load - Hotfix
  src/components/Teams/Teams.jsx
Labels: hotfix

#2406 Added test file for LoginPrivileges
  src/components/Reports/TeamReport/components/__tests__/LoginPrivileges.test.jsx
Labels: Moved to Final Review

#2461 Peter - Hotfix (timelog): blank page due to bad request
  src/components/Timelog/Timelog.jsx
Labels: hotfix

#2257 Hoang fix viewing other dashboard
  src/components/Header/Header.jsx
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timer/Timer.jsx
  src/utils/permissions.js
Labels: Moved to Final Review

#2191 Peterson impl make profile team code field show existing codes
  src/components/UserProfile/AddNewUserProfile/__test__/UserProfileAdd.test.js
  src/components/UserProfile/TeamsAndProjects/AutoCompleteTeamCode.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/TeamsAndProjects/autoComplete.css
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2477 Nahiyan_Hotfix for spacing issue on Timelog page
  src/components/Badge/Badge.css
  src/components/Badge/BadgeReport.css
  src/components/Badge/BadgeReport.jsx
  src/components/LeaderBoard/Leaderboard.css
  src/components/TeamMemberTasks/style.css
  src/components/Timelog/Timelog.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
Labels: do not review

#2169 Kaushik-Cheng-Yun_WBS.jsx_Unit_test
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/wbs.test.jsx
Labels: High Priority - Please Review First

#2123 Sarthak project and team overview UI fixed
  src/__tests__/mockStates.test.js
  src/components/Projects/Overview/Overview.css
  src/components/Projects/Overview/Overview.jsx
  src/components/Projects/Overview/__tests__/Overview.test.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/WBS/wbs.css
  src/components/Projects/projects.css
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
  src/components/Teams/TeamsOverview.css
  src/components/Teams/TeamsOverview.jsx
  src/components/Teams/__tests__/TeamsOverview.test.js
  src/languages/en/ui.js
Labels: High Priority - Please Review First, medium priority

#2470 Nahiayn_New Dark Mode Button
  src/components/Header/DarkMode.css
  src/components/Header/DarkModeButton.jsx
  src/components/Header/Header.jsx
  src/components/Header/images/nightIcon.png
  src/components/Header/images/sunIcon.png
Labels: High Priority - Please Review First

#2450 Bhuvan - tableFilter.jsx test cases
  src/components/Reports/TableFilter/__test__/tableFilter.test.js
Labels: Moved to Final Review

#2386 Youyou_fix_new_roles_not_show_in_permission_page
  src/actions/role.js
  src/components/PermissionsManagement/NewRolePopUp.jsx
  src/components/PermissionsManagement/PermissionsManagement.jsx
Labels: High Priority - Please Review First

#2408 weiyao_permissionManagement_addRoles
  src/components/PermissionsManagement/PermissionListItem.jsx
  src/components/UserProfile/EditableModal/RoleInfoModal.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2443 Jiayu Sort projects by most recent edited inventories and members
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2487 Peterson fix the bug that causes the time log page to reload indefinitely
  src/components/Header/Header.jsx
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First, high priority

#2413 Hoang prevent overriding task edit suggestion's approval/rejection
  src/actions/task.js
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionsModal.jsx
  src/components/TaskEditSuggestions/TaskEditSuggestions.css
  src/components/TaskEditSuggestions/TaskEditSuggestions.jsx
  src/components/TaskEditSuggestions/__tests__/service.test.js
  src/components/TaskEditSuggestions/service.js
  src/components/TaskEditSuggestions/thunks.js
Labels: High Priority - Please Review First

#2339 Shengwei fix user profile quick setup
  src/actions/allTeamsAction.js
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamCodeField.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamField.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
  src/constants/allTeamsConstants.js
  src/reducers/allTeamsReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First
