Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-12, with the labels that each got.

#2881 Nikhil - fixed new user popup issue
  src/components/UserManagement/setupNewUserPopup.jsx
Labels: High Priority - Please Review First

#2855 Carlos improvement team hours visualization
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.jsx
  src/components/Reports/ProjectReport/ProjectPieChart/ProjectPieChart.css
  src/components/Reports/ProjectReport/ProjectPieChart/ProjectPieChart.jsx
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/common/TwoWayToggleSwitch/TwoWayToggleSwitch.css
  src/components/common/TwoWayToggleSwitch/TwoWayToggleSwitch.jsx
Labels: High Priority - Please Review First

#2821 Vedant Fix project dashboard and add multi-select option
  src/components/BMDashboard/BMDashboard.css
  src/components/BMDashboard/BMDashboard.jsx
  src/components/BMDashboard/Projects/ProjectSelectForm.jsx
  src/components/BMDashboard/Projects/ProjectSummary.css
  src/components/BMDashboard/Projects/ProjectSummary.jsx
  src/components/BMDashboard/Projects/ProjectsList.jsx
  src/components/BMDashboard/_tests_/BMDashboard.test.jsx
Labels: High Priority - Please Review First

#2687 Vedant Add reset filter option to badge data filtering
  src/components/Badge/BadgeDevelopment.jsx
Labels: High Priority - Please Review First

#2887 Vedant Fix project delete modal in dark mode
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/__tests__/Modal.test.jsx
Labels: High Priority - Please Review First

#2754 Jingyi_fix_timeoff_indicator_add_tooltip
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#2254 Jingyi-Interact with Task "Ready for Review" button
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: High Priority - Please Review First

#2772 Carlos anniversary celebrated
  package-lock.json
  package.json
  src/actions/sendEmails.js
  src/actions/totalOrgSummary.js
  src/components/Announcements/index.jsx
  src/components/TotalOrgSummary/AnniversaryCelebrated/AnniversaryCelebrated.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/common/EmailSender/EmailSender.jsx
  src/routes.js
Labels: High Priority - Please Review First

#2912 huijie - category search application page
  src/components/Collaboration/Collaboration.jsx
Labels: High Priority - Please Review First

#2872 Supriya-Add-User-Role-below-their-name-in-Tasks-Tab
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: High Priority - Please Review First

#2673 Sriram - fix projects archive functionality and Set Inactive button crashing UI
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Project/Project.test.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/__tests__/Projects.test.jsx
  src/components/common/Modal/Modal.jsx
  src/reducers/allProjectsReducer.js
Labels: High Priority - Please Review First

#2902 Yashwanth fix: labels
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: High Priority - Please Review First

#2890 Jingyi_Add intangible time reminder/confirmation modal
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/TimeEntryForm/TimeLogConfirmationModal.jsx
Labels: High Priority - Please Review First, high priority

#2736 Satya fix teams UI
  src/components/Teams/Team.css
  src/components/Teams/TeamTableHeader.jsx
  src/components/Teams/TeamsOverview.css
  src/components/Teams/TeamsOverview.jsx
Labels: High Priority - Please Review First

#2925 Vedant fix checkbox and label alignment pie chart
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.css
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.jsx
  src/components/Reports/ProjectReport/WbsPiechart/WbsPieChart.jsx
Labels: High Priority - Please Review First

#2473 Vijayanand UI fix on report when searching projects/people/teams table on narrow screen
  src/components/Reports/Reports.jsx
Labels: High Priority - Please Review First

#2831 Rahul Fix Teams Modal UI
  src/components/Projects/WBS/WBSDetail/wbs.css
  src/components/Teams/TeamMembersPopup.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2866 Ashish_Fix_Rehireable_Status
  src/actions/userManagement.js
  src/components/UserProfile/UserProfile.jsx
Labels: medium priority

#2931 Supriya -Add-Projects-dropdown-in-bmdashboard-with-404-NotFound-page
  src/assets/images/404Image1.png
  src/assets/images/404ImageDarkMode1.png
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/NotFound/NotFoundPage.css
  src/components/NotFound/NotFoundPage.jsx
  src/routes.js
Labels: High Priority - Please Review First

#2774 Sai Venkatesh - frontend - Improve speed and function of deleting multiple blue squares
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
Labels: High Priority - Please Review First

#2882 Ashish_add_status_column_header
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First

#2965 Pallavi Improved search functionality in UserManagement.jsx
  src/components/UserManagement/UserManagement.jsx
Labels: medium priority

#2906 Saipreetham_fix/add-new-QST-media-folder-validation of link.
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
Labels: High Priority - Please Review First

#2868 Yashwanth individual permission change show
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
  src/components/PermissionsManagement/PermissionsManagement.jsx
Labels: High Priority - Please Review First

#2976 Yashwanth : Fix badge deletion
  src/components/Badge/BadgeReport.jsx
Labels: High Priority - Please Review First

#2939 Dhrumil - Fix Test File Throws an error and added test Cases
  src/components/Teams/Teams.jsx
  src/components/Teams/__tests__/Teams.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2788 Dhrumil - Added tests cases for Teams.
  src/components/Teams/__tests__/Teams.test.js
Labels: do not review

#2949 Vijay Anand - Unit test total org summary reducer
  src/reducers/__tests__/totalOrgSummaryReducer.test.js
Labels: Moved to Final Review

#2841 Jatin toggle invisibility permission self and others
  src/actions/userManagement.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/TeamsAndProjects/Switch.css
  src/components/UserProfile/TeamsAndProjects/Switch.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First
