Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-01, with the labels that each got.

#1764 Shrey unit test History Modal
  src/__tests__/UserProfile/VolunteeringTimeTab/HistoryModal.test.js
Labels: High Priority - Please Review First

#1737 Shrey unit tests TangibleInfoModal
  src/__tests__/Timelog/TangibleInfoModal.test.js
Labels: High Priority - Please Review First

#1744 Xiaow TimeEntryForm refactor
  src/__tests__/Timelog/TimeEntry.test.js
  src/__tests__/Timelog/TimeEntryForm.test.js
  src/__tests__/Timelog/TimeEntryForm_edit.test.js
  src/__tests__/mockStates.js
  src/actions/index.js
  src/actions/team.js
  src/actions/userProfile.js
  src/actions/userProjects.js
  src/actions/weeklySummaries.js
  src/assets/images/logo.png
  src/components/Dashboard/Dashboard.jsx
  src/components/Header/Header.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/PopUpBar/PopUpBar.jsx
  src/components/PopUpBar/__tests__/PopUpBar.test.jsx
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/TeamMemberTasks/FilteredTimeEntries.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/Timelog/TimeEntry.jsx
  src/components/Timelog/TimeEntryForm/ReminderModal.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/TimeEntryForm/selectors.js
  src/components/Timelog/Timelog.jsx
  src/components/Timer/Timer.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/constants/userProfile.js
  src/constants/userProjects.js
  src/reducers/timeEntriesForSpecifiedProjectReducer.js
  src/reducers/userProfileByIdReducer.js
  src/reducers/userProjectsReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#1766 Xiao F hotfix personal max badge label position
  src/components/UserProfile/Badge.css
  src/components/UserProfile/BadgeImage.jsx
Labels: do not review

#1664 Nathan highlight bio permission
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First

#1759 Shrey unit test WorkHistory
  src/components/UserProfile/__tests__/WorkHistory.test.js
Labels: High Priority - Please Review First

#1780 Revert "Olga tool details page"
  src/actions/bmdashboard/toolActions.js
  src/components/BMDashboard/Tools/ToolDetailPage.css
  src/components/BMDashboard/Tools/ToolDetailPage.jsx
  src/components/BMDashboard/Tools/ToolModal.jsx
  src/constants/bmdashboard/toolsConstants.js
  src/reducers/bmdashboard/toolByIdReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#1510 Xiao F Create way for owner to edit & update ChatGPT prompt text
  src/actions/weeklySummariesAIPrompt.js
  src/components/Dashboard/Dashboard.jsx
  src/components/WeeklySummary/CurrentPromptModal.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/components/WeeklySummary/WeeklySummary.test.jsx
  src/constants/weeklySummariesAIPrompt.js
  src/reducers/dashboardDataReducer.js
  src/reducers/index.js
  src/reducers/weeklySummariesAIPromptReducer.js
  src/utils/URL.js
Labels: Moved to Final Review, High Priority - Please Review First

#1781 Shrey hotfix path change for unit tests and Stub test cases
  src/components/Timelog/__tests__/AboutModal.test.js
  src/components/Timelog/__tests__/EffortBar.test.js
  src/components/Timelog/__tests__/TimeEntryForm/ReminderModal.test.js
  src/components/Timelog/__tests__/TimeEntryForm/TangibleInfoModal.test.js
  src/components/UserManagement/__tests__/ActiveCell.test.js
  src/components/UserManagement/__tests__/DropDownSearchBox.test.js
  src/components/UserManagement/__tests__/UserTableHeader.test.js
  src/components/UserProfile/VolunteeringTimeTab/__tests__/HistoryModal.test.js
  src/components/common/Stub/__tests__/Stub.test.js
Labels: do not review

#1722 Shiwani Create a Leaderboard way to see when people are off for the week
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: High Priority - Please Review First

#1796 Roberto-hotfix for viewing others dashboard
  src/components/Dashboard/Dashboard.jsx
  src/components/TeamMemberTasks/ReviewButton.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: do not review

#1789 Tim: Fix BM Dashboard Server Errors
  src/components/BMDashboard/Consumables/ConsumablesList/ConsumablesInputs.jsx
  src/components/BMDashboard/MaterialsList/RecordsModal.jsx
Labels: High Priority - Please Review First

#1702 Xiao F Make map add new user fields edit more easily
  src/components/TeamLocations/AddOrEditPopup.jsx
  src/components/TeamLocations/CustomInput.jsx
Labels: High Priority - Please Review First

#1751 keyun-fix-hover-box position
  src/components/UserProfile/BlueSquares/BlueSquare.css
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
Labels: Moved to Final Review

#1598 Remake Kaikanes Badge Key error
  src/components/Reports/BadgeSummaryViz.jsx
Labels: Moved to Final Review

#1660 yixiao_taskeditsuggestion_unittest
  src/components/TaskEditSuggestions/__tests__/TaskEditSuggestions.test.js
Labels: Moved to Final Review

#1823 Abdel blue square date confirmation modal
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
Labels: do not review

#1458 Xiao F create the ability for owners to approve and apply suggested changes on task
  src/components/Header/Header.jsx
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionsModal.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#1185 Zuhang fix team management alert if user already exists
  src/components/Teams/MembersAutoComplete.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/WeeklySummariesReport/google_doc_icon_gray.png
Labels: Moved to Final Review

#1792 Shihao fix refresh issue
  __mocks__
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review, High Priority - Please Review First

#1277 Jerry - Track Who Changes Permissions On Permissions Management Page
  src/components/PermissionsManagement/PermissionChangeLogTable.css
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
  src/components/PermissionsManagement/PermissionsManagement.css
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/RolePermissions.jsx
  src/utils/URL.js
  src/utils/formatDate.js
Labels: Moved to Final Review

#1668 Changhao - Unit tests for userSearchPanel
  src/components/UserManagement/__tests__/UserSearchPanel.test.js
Labels: Moved to Final Review

#1816 Kaikanes infringe bugfix
  src/components/Reports/InfringementsViz.jsx
  src/components/Reports/PeopleReport/PeopleReport.css
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleTableDetails.css
  src/components/Reports/TableFilter/TableFilter.css
  src/components/Reports/TimeEntriesViz.jsx
Labels: High Priority - Please Review First

#1604 Anirudh add edit button to each summary
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/Timelog/Timelog.css
  src/components/Timelog/WeeklySummaries.jsx
  src/components/WeeklySummary/WeeklySummary.css
Labels: Moved to Final Review

#1387 Jiyuan - Fixed Assign Badges permission function
  src/components/UserProfile/Badges.jsx
Labels: Moved to Final Review

#1575 Xiao F add floating and dismissable team notification header bar
  src/App.css
  src/components/Header/Header.css
  src/components/Header/Header.jsx
Labels: High Priority - Please Review First

#1745 Yubo - Read-only HOC make non-editable task view obvious
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/ReadOnlySectionWrapper.jsx
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
Labels: Moved to Final Review

#1854 Olena Lesson Card Functionality
  src/actions/bmdashboard/lessonLikesActions.js
  src/actions/bmdashboard/lessonsAction.js
  src/actions/bmdashboard/projectByIdAction.js
  src/components/BMDashboard/LessonList/DeleteLessonCardPopUp.jsx
  src/components/BMDashboard/LessonList/LessonCard.css
  src/components/BMDashboard/LessonList/LessonCard.jsx
  src/components/BMDashboard/LessonList/LessonListForm.css
  src/components/BMDashboard/LessonList/LessonListForm.jsx
  src/components/BMDashboard/LessonList/Lessons.jsx
  src/constants/bmdashboard/lessonConstants.js
  src/constants/bmdashboard/projectConstants.js
  src/reducers/bmdashboard/lessonsReducer.js
  src/reducers/bmdashboard/projectByIdReducer.js
  src/reducers/index.js
  src/reducers/projectByIdReducer.js
  src/routes.js
  src/utils/URL.js
  src/utils/formatDate.js
Labels: Moved to Final Review

#1877 Roberto-refactored basic information tab and updates timezone array
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.css
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/TimeZoneDropDown/__test__/TimeZoneDropDown.test.js
  src/components/UserProfile/UserProfile.jsx
  src/constants/timeZones.js
Labels: High Priority - Please Review First

#1890 Bailey create link validation for review button
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: do not review

#1471 Abdel log requested time off for blue squares
  .eslintignore
  package-lock.json
  package.json
  src/actions/timeOffRequestAction.js
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/TimeOffRequestDetailModal.jsx
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/style.css
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
  src/components/UserManagement/logTimeOffPopUp.jsx
  src/components/UserManagement/usermanagement.css
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/common/SkeletonLoading/SkeletonLoading.jsx
  src/constants/timeOffRequestConstants.js
  src/languages/en/ui.js
  src/reducers/index.js
  src/reducers/timeOffRequestReducer.js
  src/utils/URL.js
  src/utils/formatDateFromDescriptionString.js
Labels: do not review, Moved to Final Review
