Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-02, with the labels that each got.

#1870 Leo_Add_Timelog_Icon_to_Tasktab
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: Moved to Final Review

#1742 Haohui - fix permission for edit tasks
  src/components/Header/Header.jsx
  src/components/common/ProtectedRoute/ProtectedRoute.jsx
  src/routes.js
  src/utils/routePermissions.js
Labels: Moved to Final Review

#1906 Fix validation for weeklyCommitedHours field and User Profile Page goes blank when resizing under 1025px
  src/components/UserManagement/setupNewUserPopup.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
Labels: do not review

#1881 yixiao_taskreducer_unit
  src/components/TaskEditSuggestions/__tests__/reducer.test.js
Labels: Moved to Final Review

#1851 Chengyan unit test for badge.jsx
  src/__tests__/mockStates.js
  src/__tests__/utils.js
  src/components/Badge/Badge.jsx
  src/components/Badge/__tests__/Badge.test.js
Labels: do not review

#1572 Roberto- fixes intangible time entries round to 2nd decimal place
  src/__tests__/mockStates.js
  src/components/Timelog/DeleteModal.jsx
  src/components/Timelog/EffortBar.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/__tests__/DeleteModal.test.js
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: Moved to Final Review

#1899 Sucheta show new icon on ai prompt update
  src/actions/weeklySummariesAIPrompt.js
  src/assets/images/New-HGN-Icon-11kb-200x160px.png
  src/components/Dashboard/Dashboard.jsx
  src/components/WeeklySummary/CurrentPromptModal.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
  src/constants/weeklySummariesAIPrompt.js
  src/utils/URL.js
Labels: Moved to Final Review, High Priority - Please Review First

#1927 Nahiyan-Improve profile page teams tab UX
  src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
  src/components/UserProfile/TeamsAndProjects/AddTeamsAutoComplete.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#1752 Aishwarya - Purchase tool request form-frontend
  src/actions/bmdashboard/invTypeActions.js
  src/actions/bmdashboard/toolActions.js
  src/components/BMDashboard/ToolPurchaseRequest/PurchaseForm.css
  src/components/BMDashboard/ToolPurchaseRequest/PurchaseForm.jsx
  src/components/BMDashboard/ToolPurchaseRequest/PurchaseTool.css
  src/components/BMDashboard/ToolPurchaseRequest/PurchaseTool.jsx
  src/components/BMDashboard/ToolPurchaseRequest/index.js
  src/constants/bmdashboard/inventoryTypeConstants.js
  src/constants/bmdashboard/toolsConstants.js
  src/reducers/bmdashboard/inventoryTypeReducer.js
  src/reducers/bmdashboard/toolReducer.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#1849 Ilya fix blue square hover box on phones
  src/components/UserProfile/BlueSquares/BlueSquare.css
Labels: Moved to Final Review

#1681 Shengwei fix jae's account edit permission
  src/components/Badge/BadgeManagement.jsx
  src/components/Badge/BadgeReport.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/__test__/UserTableData.test.js
  src/components/UserProfile/AssignBadgePopup.jsx
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/TimeEntryEditHistory.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#1920 Yixiao taskeditthunks unit
  src/components/TaskEditSuggestions/__tests__/thunks.test.js
Labels: Moved to Final Review

#1942 Fix Add blue square scheduler list scheduled time off
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/logTimeOffPopUp.jsx
Labels: do not review

#1901 Changhao - added unit tests for GeneratePdfReport.jsx
  src/__tests__/GeneratePdfReport.test.js
  src/components/WeeklySummariesReport/__tests__/GeneratePdfReport.test.js
  src/components/WeeklySummariesReport/__tests__/__snapshots__/GeneratePdfReport.test.js.snap
Labels: Moved to Final Review

#1873 Luis add warnings component to dashboard
  .gitattributes
  src/actions/information.js
  src/actions/warnings.js
  src/assets/images/logo.png
  src/components/Badge/BadgeReport.css
  src/components/Dashboard/Dashboard.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/Warnings/WarningIcon.jsx
  src/components/Warnings/WarningIcons.jsx
  src/components/Warnings/WarningItem.jsx
  src/components/Warnings/Warnings.css
  src/components/Warnings/Warnings.jsx
  src/components/Warnings/WarningsModal.jsx
  src/components/WeeklySummariesReport/google_doc_icon_gray.png
  src/constants/warning.js
  src/reducers/index.js
  src/reducers/warningsReducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#1929 add filters to weekly summaries reports
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review

#1934 Jacob - Optimize member search
  src/actions/projectMembers.js
  src/components/Projects/Members/Members.jsx
  src/utils/URL.js
Labels: Moved to Final Review

#1924 olena copy of reverted pr1854 with fixed issues
  src/actions/bmdashboard/lessonLikesActions.js
  src/actions/bmdashboard/lessonsAction.js
  src/actions/bmdashboard/projectByIdAction.js
  src/components/BMDashboard/LessonList/DeleteLessonCardPopUp.jsx
  src/components/BMDashboard/LessonList/LessonCard.css
  src/components/BMDashboard/LessonList/LessonCard.jsx
  src/components/BMDashboard/LessonList/LessonListForm.css
  src/components/BMDashboard/LessonList/LessonListForm.jsx
  src/components/BMDashboard/LessonList/Lessons.jsx
  src/constants/bmdashboard/lessonConstants.js
  src/constants/bmdashboard/projectConstants.js
  src/reducers/bmdashboard/lessonsReducer.js
  src/reducers/bmdashboard/projectByIdReducer.js
  src/reducers/index.js
  src/reducers/projectByIdReducer.js
  src/routes.js
  src/utils/URL.js
  src/utils/formatDate.js
Labels: Moved to Final Review

#1883 yixiao_taskeditservice_unit
  package-lock.json
  package.json
  src/components/TaskEditSuggestions/__tests__/service.test.js
  src/components/TaskEditSuggestions/service.js
Labels: Moved to Final Review

#1867 Ilya remove task modal from reports
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
  src/components/Reports/PeopleReport/selectors.js
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/common/PieChart/PieChart.css
  src/components/common/PieChart/PieChart.jsx
Labels: Moved to Final Review

#1830 Shengwei Enhancement: badge assignment and modification will not remove earned date
  src/components/Badge/BadgeReport.jsx
  src/components/Reports/BadgeSummaryViz.jsx
Labels: Moved to Final Review

#1950 Nathan fix route permissions
  src/components/BMDashboard/BMHeader/BMHeader.jsx
  src/components/Header/Header.jsx
  src/components/Projects/Members/Member/Member.jsx
  src/components/Projects/Members/Members.jsx
  src/components/Projects/Project/Project.jsx
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/WBS/AddWBS/AddWBS.jsx
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/routes.js
  src/utils/routePermissions.js
Labels: High Priority - Please Review First

#1939 Ramya unit test : Reports/TeamReport/ReportCharts
  src/components/Reports/TeamReport/components/ReportCharts.jsx
  src/components/Reports/TeamReport/components/__tests__/ReportCharts.test.jsx
Labels: Moved to Final Review

#1951 Shereen - Unit tests for pause and resume button component.
  src/components/UserManagement/PauseAndResumeButton.jsx
  src/components/UserManagement/__tests__/PauseAndResumeButton.test.js
Labels: Moved to Final Review

#1936 Ramya Unit Test :UsersProfile/ TeamsAndProject/AddProjectPopup
  src/components/UserProfile/TeamsAndProjects/__tests__/AddProjectPopup.test.js
Labels: Moved to Final Review

#1640 Roberto- changes open cage api call to backend
  src/actions/timezoneAPIActions.js
  src/components/Dashboard/Dashboard.jsx
  src/components/SetupProfile/SetupProfileUserEntry.jsx
  src/components/SetupProfile/homeCountryModal.jsx
  src/components/TeamLocations/AddOrEditPopup.jsx
  src/components/TeamLocations/TeamLocations.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/constants/timezoneApiConstants.js
  src/reducers/index.js
  src/reducers/timezoneApiReducer.js
  src/services/timezoneApiService.js
  src/utils/URL.js
Labels: Moved to Final Review

#1989 Shivansh Added Security rechecks for Delete Team and User
  src/components/Teams/DeleteTeamPopup.jsx
  src/components/Teams/__tests__/DeleteTeamPopup.test.js
  src/components/UserManagement/DeleteUserPopup.jsx
  src/components/UserManagement/__test__/DeleteUserPopup.test.js
Labels: Moved to Final Review

#1459 Shiwani Make permission for "total valid weekly summaries" number editable
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: Moved to Final Review

#1810 Jacob fix badge development checkbox
  src/actions/badgeManagement.js
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/UserManagement/__test__/ActiveInactiveConfirmationPopup.test.js
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: Moved to Final Review
