Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-06, with the labels that each got.

#2264 Abdel add i icon to blue square
  public/index.html
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.css
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.jsx
Labels: do not review

#2308 Sucheta - (New) Improve add task modal format
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#2296 Ilya log tool frontend
  src/actions/bmdashboard/invTypeActions.js
  src/actions/bmdashboard/toolActions.js
  src/components/BMDashboard/ItemList/ItemListView.css
  src/components/BMDashboard/LogTools/LogTools.css
  src/components/BMDashboard/LogTools/LogTools.jsx
  src/components/Header/Header.jsx
  src/constants/bmdashboard/toolsConstants.js
  src/reducers/bmdashboard/inventoryTypeReducer.js
  src/reducers/bmdashboard/toolReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2270 Yao - New Add less-than-minimum hours logged colors on Weekly Summaries Reports page
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: Moved to Final Review

#2295 Nahiyan_Dark mode on User Profile Modals
  src/components/Badge/BadgeReport.jsx
  src/components/UserProfile/AddNewTeamModal.jsx
  src/components/UserProfile/AssignBadgePopup.jsx
  src/components/UserProfile/Badges.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
  src/components/UserProfile/TimeEntryEditHistory.jsx
  src/components/UserProfile/UserLinks/UserLinks.jsx
  src/components/UserProfile/UserLinks/__tests__/UserLinks.test.js
  src/components/UserProfile/UserLinks/__tests__/UserLinks.test.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/components/UserProfile/UserProfileEdit/__test__/SaveButton.test.js
  src/components/UserProfile/UserProfileModal/EditConfirmModal.jsx
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
  src/components/UserProfile/UserProfileModal/EditLinkModal.test.js
  src/components/UserProfile/UserProfileModal/UserProfileModal.jsx
  src/components/UserProfile/VolunteeringTimeTab/HistoryModal.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/components/UserProfile/VolunteeringTimeTab/__tests__/HistoryModal.test.js
  src/components/UserProfile/__tests__/AddNewTeamModal.test.js
  src/components/UserProfile/__tests__/AssignBadgePopup.test.jsx
  src/components/UserProfile/__tests__/Teamsview.test.js
  src/styles.js
Labels: High Priority - Please Review First, Moved to Final Review

#2200 Iven - Allow accounts with permission make suggest on tasks and see the notification after approval
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/TaskEditSuggestions/thunks.js
Labels: High Priority - Please Review First

#2317 Ramakrishna fix mentor summary required
  src/components/SummaryBar/SummaryBar.jsx
Labels: hotfix

#2077 Luis edit warning description
  src/actions/warnings.js
  src/components/Warnings/WarningItem.jsx
  src/components/Warnings/Warnings.css
  src/components/Warnings/Warnings.jsx
  src/components/Warnings/WarningsModal.jsx
  src/components/Warnings/modals/WarningModal.jsx
  src/components/Warnings/modals/WarningTrackerModal.jsx
  src/components/Warnings/reorder.svg
  src/constants/warning.js
  src/reducers/warningsReducer.js
  src/utils/URL.js
Labels: Moved to Final Review

#2271 Peterson fix when adding team to profile save changes becomes disabled for other tabs
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
Labels: High Priority - Please Review First

#2316 Chris_Weekly_Summaries_Report_Refresh_Button
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First

#2224 Iven add teams team code colors filters on dashboard
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
Labels: High Priority - Please Review First

#2333 Nathalia make blue square description box bigger and auto-fit
  src/components/UserProfile/UserProfileModal/UserProfileModal.jsx
Labels: High Priority - Please Review First

#2279 Shiwani BMLogin Unit Test
  src/components/BMDashboard/Login/__tests__/BMLogin.test.js
Labels: Moved to Final Review

#2301 Ramakrishna Fix 5-Digit Search Function Breaks After Edits
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2341 Youyou click profile icon open in new tab
  src/components/UserManagement/ProfileNavDot.jsx
Labels: High Priority - Please Review First

#2330 Ramakrishna _Allowing the numbers in teamcode
  src/components/Reports/TeamTable.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: High Priority - Please Review First

#2331 Kyrene - Allow volunteers, admin and owners to click task and navigate to task page
  src/utils/routePermissions.js
Labels: High Priority - Please Review First

#2357 Abdel modal assign blue square emails
  src/actions/blueSquareEmailBCCAction.js
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/BluequareEmailBBCPopUp.jsx
  src/components/UserProfile/UserProfile.scss
  src/constants/BluequareEmailBccConstants.js
  src/reducers/blueSquareEmailBcc.js
  src/reducers/index.js
  src/utils/URL.js
Labels: do not review

#2300 Nathalia add popup icon to weekly summaries
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/EditableModal/RichTextEditor.jsx
  src/components/UserProfile/EditableModal/RoleInfoModal.jsx
  src/components/UserProfile/EditableModal/__tests__/roleInfoModal.test.js
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/routes.js
Labels: High Priority - Please Review First

#2373 Ramakrishnaupdated warning msg for incorrect teamcode saving
  src/components/Reports/TeamTable.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
Labels: hotfix

#1913 Jiayu took this over from Miguel - User Suggestion Edit
  src/components/SummaryBar/SummaryBar.css
  src/components/SummaryBar/SummaryBar.jsx
Labels: Moved to Final Review

#2135 Hoang fix hours inputs in task modal
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: High Priority - Please Review First

#2263 Imran fix permission access profile of project members
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/Projects/Members/Member/Member.jsx
  src/components/Projects/Members/Members.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2220 Anirudh - Leaderboard a way to see how many days until a person’s last day.
  .vscode/settings.json
  src/components/LeaderBoard/Leaderboard.css
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/LeaderBoard/__tests__/Leaderboard.test.jsx
Labels: High Priority - Please Review First

#2365 Nahiyan_Fix table header for mobile display
  src/components/LeaderBoard/Leaderboard.css
Labels: High Priority - Please Review First

#2377 added description to blue square created on date
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
Labels: do not review

#2242 Imran edit summary submit requirement others
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: High Priority - Please Review First

#2364 Chris_teamMemberTasks_reducer_unittest
  src/components/TeamMemberTasks/__tests__/reducer.test.js
Labels: Moved to Final Review

#2314 Shengwei_update_backend_permission_control_for_protected_account
  src/utils/permissions.js
Labels: High Priority - Please Review First

#2367 kaushik_people-status_rehireable_by_default
  src/components/Reports/PeopleReport/PeopleReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2310 Carlos add hours by team member visualization project reports
  __mocks__/styleMock.js
  jest.config.js
  package-lock.json
  package.json
  src/actions/index.js
  src/actions/project.js
  src/actions/projectMembers.js
  src/actions/task.js
  src/components/BMDashboard/ItemList/ItemsTable.jsx
  src/components/BMDashboard/LogTools/LogTools.jsx
  src/components/BMDashboard/ToolItemList/ToolItemsTable.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.css
  src/components/Reports/ProjectReport/PiechartByProject/PieChartByProject.jsx
  src/components/Reports/ProjectReport/PiechartByProject/TriMembersStateToggleSwitch/TriMembersStateToggleSwitch.css
  src/components/Reports/ProjectReport/PiechartByProject/TriMembersStateToggleSwitch/TriMembersStateToggleSwitch.jsx
  src/components/Reports/ProjectReport/ProjectReport.css
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/ProjectReport/WbsPiechart/WbsPieChart.jsx
  src/components/Reports/ProjectReport/WbsPiechart/data.js
  src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
  src/components/Reports/ProjectReport/selectors.js
  src/components/Reports/Reports.jsx
  src/components/Reports/TasksTable/TasksTable.jsx
  src/components/Reports/WbsTable/WbsTable.jsx
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/Reports/sharedComponents/ReportPage/ReportPage.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.css
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportCard/ReportCard.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/ReportHeader.jsx
  src/components/TaskEditSuggestions/service.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/reducer.js
  src/components/Timer/Countdown.jsx
  src/components/Timer/Timer.jsx
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/WeeklySummary/WeeklySummaryModal.jsx
  src/components/common/Checkbox/Checkbox.jsx
  src/components/common/Stub/Stub.jsx
  src/reducers/allTasksReducer.js
  src/reducers/bmdashboard/equipmentReducer.js
  src/reducers/bmdashboard/inventoryUnitReducer.js
  src/reducers/bmdashboard/materialsReducer.js
  src/reducers/bmdashboard/projectByIdReducer.js
  src/reducers/bmdashboard/projectReducer.js
  src/reducers/bmdashboard/reusablesReducer.js
  src/reducers/index.js
  src/reducers/timeEntriesByProjectForSpecifiedPeriodReducer.js
  src/routes.js
  src/setupTests.js
Labels: High Priority - Please Review First

#2298 Chris_spinning_wheel_date_change_reports
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2384 Chris_fix_unspecified_category_wbs
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: High Priority - Please Review First

#2307 Gowtham Opening multiple time logs sometimes loads my time log instead
  src/components/SummaryBar/SummaryBar.jsx
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First, high priority

#2225 Hiral fix profile page formatting
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsAndProjects.css
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: High Priority - Please Review First

#2387 Remove dead space in user profile section
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.scss
Labels: High Priority - Please Review First

#2287 Imran added General Section to Permissions
  src/components/PermissionsManagement/PermissionsConst.js
Labels: hotfix

#2221 Nathan separate edit time entry permissions
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/Reports/LostTime/LostTimeHistory.jsx
  src/components/Timelog/TimeEntry.jsx
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First
