Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-09, with the labels that each got.

#2542 Vijay Anand assign badge popup ui fix
  src/components/Badge/AssignBadgePopup.css
  src/components/Badge/AssignBadgePopup.jsx
Labels: High Priority - Please Review First, Moved to Final Review, do not review

#2572 Shadhrush - Fixing "Send Emails" visibility for Volunteers with 'Other Links' access and adding a new Send Emails Permission.
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/Header/Header.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/routes.js
  src/utils/routePermissions.js
Labels: High Priority - Please Review First, Moved to Final Review

#2530 Shrada User Profile Modal Fix
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: Moved to Final Review

#2597 Vijay Anand - Added search by name functionality feature to Leaderboard Component
  src/components/LeaderBoard/Leaderboard.jsx
Labels: Moved to Final Review

#2630 Ivy-hotfix-isSet-resolve-twice-render
  src/components/UserManagement/SetUpFinalDayButton.jsx
Labels: do not review

#2248 Imran split blue squares permissions
  src/__tests__/mockAdminState.js
  src/__tests__/mockStates.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/BlueSquares/__tests__/BlueSquare.test.js
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileModal/UserProfileModal.jsx
  src/components/UserProfile/UserProfileModal/__tests__/USerProfileModal.test.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2549 Ivy-invalid password alert and errors to be displayed appropriately below the text input area.
  src/actions/authActions.js
  src/components/Login/Login.jsx
  src/components/UpdatePassword/__tests__/UpdatePassword.test.js
  src/components/common/Form/Form.jsx
Labels: High Priority - Please Review First

#2636 Reina filtering UI badge management
  package-lock.json
  package.json
  src/components/Badge/Badge.css
  src/components/Badge/BadgeDevelopment.jsx
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/BadgeTableHeader.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/SummaryBar/SummaryBar.css
  src/components/SummaryBar/SummaryBar.jsx
Labels: medium priority

#2345 Jingyi edit header message
  src/components/OwnerMessage/OwnerMessage.jsx
  src/components/PermissionsManagement/PermissionsConst.js
Labels: Moved to Final Review

#2614 Nahiyan_Optimized dashboard for mobile view
  src/components/Footer/NetlifyPoweredLink.js
  src/components/Header/Header.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/TeamMemberTasks/style.css
  src/components/Warnings/Warnings.jsx
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: High Priority - Please Review First

#2585 Nahiyan_Fixed Numbering Issue in Dark Mode
  src/components/Projects/Project/Project.jsx
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/wbs.test.jsx
Labels: Moved to Final Review

#2374 Jatin create quick setup function permissions
  src/actions/title.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignProjectField.jsx
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamCodeField.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamField.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupCodes.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileEdit/SaveButton.jsx
  src/utils/URL.js
  src/utils/permissions.js
Labels: Moved to Final Review

#2608 jatin fix the the urls inside team-weekly-summaries tab.
  src/components/UserProfile/TeamWeeklySummaries/TeamWeeklySummaries.css
Labels: Moved to Final Review

#2591 Manikrishna-found-redundant-code-removed
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
Labels: Moved to Final Review

#2471 Logeshwari - Fix for Newly Created Role not displayed in Permission Management
  src/actions/role.js
  src/components/PermissionsManagement/NewRolePopUp.jsx
  src/components/PermissionsManagement/PermissionsManagement.jsx
Labels: High Priority - Please Review First

#2637 Peterson implement add members button and modal to profile teams tab teams
  src/components/Teams/MembersAutoComplete.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/UserProfile/TeamsAndProjects/TeamMember.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: Moved to Final Review

#2410 Gowtham filter by over hours
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First

#2575 Howie Clear Insert field when used
  src/components/Announcements/index.jsx
Labels: Moved to Final Review

#2588 Peterson make people report tasks contributed section invisible if no tasks
  src/components/Reports/PeopleReport/PeopleReport.jsx
Labels: High Priority - Please Review First

#2627 Logeshwari - fix for team management page struck on team edit
  src/components/Teams/Teams.jsx
Labels: medium priority

#2561 Peizhou_Fix Add New Project Category & Ability to Change Category
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Projects.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2508 Ivy-bar-chart-summary-and-barChart-template
  src/actions/totalOrgSummary.js
  src/components/TotalOrgSummary/HoursCompleted/HoursCompletedBarChart.jsx
  src/components/TotalOrgSummary/TinyBarChart.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/barChart.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First

#2646 Aaryaneil - Added test cases for AddTeamsAutoComplete
  src/components/UserProfile/TeamsAndProjects/__tests__/AddTeamsAutoComplete.test.jsx
Labels: Moved to Final Review

#2675 Yashwanth - Edited mouseover text in assign team
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: hotfix

#2553 Shrada Fix Time Log OverLap
  src/components/Timelog/TimeEntry.jsx
Labels: Moved to Final Review

#2651 ambika fix tasks contributed section of people reports page
  src/components/Reports/PeopleTableDetails.css
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/sharedComponents/ReportPage/ReportPage.css
  src/components/UserManagement/TextSuggestion.jsx
Labels: High Priority - Please Review First

#2681 Adding z-index to button
  src/components/UserProfile/TeamsAndProjects/TeamsAndProjects.css
Labels: High Priority - Please Review First

#2688 Kyrene- Quick Setup Tool: Fix links not added when using new quick setup
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupCodes.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/UserProfile/UserLinks/UserLinks.jsx
Labels: High Priority - Please Review First

#2656 Howie Add Dropdowns for Owner Perms Table and removing bloat
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
Labels: High Priority - Please Review First

#2622 Chetan - fixed the ux issue with the summary bar
  src/components/Dashboard/Dashboard.jsx
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review, medium priority

#2517 Vijay Anand fix for unusual timelog active or inactive popup when cmd/ctrl + timelog icon is clicked
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review

#2610 Yili fix active status issue on team management page
  src/components/Teams/TeamStatusPopup.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/__tests__/TeamStatusPopup.test.js
Labels: Moved to Final Review

#2611 Jingyi leaderboard time off indicator
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#2335 Anand_Added Date Error message validation in Add Task Modal
  src/components/Header/DarkMode.css
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/languages/en/messages.js
Labels: High Priority - Please Review First

#2342 Peterson_Fix_Tasks_tab_revert_to_Current_Week_Timelog_tab_for_Volunte…
  src/components/Timelog/Timelog.jsx
Labels: Moved to Final Review

#2596 Niketha Anand- Rotate indefinitely after adding project
  src/components/Projects/AddProject/AddProject.jsx
  src/components/Projects/AddProject/AddProject.test.jsx
  src/components/Projects/Projects.jsx
Labels: Moved to Final Review

#2725 Strallia: Fix non-interactive tasks list on dashboard in Safari
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First

#2719 Niketha - Fix Category column on Projects page
  src/components/Projects/Project/Project.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2674 Ambika fix add permissions checks to disable buttons in user management
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/__tests__/ResetPasswordButton.test.js
  src/components/UserManagement/__tests__/UserTableData.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2544 Ambika fix Badge Development > Edit and Delete buttons must be disabled/enabled based on permissions
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/__tests__/BadgeDevelopmentTable.test.js
Labels: High Priority - Please Review First

#2660 Vijay Anand - UI fix for i icon in tasks and timelogs component
  src/components/TeamMemberTasks/FollowUpInfoModal.css
Labels: Moved to Final Review

#2600 ambika fix core team unique additions in leaderboard
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#2689 Change the UI of the dropdown on clicking the ‘Edit’ button next to a task
  src/components/Projects/WBS/WBSDetail/ControllerRow/ControllerRow.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
  src/components/UserProfile/UserProfileEdit/UserProfileEdit.jsx
Labels: Moved to Final Review, medium priority

#2679 WBS table UI changes for task and action columns
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#2709 Anne Fixed spacing between task rows and within task rows in WBS
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#2712 Yili - Fix the Tasks “Active” column filter
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
Labels: Moved to Final Review

#2703 Howie make task link requried for submission
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: High Priority - Please Review First
