Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2024-10, with the labels that each got.

#2649 Yili - When entering WBS management page of a project with timer on, the timer will stop
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/wbs.test.jsx
Labels: Moved to Final Review

#2250 Anand_Dark mode for all modals on Reports page
  src/components/Header/DarkMode.css
  src/components/Reports/LostTime/AddLostTime.jsx
  src/components/Reports/LostTime/EditHistoryModal.jsx
  src/components/Reports/LostTime/LostTimeHistory.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/TotalReport/TotalTeamReport.jsx
  src/components/Reports/ViewReportsByDate/ViewReportsByDate.jsx
  src/components/UserProfile/EditableModal/EditableInfoModal.css
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
  src/components/UserProfile/EditableModal/roleInfoModal.jsx
  src/styles.js
Labels: High Priority - Please Review First

#2740 Anand_BadgeManagement_Unit_Test
  src/components/Badge/__tests__/BadgeManagement.test.js
Labels: Moved to Final Review

#2749 Swathi-fix-task-view-and-the-dots-with-initials
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#2694 Sriram - add a button to create new projects
  src/actions/projects.js
  src/components/Projects/AddProject/AddProject.jsx
  src/components/Projects/AddProject/AddProject.test.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/__tests__/Projects.test.jsx
Labels: Moved to Final Review

#2702 Cillian: Add invisibility indicator to Team members page
  src/components/Teams/TeamMembersPopup.jsx
Labels: Moved to Final Review, high priority

#2197 Peterson_impl_improve_user_Management_page_search_function_to_include…
  src/components/UserManagement/UserManagement.jsx
Labels: Moved to Final Review

#2648 Haoyue fix formatting of created title
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
Labels: Moved to Final Review

#2715 Deepthi fix spacing between labels and input fields
  src/components/Announcements/Announcements.css
  src/components/Announcements/index.jsx
Labels: Moved to Final Review, do not review

#2705 Strallia: Fix page crashing when selecting featured badges
  src/components/Badge/BadgeReport.jsx
Labels: High Priority - Please Review First

#2686 Peterson fix the bug where the team code input can be edited by users who are not owners or administrators
  src/components/UserProfile/TeamsAndProjects/AutoCompleteTeamCode.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2385 Peterson implement the create project feature in the user profile section and in the project tab
  src/actions/projects.js
  src/components/Badge/__tests__/NewBadges.test.js
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
  src/components/UserProfile/TeamsAndProjects/AddProjectsAutoComplete.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsAndProjects.css
Labels: High Priority - Please Review First

#2655 Huijie - fix ability to edit start and end date
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
  src/utils/formatDate.js
Labels: Moved to Final Review

#2758 Mohan - fix team code blank screen issue
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2766 Crystal fix tasks of members are hidden when teams toggle is off
  src/components/Teams/InfoModal.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2620 Jatin make columns editable by owner
  src/actions/userManagement.js
  src/components/TeamMemberTasks/TeamMemberTasks.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableFooter.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/__tests__/UserTableData.test.js
  src/components/UserManagement/__tests__/UserTableHeader.test.js
  src/components/UserManagement/usermanagement.css
  src/constants/userManagement.js
  src/reducers/allUserProfilesReducer.js
  src/reducers/index.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2233 Peterson - Fix the issue causing the user profile page to display a white screen upon access
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: High Priority - Please Review First

#2525 Fix Badges Select Featured and Edit Personal Max Functions
  src/actions/badgeManagement.js
  src/components/Badge/AssignTableRow.jsx
  src/components/Badge/AssignTableRow.test.js
  src/components/Badge/BadgeReport.jsx
  src/components/UserProfile/AssignBadgePopup.jsx
  src/components/UserProfile/BadgeImage/BadgeImage.jsx
  src/components/UserProfile/BadgeImage/__tests__/BadgeImage.test.js
Labels: High Priority - Please Review First

#2782 Nikhil G - Fix project report formatting of members table
  src/components/Reports/ProjectMemberTable/ProjectMemberTable.css
Labels: High Priority - Please Review First, Moved to Final Review

#2787 Howie add double confirmation for task link submission
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: High Priority - Please Review First

#2746 Ajay - fix verified the user data and fixed the UI/UX issues of the user list.
  src/components/TeamLocations/ListUsersPopUp.jsx
  src/components/TeamLocations/TeamLocations.css
  src/components/TeamLocations/TeamLocations.jsx
Labels: High Priority - Please Review First

#1667 Changhao - Unit test for textsearchbox
  ..env.un~
  .env~
  .vscode/settings.json
  src/components/UserManagement/__tests__/TextSearchBox.test.js
Labels: High Priority - Please Review First

#1619 Changhao - Unit testing for CountdownTimer
  src/__tests__/CountdownTimer.test.js
Labels: High Priority - Please Review First

#2535 Nandini Fixes Hours Status
  src/components/Timelog/EffortBar.jsx
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#2750 pavanswaroop-fixed-hours-section-to-lessen-vertical-space
  src/components/Projects/WBS/SingleTask/SingleTask.js
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: High Priority - Please Review First

#2700 Haoyue title summary on profile page
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupCodes.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.css
Labels: High Priority - Please Review First

#2798 Ajay - fix date mismatch on reports and user management
  src/components/Reports/PeopleTable.js
Labels: High Priority - Please Review First

#2589 Ramakrishna fix openingteams newtab
  src/components/Projects/WBS/WBSDetail/wbs.css
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Reports/TeamReport/__tests__/TeamReport.test.js
  src/components/Reports/TeamReport/components/TeamReportLogs.jsx
  src/components/Reports/TeamReport/components/UserLoginPrivileges.jsx
Labels: medium priority
