Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-06, with the labels that each got.

#3123 SaiPreetham_Updated logic for Hide Pause and Set Final Day Buttons in Volunteer Dashboard - Role-Based Access Fix
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3107 Honglin lesson list buttons sorting and filtering features
  src/actions/bmdashboard/lessonLikesActions.js
  src/actions/bmdashboard/lessonsAction.js
  src/actions/bmdashboard/projectByIdAction.js
  src/components/BMDashboard/LessonList/LessonCard.jsx
  src/components/BMDashboard/LessonList/LessonListForm.jsx
  src/components/BMDashboard/LessonList/Lessons.jsx
  src/reducers/bmdashboard/lessonsReducer.js
Labels: High Priority - Please Review First

#3560 Shashank Add Tooltip and Stats in legend
  src/components/TotalOrgSummary/VolunteerRolesTeamDynamics/RoleDistributionPieChart.jsx
Labels: High Priority - Please Review First

#3378 Guirong-Fix Reports>Reports formatting, “i” editability, duplicate button, and add new filter
  src/components/Notification/__tests__/notification.test.js
  src/components/Reports/ReportFilter/ReportFilter.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalContributorsReport.jsx
  src/components/Reports/reportsPage.css
  src/components/UserProfile/EditableModal/EditableInfoModal.jsx
Labels: High Priority - Please Review First

#3064 Rishitha add new team form
  src/components/BMDashboard/Team/CreateNewTeam/CreateNewTeam.css
  src/components/BMDashboard/Team/CreateNewTeam/CreateNewTeam.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3522 Dhrumil-added-test-cases-ImportTask
  src/components/Projects/WBS/WBSDetail/ImportTask/__tests__/ImportTask.test.js
Labels: High Priority - Please Review First

#3570 Dharmik - fix teamCode outliers
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.module.scss
Labels: High Priority - Please Review First

#3280 Zhifan - Create way to see 6 months & yearly anniversaries
  src/actions/leaderBoardData.js
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/constants/leaderBoardData.js
  src/services/httpService.js
  src/utils/URL.js
  src/utils/anniversaryPermissions.js
Labels: High Priority - Please Review First

#2953 Aishwarya - Create way to see 6 months & yearly anniversaries
  src/actions/leaderBoardData.js
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/constants/leaderBoardData.js
  src/utils/URL.js
  src/utils/anniversaryPermissions.js
Labels: Needs New Developer, do not review

#3167 Nikhil - Added unit test for userManagement.js
  src/actions/__tests__/userManagement.test.js
Labels: Moved to Final Review

#3550 Dharmik - fix/Add number of blue squares to bottom left corner of first column on User Management Page
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/usermanagement.css
Labels: High Priority - Please Review First

#3408 Sidhartha sunkasari date range comparision filters
  src/components/TotalOrgSummary/AnniversaryCelebrated/AnniversaryCelebrated.jsx
  src/components/TotalOrgSummary/BlueSquareStats/BlueSquareStats.jsx
  src/components/TotalOrgSummary/DonutChart/DonutChart.jsx
  src/components/TotalOrgSummary/HoursCompleted/HoursCompletedBarChart.jsx
  src/components/TotalOrgSummary/HoursWorkedPieChart/HoursWorkedPieChart.jsx
  src/components/TotalOrgSummary/StatisticsTab/StatisticsTab.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/VolunteerActivities/VolunteerActivities.jsx
  src/components/TotalOrgSummary/VolunteerHoursDistribution/VolunteerHoursDistribution.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatus.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusChart.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusPieChart.jsx
  src/store.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3547 Zhifan - Fix email notification for setting last day saying the next day is their last day
  src/actions/userManagement.js
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#3654 Manusha Job Posting Page Analytics: Create a donut chart showing applicants by experience
  src/components/ExperienceDonutChart/ExperienceDonutChart.css
  src/components/ExperienceDonutChart/ExperienceDonutChart.jsx
  src/components/ExperienceDonutChart/index.js
  src/routes.js
Labels: High Priority - Please Review First

#3532 Koushica - Conversion from JobFormBuilder.css file to JobFormBuilder.module.css file
  src/components/Collaboration/JobFormBuilder.module.css
  src/components/Collaboration/JobFormbuilder.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3081 Pratyush Event Attendance and No Show track
  src/components/AttendanceSystem/AttendanceNoShowCharts.js
  src/routes.js
Labels: High Priority - Please Review First

#3192 Pratyush Develop Visualizations for Event Popularity Analytics
  src/components/EventPopularity/EventPopularity.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3325 Koushica - Listing and bidding platform: Create wish lists for users frontend
  src/components/LBDashboard/Components/ImageCarousel.css
  src/components/LBDashboard/Components/ImageCarousel.jsx
  src/components/LBDashboard/Header.jsx
  src/components/LBDashboard/WishList/ItemOverview.css
  src/components/LBDashboard/WishList/ItemOverview.jsx
  src/components/LBDashboard/WishList/WishList.css
  src/components/LBDashboard/WishList/WishList.jsx
  src/reducers/index.js
  src/reducers/lbdashboard/wishListItemReducer.js
  src/routes.js
Labels: High Priority - Please Review First

#3611 Koushica - Resource management dashboard
  src/components/ResourceManagement/ResourceManagement.jsx
  src/components/ResourceManagement/ResourceManagement.module.css
  src/routes.js
Labels: High Priority - Please Review First

#3573 Amalesh - Resolving the linting errors caused by the final few folders
  .eslintignore
  src/components/Announcements/index.jsx
  src/components/ForcePasswordUpdate/__tests__/ForcePasswordUpdate.test.js
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Timelog/Timelog.jsx
  src/components/UserManagement/DropDownSearchBox.jsx
  src/components/UserManagement/PauseAndResumeButton.jsx
  src/components/UserManagement/ProfileNavDot.jsx
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserManagement/SetUpFinalDayPopUp.jsx
  src/components/UserManagement/TextSuggestion.jsx
  src/components/UserManagement/TimeDifference.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/__tests__/DeleteUserPopup.test.js
  src/components/UserManagement/__tests__/DropDownSearchBox.test.js
  src/components/UserManagement/__tests__/ProfileNavDot.test.jsx
  src/components/UserManagement/__tests__/SetUpFinalDayButton.test.js
  src/components/UserManagement/__tests__/SetUpFinalDayPopUp.test.jsx
  src/components/UserManagement/__tests__/UserManagement.test.js
  src/components/UserManagement/__tests__/UserTableHeader.test.js
  src/components/UserManagement/index.js
  src/components/UserManagement/setupNewUserPopup.jsx
Labels: High Priority - Please Review First

#3552 Reina create line chart showing total rental costs over time
  src/actions/bmdashboard/rentalChartActions.js
  src/components/BMDashboard/RentalChart/RentalChart.css
  src/components/BMDashboard/RentalChart/RentalChart.jsx
  src/constants/bmdashboard/rentalChartConstants.js
  src/reducers/bmdashboard/rentalChartReducer.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3590 Bhavpreet - community portal activity comment section
  src/components/CommunityPortal/Activities/activityId/Activity.css
  src/components/CommunityPortal/Activities/activityId/Activity.jsx
  src/components/CommunityPortal/Activities/activityId/CommentSection/CommentSection.css
  src/components/CommunityPortal/Activities/activityId/CommentSection/CommentSection.jsx
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
  src/routes.js
Labels: High Priority

#3640 Nikhil Routh Migrate src/components/HGNForm css to module css
  refactor-css-classes.js
  src/components/HGNForm/pages/Page1.js
  src/components/HGNForm/questionpages/BackendQuestions.js
  src/components/HGNForm/questionpages/Banner.js
  src/components/HGNForm/questionpages/FollowupQuestions.js
  src/components/HGNForm/questionpages/FrontendQuestions.js
  src/components/HGNForm/questionpages/GeneralQuestions.js
  src/components/HGNForm/questionpages/InfoForm.js
  src/components/HGNForm/questionpages/Progress.js
  src/components/HGNForm/questionpages/QuestionnaireHeader.js
  src/components/HGNForm/questionpages/QuestionnaireInfo.js
  src/components/HGNForm/questionpages/ThankYou.js
  src/components/HGNForm/styles/Banner.module.css
  src/components/HGNForm/styles/FollowupQuestions.module.css
  src/components/HGNForm/styles/FrontendBackendQuestions.module.css
  src/components/HGNForm/styles/GeneralQuestions.module.css
  src/components/HGNForm/styles/InfoForm.module.css
  src/components/HGNForm/styles/Progress.module.css
  src/components/HGNForm/styles/QuestionnaireInfo.module.css
  src/components/HGNForm/styles/hgnform.module.css
Labels: High Priority - Please Review First

#3476 Bhavpreet- LB platform - messaging frontend
  package-lock.json
  package.json
  public/big-sign.png
  refactor-css-classes.js
  src/actions/lbdashboard/messagingActions.js
  src/actions/lbdashboard/userPreferenceActions.js
  src/components/App.jsx
  src/components/Header/BellNotification.jsx
  src/components/LBDashboard/ListingOverview/Listoverview.module.css
  src/components/LBDashboard/Login/LBLogin.jsx
  src/components/LBDashboard/Map/MasterPlan/MasterPlan.module.css
  src/components/LBDashboard/Messaging/LBMessaging.css
  src/components/LBDashboard/Messaging/LBMessaging.jsx
  src/components/Notification/__tests__/notification.test.js
  src/components/Notification/notificationCard.jsx
  src/components/TaskEditSuggestions/reducer.js
  src/components/Timer/TimerPopout.jsx
  src/components/WeeklySummariesReport/__tests__/WeeklySummariesReport.test.js
  src/components/WeeklySummary/__tests__/WeeklySummary.test.js
  src/components/__tests__/App.test.js
  src/constants/lbdashboard/messagingConstants.js
  src/constants/lbdashboard/userPreferenceConstants.js
  src/handlers/LBDashboard/messagingHandlers.js
  src/reducers/index.js
  src/reducers/lbdashboard/messagingReducer.js
  src/reducers/lbdashboard/userPreferencesReducer.js
  src/routes.js
  src/store.js
  src/utils/URL.js
  src/utils/messagingSocket.js
Labels: High Priority - Please Review First

#3653 Rahul - Fix Tasks Table User Status Column
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First

#3567 Dhrumil BiddingHomepage component and associated styles
  src/components/LBDashboard/BiddingHomepage/BiddingHomepage.css
  src/components/LBDashboard/BiddingHomepage/BiddingHomepage.jsx
  src/routes.js
Labels: High Priority - Please Review First

#1850 Anirudh SK finishing for Jay - PERMISSION: Modify Task X on Dashboard Permission
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: High Priority - Please Review First, Needs New Developer

#3433 Pallavi Implemented Copy question sets
  src/components/Collaboration/JobFormbuilder.jsx
  src/components/Collaboration/QuestionEditModal.css
  src/components/Collaboration/QuestionEditModal.jsx
  src/components/Collaboration/QuestionFieldActions.css
  src/components/Collaboration/QuestionFieldActions.jsx
  src/components/Collaboration/QuestionSetManager.css
  src/components/Collaboration/QuestionSetManager.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First

#3675 pallavi implemented job analytics graph
  package-lock.json
  src/components/ApplicationAnalytics/api.js
  src/components/ApplicationAnalytics/data.js
  src/components/ApplicationAnalytics/index.jsx
  src/components/ApplicationAnalytics/jobAnalytics.css
  src/components/ApplicationAnalytics/jobAnalytics.jsx
  src/routes.js
Labels: High Priority - Please Review First, Moved to Final Review
