Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-01, with the labels that each got.

#2743 Added sorting functionality to equipment table
  src/components/BMDashboard/Equipment/List/EquipmentsTable.jsx
Labels: Moved to Final Review, medium priority

#2753 Anirudh - Equipment add page Redirects to equipments page changes
  src/components/BMDashboard/Equipment/Add/AddTypeForm.jsx
Labels: medium priority

#2764 Rishitha fix purchase request
  src/components/BMDashboard/ItemList/RecordsModal.jsx
  src/components/BMDashboard/PurchaseRequests/PurchaseForm.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2818 Fix white screen issue on task deletion
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: Moved to Final Review

#3013 Haoyue - Modified the hover text for Add QST button
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
Labels: High Priority - Please Review First

#2566 Reina delete own time
  .eslintrc.json
  package-lock.json
  package.json
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/Timelog/DeleteModal.jsx
  src/components/Timelog/TimeEntry.jsx
  src/components/UserManagement/__tests__/PauseAndResumeButton.test.js
Labels: Moved to Final Review, medium priority

#2916 Reina delete tags from lessonlist
  src/components/BMDashboard/LessonList/ConfirmationModal.jsx
  src/components/BMDashboard/LessonList/LessonListForm.css
  src/components/BMDashboard/LessonList/LessonListForm.jsx
  src/components/BMDashboard/Projects/ProjectSelectForm.jsx
  src/utils/URL.js
Labels: high priority

#2671 Reina - Added changes to allow badge filtering in the badge management page
  src/components/Badge/Badge.css
  src/components/Badge/BadgeDevelopment.jsx
  src/components/Badge/BadgeDevelopmentTable.jsx
  src/components/Badge/BadgeTableHeader.jsx
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Project/Project.test.jsx
Labels: High Priority - Please Review First

#2708 Mohan - Finishing for Vedant - Fix assign team button hover at smaller resolutions
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/ToolTips/TeamsTabTips.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: Moved to Final Review, Needs New Developer, do not review

#3007 Strallia - Chart Components for Total Org Summary Page
  package-lock.json
  package.json
  src/actions/totalOrgSummary.js
  src/components/TotalOrgSummary/BlueSquareStats/BlueSquareStats.css
  src/components/TotalOrgSummary/BlueSquareStats/BlueSquareStats.jsx
  src/components/TotalOrgSummary/DonutChart/DonutChart.css
  src/components/TotalOrgSummary/DonutChart/DonutChart.jsx
  src/components/TotalOrgSummary/StatisticsTab/StatisticsTab.css
  src/components/TotalOrgSummary/StatisticsTab/StatisticsTab.jsx
  src/components/TotalOrgSummary/TeamStats/TeamStats.css
  src/components/TotalOrgSummary/TeamStats/TeamStats.jsx
  src/components/TotalOrgSummary/TeamStats/TeamStatsBarChart.css
  src/components/TotalOrgSummary/TeamStats/TeamStatsBarChart.jsx
  src/components/TotalOrgSummary/TeamStats/TeamStatsBarLabel.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
  src/components/TotalOrgSummary/VolunteerActivities/VolunteerActivities.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatus.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusChart.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusPieChart.css
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusPieChart.jsx
  src/constants/totalOrgSummary.js
  src/reducers/__tests__/totalOrgSummaryReducer.test.js
  src/reducers/totalOrgSummaryReducer.js
  src/utils/URL.js
  src/utils/totalOrgSummary.js
Labels: do not review

#2802 howie fit teams table width into all devices
  src/components/Teams/Team.css
Labels: Moved to Final Review

#2763 Peterson_fix_bug_after_being_clicked_outside_the_modal_is_not_closed
  src/components/Badge/BadgeDevelopment.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2978 Reina create way to change order of QST codes
  package-lock.json
  package.json
  src/components/UserProfile/QuickSetupModal/EditTitlesModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.css
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/utils/URL.js
Labels: high priority, Saved for Later Implementation

#2801 Snehal fix user id dashboard
  src/components/Dashboard/Dashboard.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3035 Reina - Phase 2 create new team member
  src/components/BMDashboard/AddTeamMember/AddTeamMember.css
  src/components/BMDashboard/AddTeamMember/AddTeamMember.jsx
  src/components/TotalOrgSummary/DonutChart/DonutChart.jsx
  src/components/TotalOrgSummary/VolunteerStatus/VolunteerStatusPieChart.jsx
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3062 peterson_fix_bug_in_Team_Member_Tasks_Table
  src/components/Timelog/Timelog.jsx
Labels: do not review

#2714 Jatin get profile images from website
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileModal/UserProfileModal.css
  src/components/UserProfile/UserProfileModal/confirmRemoveModal.js
  src/components/UserProfile/UserProfileModal/suggestedProfileModal.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#2862 Snehal delete members from the project
  src/components/Projects/Members/Member/Member.jsx
  src/components/Projects/Members/Member/__tests__/Member.test.jsx
  src/components/Projects/Members/Members.jsx
Labels: High Priority - Please Review First

#2852 Xiaolu finish the unit test for BlueSquaresTable
  src/components/UserProfile/BlueSquaresTable/BlueSquaresTable.jsx
  src/components/UserProfile/BlueSquaresTable/__tests__/BlueSquaresTable.test.js
Labels: Moved to Final Review

#3027 Nanguan Add test for CreateNewBadgePopup.jsx
  src/components/Badge/__tests__/CreateNewBadgePopup.test.js
Labels: Moved to Final Review

#2621 Peterson implement improvements in team code input
  src/components/UserProfile/TeamsAndProjects/AutoCompleteTeamCode.jsx
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: do not review

#3050 Shashank - Fixed UI Issues in header
  src/components/Header/DarkModeButton.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
Labels: High Priority - Please Review First

#3080 Create Login and Registration pages for Listing and Bidding Dashboard
  src/assets/images/logo2.png
  src/components/LBDashboard/Auth/Auth.css
  src/components/LBDashboard/Auth/Login.jsx
  src/components/LBDashboard/Auth/Register.jsx
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First
