Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-04, with the labels that each got.

#3343 Dhrumil-Bidding-Overview-Frontend
  src/components/LBDashboard/BiddingOverview/BiddingOverview.css
  src/components/LBDashboard/BiddingOverview/BiddingOverview.jsx
  src/routes.js
Labels: Medium Priority

#3006 Aaryaneil - Unit Test for ownerMessageReducer
  src/reducers/__tests__/ownerMessageReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#3002 Aaryaneil - Unit Tests errorsReducer component
  src/reducers/__tests__/errorsReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#3000 Aaryaneil - Unit Tests teamByIdReducer
  src/reducers/__tests__/teamByIdReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2998 Aaryaneil Unit Tests for userProjectMembersReducer component
  src/reducers/__tests__/userProjectMembersReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2997 Aaryaneil - Unit Tests for userTeamMembersReducer component
  src/reducers/__tests__/userTeamMembersReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2995 Aaryaneil unit tests wbsReducer
  src/reducers/__tests__/wbsReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2971 Aaryaneil Unit Test actionItemsReducer
  src/reducers/__tests__/actionItemsReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2739 Aaryaneil - Added unit tests for allProjectsReducer.
  src/reducers/__tests__/allProjectsReducer.test.js
Labels: Moved to Final Review

#3004 Aaryaneil - Unit Tests for userProfileByIdReducer
  src/reducers/__tests__/userProfileByIdReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#2407 Aaryaneil PieChartInfoDetail unit test
  src/components/Reports/TeamReport/components/__tests__/PieChartInfoDetail.test.js
Labels: Moved to Final Review

#2615 Aaryaneil unit test delete badge popup
  src/components/Badge/__tests__/DeleteBadgePopup.test.jsx
Labels: Moved to Final Review

#2616 Aaryaneil - Added tests cases for PeopleTasksPieChart.
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.test.jsx
Labels: Moved to Final Review

#2618 Aaryaneil - Added test cases for ProfileNavDot.
  src/components/UserManagement/__tests__/ProfileNavDot.test.jsx
Labels: Moved to Final Review

#2645 Aaryaneil - Added tests for SetUpFinalDayPopUp component
  src/components/UserManagement/__tests__/SetUpFinalDayPopUp.test.jsx
Labels: Moved to Final Review

#2737 Aaryaneil - Added unit test for authReducer.
  src/reducers/__tests__/authReducer.test.js
Labels: Moved to Final Review

#2738 Aaryaneil - Created unit tests for leaderboardDataReducer.
  src/reducers/__tests__/leaderboardDataReducer.test.js
Labels: Moved to Final Review

#3001 Aaryaneil - Unit Tests for projectByIdReducer component
  src/reducers/__tests__/projectByIdReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#3003 Aaryaneil - Unit Tests for rolePresetReducer
  src/reducers/__tests__/rolePresetReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#3005 Aaryaneil - Unit tests for popupEditorReducer
  src/reducers/__tests__/popupEditorReducer.test.js
Labels: High Priority - Please Review First, Moved to Final Review

#3369 Prit-Fixed: Profile page formatting of Teams row box and Team Name vertical centering
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.css
  src/components/UserProfile/TeamsAndProjects/UserTeamsTable.jsx
Labels: High Priority - Please Review First

#3356 Amalesh-Frontend-Pages-For-New-Google-Form-Equivalent-For-Technical-Support-And-Advisory-Volunteer-Agreement
  src/components/TSAForm/pages/TSAFormPage1.js
  src/components/TSAForm/pages/TSAFormPage2.js
  src/components/TSAForm/pages/TSAFormPage3.js
  src/components/TSAForm/pages/TSAFormPage4.js
  src/components/TSAForm/pages/TSAFormPage5.js
  src/components/TSAForm/pages/TSAFormPage6.js
  src/components/TSAForm/pages/TSAFormPage7.js
  src/components/TSAForm/pages/TSAFormPage8.js
  src/routes.js
Labels: High Priority - Please Review First

#3252 Yili - unit test : WeeklySummariesReport /FormattedReport
  src/components/WeeklySummariesReport/__tests__/FormattedReport.test.js
Labels: Moved to Final Review

#2583 Yili fix UI issues on the User Management Page
  src/components/UpdatePassword/UpdatePassword.jsx
  src/components/UpdatePassword/__tests__/UpdatePassword.test.js
  src/components/UpdatePassword/__tests__/UpdatePassword_withoutMock.test.js
  src/components/UserManagement/ResetPasswordPopup.jsx
  src/components/UserManagement/SetupHistoryPopup.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserSearchPanel.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableHeader.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
Labels: High Priority - Please Review First

#3366 Angad - Hotfix broken teams page formatting and team members not visible.
  src/components/Teams/Team.css
  src/components/Teams/Team.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/TeamsOverview.css
Labels: High Priority - Please Review First

#3294 Vinay: Let a user know through a popup that Permissions have been changed for them
  src/components/Header/Header.jsx
  src/components/PopUpBar/PopUpBar.jsx
  src/components/PopUpBar/__tests__/PopUpBar.test.jsx
Labels: High Priority - Please Review First

#3380 Amalesh - Fixing Linting Errors in "Common" and "EmailSubscribeForm" folders
  .eslintignore
  src/components/EmailSubscribeForm/ConfirmationMessage.js
  src/components/EmailSubscribeForm/Unsubscribe/ConfirmationMessage.js
  src/components/EmailSubscribeForm/Unsubscribe/index.js
  src/components/EmailSubscribeForm/UnsubscribeForm.js
  src/components/EmailSubscribeForm/index.js
  src/components/common/CPDashboard/CPProtectedRoute/CPProtectedRoute.jsx
  src/components/common/EmailSender/EmailSender.jsx
  src/components/common/FileUpload/FileUpload.jsx
  src/components/common/FileUpload/__tests__/FileUpload.test.jsx
  src/components/common/Form/Form.jsx
  src/components/common/Image/Image.test.jsx
  src/components/common/Modal/CustomModalHeader.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/PieChart/PieChart.jsx
  src/components/common/PieChart/ProjectPieChart.jsx
  src/components/common/ShowSaveWarning.test.jsx
  src/components/common/TwoWayToggleSwitch/TwoWayToggleSwitch.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3398 Bhavpreet - Fixes the issue of code replacement of inactive user
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/utils/URL.js
Labels: High Priority - Please Review First, High Priority

#2860 Yili - Gives the user permission to Reset and/or Change the password of any user
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/UserManagement/ResetPasswordButton.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/__tests__/ResetPasswordButton.test.js
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#3175 Yili - unit test : Reports/PeopleTableDetails
  src/components/Reports/PeopleTableDetails.jsx
  src/components/Reports/__tests__/PeopleTableDetails.test.js
Labels: High Priority - Please Review First, Moved to Final Review, do not review

#3293 Bhavpreet- Create choosing village map frontend
  src/assets/images/masterMap.png
  src/assets/images/pin-point.png
  src/assets/images/routeMarker.png
  src/components/LBDashboard/Map/MasterPlan/MasterPlan.css
  src/components/LBDashboard/Map/MasterPlan/MasterPlan.jsx
  src/routes.js
Labels: High Priority - Please Review First, Urgent Priority

#3379 Peterson resolved the bug that prevented the modal from closing when clicking outside
  src/components/Badge/AssignBadge.jsx
Labels: High Priority - Please Review First

#3393 Akshay - Add - timeZone-property-to-UserManagement - Frontend
  src/components/UserManagement/TimeDifference.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/usermanagement.css
Labels: High Priority - Please Review First

#3387 Bhavpreet- fixed the end date and final date issue on um
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserManagement/SetUpFinalDayPopUp.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/__tests__/SetUpFinalDayPopUp.test.jsx
  src/components/UserManagement/__tests__/UserTableData.test.js
Labels: Hotfix

#3363 Bhavpreet - changed custom carousel to that of bootstraps
  src/components/LBDashboard/ListingOverview/ImageCarousel.css
  src/components/LBDashboard/ListingOverview/ImageCarousel.jsx
  src/components/LBDashboard/ListingOverview/ListOverview.jsx
  src/components/LBDashboard/ListingOverview/Listoverview.css
Labels: Hotfix

#3415 Guirong taking over for Mohammad- Project Title, Sorting task button, and Spaces between back button and return title
  src/components/Projects/WBS/AddWBS/AddWBS.jsx
  src/components/Projects/WBS/AddWBS/__tests__/AddWBS.test.jsx
  src/components/Projects/WBS/WBSItem/WBSItem.jsx
  src/components/Projects/WBS/WBSItem/__tests__/WBSItem.test.js
  src/components/Projects/WBS/wbs.jsx
  src/styles/print.css
Labels: High Priority - Please Review First

#3417 Dipti fix inability to delete projects from the project page
  src/components/Projects/Project/Project.jsx
  src/components/Projects/Project/Project.test.jsx
  src/components/Projects/Projects.jsx
  src/components/common/Modal/Modal.jsx
Labels: High Priority - Please Review First

#3133 Nishita_Create_Insights_for_Event_Personalization
  src/components/CommunityPortal/EventPersonalization/EventStats.css
  src/components/CommunityPortal/EventPersonalization/EventStats.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3327 Barnaboss_Fixed_the_random_timer_icon
  src/components/LeaderBoard/Leaderboard.jsx
Labels: Moved to Final Review

#3397 Ramakrishna fix assigning project via userProfile
  src/components/Teams/Team.jsx
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First, High Priority

#3313 Sundar - Phase 2 Summary Dashboard: Create a grouped-bar chart named Quantity of Materials Used in Projects frontend
  package-lock.json
  package.json
  src/actions/bmdashboard/weeklyProjectSummaryActions.js
  src/components/BMDashboard/WeeklyProjectSummary/QuantityOfMaterialsUsed/QuantityOfMaterialsUsed.css
  src/components/BMDashboard/WeeklyProjectSummary/QuantityOfMaterialsUsed/QuantityOfMaterialsUsed.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.css
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummaryHeader.jsx
  src/constants/bmdashboard/weeklyProjectSummaryConstants.js
  src/reducers/bmdashboard/weeklyProjectSummaryReducer.js
  src/reducers/index.js
Labels: High Priority - Please Review First

#2994 Chetan fix margin for dashboard card
  src/components/Header/Header.css
  src/components/Header/Header.jsx
Labels: High Priority - Please Review First

#3428 sundar_grouped_quantity_of_materials_used_chart_fix
  src/components/BMDashboard/WeeklyProjectSummary/QuantityOfMaterialsUsed/QuantityOfMaterialsUsed.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3332 Harini - Total Org Summary - Global Volunteer Network Map
  package-lock.json
  package.json
  src/components/TotalOrgSummary/GlobalVolunteerMap/GlobalVolunteerMap.js
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
Labels: High Priority - Please Review First

#3435 Guirong-Fix blue square chart
  src/components/TotalOrgSummary/BlueSquareStats/BlueSquareStats.jsx
  src/components/TotalOrgSummary/DonutChart/DonutChart.css
  src/components/TotalOrgSummary/DonutChart/DonutChart.jsx
Labels: High Priority - Please Review First

#2895 Tanvi - taking over for Shreya - # Fix: new people not showing up in User Management on refresh
  src/components/UserManagement/UserManagement.jsx
Labels: High Priority - Please Review First, High Priority

#3442 Fix for nullnull bug in "Other Links" dropdown
  src/components/Header/Header.jsx
Labels: High Priority - Please Review First

#3412 Fix the bug that prevents users from using dark mode
  src/components/JobCCDashboard/JobCCDashboard.css
  src/components/JobCCDashboard/JobCCDashboard.jsx
Labels: High Priority - Please Review First

#3169 Bhavpreet - Fixed and Added respective missing Create User form Toasts
  src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx
Labels: High Priority - Please Review First, Medium Priority

#3041 Mrinalini - Fixed Leaderboard refresh does not refresh timeoff issue
  src/components/Dashboard/Dashboard.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#3342 Anirudh SK - Formatting CSS for Select Featured in View Profile page
  src/components/Badge/BadgeReport.css
  src/components/Badge/BadgeReport.jsx
Labels: Moved to Final Review
