Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-09, with the labels that each got.

#2816 Siva: Take over from Preetham - Fix TeamReport search functionality and resolve React errors
  dummy.js
  src/components/Reports/TeamReport/TeamReport.jsx
Labels: High Priority - Please Review First

#3958 Amalesh - Fixed the issue with displaying the “Contributors Report”
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalContributorsReport.jsx
Labels: High Priority - Please Review First

#3681 Dharmik - Finish creating way to save a team code filter set
  package-lock.json
  src/actions/allTeamsAction.js
  src/actions/savedFilterActions.js
  src/components/Reports/TeamTable.jsx
  src/components/WeeklySummariesReport/SaveFilterModal.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.module.css
  src/constants/weeklySummariesReport.js
  src/reducers/index.js
  src/reducers/savedFilterReducer.js
  src/utils/URL.js
  yarn.lock
Labels: High Priority - Please Review First

#4004 Sundar: Fix move summary between weeks
  src/components/WeeklySummary/WeeklySummary.jsx
Labels: High Priority - Please Review First

#4009 Shashank madan fix and finish PR3890
  src/components/HGNForm/questionpages/InfoForm.jsx
  src/components/HGNSkillsDashboard/SkillsProfilePage/components/UserSkillsProfile.jsx
  src/routes.jsx
  yarn.lock
Labels: High Priority - Please Review First

#3924 Siri Sudheeksha: fix project assignment from User Profile and Project…
  src/actions/projectMembers.js
  src/components/Projects/Members/FoundUser/FoundUser.jsx
  src/components/Projects/Members/Members.jsx
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
  src/components/UserProfile/TeamsAndProjects/ProjectsTab.jsx
  src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx
  src/components/UserProfile/TeamsAndProjects/__tests__/ProjectsTab.test.jsx
  src/components/UserProfile/UserProfile.jsx
  yarn.lock
Labels: High Priority - Please Review First

#3984 Chaitanya: Access Management UI Fixes
  src/components/UserProfile/UserProfileModal/AccessManagementModal.css
  src/components/UserProfile/UserProfileModal/AccessManagementModal.jsx
  src/utils/URL.js
Labels: do not review

#1793 Anirudh SK (Old PR Conflicts fix) - Jay - PERMISSION: Modify Badge Amount Permission
  src/components/Badge/BadgeReport.jsx
  src/components/PermissionsManagement/PermissionsConst.jsx
  src/components/UserProfile/Badges.jsx
Labels: High Priority - Please Review First, Needs New Developer

#3997 Kedarnath posting landing page
  src/components/Collaboration/Collaboration.jsx
Labels: High Priority - Please Review First

#3870 Manvitha job posting title search option
  package-lock.json
  src/components/Collaboration/Collaboration.jsx
  src/components/Collaboration/Collaboration.module.css
  yarn.lock
Labels: High Priority - Please Review First

#3727 Alisha - PR Review Team Analytics Dashboard - Make a display box for confirming promotions
  src/components/Collaboration/Collaboration.jsx
  src/components/Header/Header.jsx
  src/components/PRPromotions/DisplayBox.css
  src/components/PRPromotions/DisplayBox.jsx
  src/components/PRPromotions/PRPromotionsPage.jsx
  src/components/Projects/Members/Members.jsx
  src/languages/en/ui.js
  src/routes.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#4027 Vishnu projects page add view people
  src/actions/projectMembers.js
  src/components/Projects/Members/FoundUser/FoundUser.jsx
  src/components/Projects/Members/FoundUser/__tests__/FoundUser.test.jsx
  src/components/Projects/Members/Members.jsx
Labels: High Priority - Please Review First

#3976 Akshay - Add - darkMode styles to MostFrequentKeywords component
  src/components/BMDashboard/WeeklyProjectSummary/GroupedBarGraphInjurySeverity/InjuryCategoryBarChart.css
  src/components/BMDashboard/WeeklyProjectSummary/GroupedBarGraphInjurySeverity/InjuryCategoryBarChart.jsx
  src/components/BMDashboard/WeeklyProjectSummary/MostFrequentKeywords/MostFrequentKeywords.jsx
  src/components/BMDashboard/WeeklyProjectSummary/MostFrequentKeywords/MostFrequentKeywords.module.css
Labels: High Priority - Please Review First, Moved to Final Review

#4069 Dipti Fix Subscribe and Unsubscribe Page
  src/routes.jsx
Labels: High Priority - Please Review First

#3875 Aayush - PR Admin Dashboard: Change .css to .module.css in /memberlist
  src/components/QuestionnaireDashboard/MemberList.css
  src/components/QuestionnaireDashboard/MemberList.jsx
  src/components/QuestionnaireDashboard/MemberList.module.css
  src/routes.jsx
Labels: High Priority - Please Review First

#3965 Shashank madan hierarchy summary submission
  src/components/LeaderBoard/Leaderboard.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  yarn.lock
Labels: High Priority - Please Review First

#4091 Swetha - Job Application form
  public/Bottom_image.png
  public/Top_image.png
  src/components/Collaboration/JobApplicationForm.css
  src/components/Collaboration/JobApplicationForm.jsx
  src/components/Collaboration/JobApplicationPage.jsx
  src/components/Collaboration/SuggestedJobsList.jsx
  src/routes.jsx
Labels: High Priority - Please Review First

#3029 Jaydeep taking over for Nishita_Develop_Community_Calendar_Full_View
  package-lock.json
  package.json
  src/components/CommunityPortal/Calendar/CalendarActivitySection.jsx
  src/components/CommunityPortal/Calendar/CommunityCalendar.jsx
  src/components/CommunityPortal/Calendar/CommunityCalendar.module.css
  src/routes.jsx
  yarn.lock
Labels: High Priority - Please Review First

#3967 Kedarnath - Change .css to .module.css in /pr-grading-test
  src/components/PRGradingScreen/PRGradingScreen.jsx
  src/components/PRGradingScreen/PRGradingScreen.module.css
Labels: High Priority - Please Review First

#4053 Shravya_bugfix/inline/module.css_3733
  src/components/BMDashboard/WeeklyProjectSummary/ProjectRiskProfileOverview.jsx
  src/components/BMDashboard/WeeklyProjectSummary/ProjectRiskProfileOverview.module.css
Labels: High Priority - Please Review First

#4103 Alisha Fix: LBDashboard homepage routing and restore missing routes
  src/routes.jsx
  yarn.lock
Labels: High Priority - Please Review First

#3972 Ajay implemented list of active and In Active teams
  src/components/BMDashboard/_tests_/AddTeamMember.test.jsx
  src/components/PermissionsManagement/__tests__/RolePermissions.test.jsx
  src/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx
  src/components/Teams/Team.css
  src/components/Teams/Team.jsx
  src/components/Teams/TeamTableHeader.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/TeamsOverview.css
  src/components/Teams/TeamsOverview.jsx
  src/components/Teams/__tests__/TeamsOverview.test.jsx
  src/languages/en/ui.js
  yarn.lock
Labels: High Priority - Please Review First

#3966 Kedarnath - Change .css to .module.css in /prPromotionsPage
  src/components/PRPromotions/DisplayBox.jsx
  src/components/PRPromotions/DisplayBox.module.css
  src/components/PRPromotions/PRPromotionsPage.jsx
Labels: High Priority - Please Review First

#4022 Jaydeep phase 3 fix track estimated event value
  src/components/CommunityPortal/ResourceUsage/ResourceUsage.jsx
  src/components/CommunityPortal/ResourceUsage/ResourceUsage.module.css
  src/routes.jsx
Labels: High Priority - Please Review First

#3889 Neeraj Job Posting Page Analytics Frontend : Create a horizontal bar graph to show hits/applications ratio
  src/components/Projects/Members/Members.jsx
  src/components/Reports/HitsAndApplicationRatio/ConvertedApplicationGraph.jsx
  src/components/Reports/HitsAndApplicationRatio/JobAnalyticsPage.jsx
  src/components/Reports/HitsAndApplicationRatio/NonConvertedApplicationsGraph.jsx
  src/components/Reports/HitsAndApplicationRatio/dataSample.js
  src/components/Reports/HitsAndApplicationRatio/filters.js
  src/components/Reports/HitsAndApplicationRatio/index.js
  src/routes.jsx
  src/utils/URL.js
  yarn.lock
Labels: High Priority - Please Review First
