Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-02, with the labels that each got.

#3113 Shengwei - Hotfix - Upgrade CircleCI resource class from large to xlarge
  .circleci/config.yml
Labels: hotfix

#3061 nazanin_fix_overlapping_welcome_dropdown_menu_and_Select_from_Categories
  src/components/Header/Header.css
Labels: High Priority - Please Review First

#2991 Ziyu-unit-test-countdown
  src/components/Timer/__test__/Countdown.test.js
Labels: Moved to Final Review

#3104 Verify that after deleting any task from the wbs task list it should not show blank screen.
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: High Priority - Please Review First

#3042 Ramakrishna added report icon and completed tasknumbers in taskmemebers dashboard
  public/report_icon.png
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First, high priority

#3132 Vinay fix copying resolved bug
  src/reducers/allTasksReducer.js
Labels: High Priority - Please Review First

#2770 Rishitha - Fix purchase request form for tools
  src/components/BMDashboard/ToolItemList/ToolItemsTable.jsx
  src/components/BMDashboard/ToolPurchaseRequest/PurchaseForm.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#2865 Rishitha fix projects active filter
  src/components/Projects/Projects.jsx
Labels: High Priority - Please Review First

#2905 Rishitha Add toggle percentage to pie chart
  src/components/common/PieChart/PieChart.css
  src/components/common/PieChart/PieChart.jsx
Labels: High Priority - Please Review First

#2919 Rishitha Fix blue square summary format and date
  src/components/UserProfile/BlueSquares/BlueSquare.css
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#2982 Rishitha add details in add material
  src/components/BMDashboard/AddMaterial/AddMaterial.css
  src/components/BMDashboard/AddMaterial/AddMaterial.jsx
Labels: High Priority - Please Review First, Updated

#3019 Yashwanth Category columns of projects page
  src/components/Projects/Project/Project.jsx
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3021 Neha - Only whole numbers are accepted for no. of weeks in bluesquare scheduling
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3053 Geeta - Fixed category bug for Projects
  src/components/UserProfile/TeamsAndProjects/AddProjectPopup.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3154 Sharan Sai - Tasks Number Period(".") Issue
  src/components/TeamMemberTasks/TeamMemberTask.jsx
Labels: High Priority - Please Review First, hotfix

#3143 Sai Girish - Fixed the toolbar visiblity
  src/App.css
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
Labels: High Priority - Please Review First, hotfix

#3024 Sriram- add special toggles for weekly summary reports
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First, high priority

#2701 Logeshwari fix for active/inactive toggle to teams
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Teams/ToggleSwitch/ToggleSwitch.module.scss
Labels: High Priority - Please Review First, Updated

#3094 Jinda unit test timeEntries
  src/actions/__tests__/timeEntries.js.test.js
Labels: Moved to Final Review

#2358 Sriram took over for Jay - fix people report badges
  src/components/Badge/BadgeImage.jsx
  src/components/Badge/BadgeReport.css
  src/components/Badge/BadgeReport.jsx
  src/components/Reports/BadgeSummaryPreview.css
  src/components/Reports/BadgeSummaryPreview.jsx
  src/components/Reports/BadgeSummaryViz.css
  src/components/Reports/BadgeSummaryViz.jsx
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/Reports.jsx
  src/components/UserProfile/Badges.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3176 Bhavpreet - Fixed the end and start date on activation/deactivation of account
  src/actions/__tests__/timeEntries.js.test.js
  src/actions/timeEntries.js
  src/actions/userManagement.js
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Labels: Urgent Priority

#3095 Jinda unit test teams
  src/actions/__tests__/teams.js.test.js
  src/actions/team.js
Labels: Moved to Final Review

#2751 Haoyue - Quick Setup Tool: Team Code field should only suggest active team
  src/actions/allTeamsAction.js
  src/actions/teamCodes.js
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamCodeField.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupCodes.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/reducers/index.js
  src/reducers/teamCodesReducer.js
Labels: High Priority - Please Review First

#2850 Gmon - Add active/inactive numbers by teams on team page
  src/components/Teams/TeamsOverview.jsx
Labels: High Priority - Please Review First

#3054 Samarth B - Lint Fix Setup Profile
  .eslintignore
  .prettierignore
  package.json
  src/components/SetupProfile/SetupProfile.jsx
  src/components/SetupProfile/SetupProfileInvalidToken.jsx
  src/components/SetupProfile/SetupProfileUserEntry.jsx
  src/components/SetupProfile/collaborationSuggestionData.js
  src/components/SetupProfile/deleteHomeCountryModal.jsx
  src/components/SetupProfile/homeCountryModal.jsx
  src/components/SetupProfile/profilePictureModal.jsx
  src/components/SetupProfile/requirementModal.jsx
Labels: High Priority - Please Review First

#3055 Samarth B - Lint Fix TeamLocations
  .eslintignore
  .prettierignore
  src/components/TeamLocations/AddOrEditPopup.jsx
  src/components/TeamLocations/CustomInput.jsx
  src/components/TeamLocations/ListUsersPopUp.jsx
  src/components/TeamLocations/MarkerPopup.jsx
  src/components/TeamLocations/TeamLocations.jsx
  src/components/TeamLocations/TeamLocationsTable.jsx
  src/components/TeamLocations/index.js
Labels: High Priority - Please Review First

#3091 Sai preetham tracking management
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/Warnings/WarningIcon.jsx
  src/components/Warnings/WarningIcons.jsx
  src/components/Warnings/WarningItem.jsx
  src/components/Warnings/Warnings.jsx
  src/components/Warnings/__test__/Warnings.test.js
  src/components/Warnings/modals/WarningModal.jsx
  src/components/Warnings/modals/WarningTrackerModal.jsx
Labels: High Priority - Please Review First

#3018 Deepthi fix leaderboard header
  src/components/LeaderBoard/Leaderboard.css
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#3190 Swaroop - Fix: Reports Project/People/Teams List Placement
  src/components/Reports/reportsPage.css
Labels: High Priority - Please Review First

#3201 Bhavpreet - add the populatation of data on clicking of input
  src/components/UserProfile/QuickSetupModal/AssignProjectField.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamCodeField.jsx
  src/components/UserProfile/QuickSetupModal/AssignTeamField.jsx
Labels: hotfix

#3187 Shashank_Fix_Profile_Page
  src/actions/userManagement.js
  src/components/UserManagement/PauseAndResumeButton.jsx
  src/components/UserManagement/SetUpFinalDayButton.jsx
  src/components/UserManagement/__tests__/PauseAndResumeButton.test.js
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.css
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfile.scss
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.jsx
  src/components/UserProfile/UserProfileEdit/ToggleSwitch/ToggleSwitch.module.scss
  src/languages/en/ui.js
Labels: High Priority - Please Review First

#3145 Dhrumil-Update-Reusable-Form
  src/components/BMDashboard/UpdateReusables/UpdateReusableModal.jsx
Labels: High Priority - Please Review First
