Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-05, with the labels that each got.

#3276 pavanswaroop-added-role-icons-reduced-header-searcheditor-tablecolumn-widths
  src/components/UserManagement/UserTableData.jsx
  src/components/UserManagement/UserTableSearchHeader.jsx
  src/components/UserManagement/usermanagement.css
Labels: High Priority - Please Review First

#3367 Sharadha - Create Frontend Title search option
  src/components/Collaboration/Collaboration.css
  src/components/Collaboration/Collaboration.jsx
  src/components/Collaboration/Collaboration.module.css
Labels: High Priority - Please Review First

#3162 Geeta - Fixed date autofilling
  src/components/UserManagement/UserManagement.jsx
  src/components/UserProfile/UserProfileModal/UserProfileModal.jsx
Labels: High Priority - Please Review First

#3088 Deepthi fix limit of bounding box
  src/components/TeamMemberTasks/FollowUpInfoModal.css
  src/components/TeamMemberTasks/FollowUpInfoModal.jsx
Labels: Medium Priority

#2417 Jay Force new password for new users
  src/components/ForcePasswordUpdate/ForcePasswordUpdate.jsx
Labels: Moved to Final Review

#3445 Sriram optimize profile page loading times
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First, High Priority

#3269 Rahul fix reports team page last table for small screens
  src/components/Reports/TeamReport/TeamReport.jsx
  src/components/Reports/TeamReport/components/ReportCharts.css
  src/components/Reports/TeamReport/components/ReportLogs.css
  src/components/Reports/TeamReport/components/TeamReportLogs.jsx
  src/components/Reports/TeamReport/components/TeamsReportLogs.jsx
  src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/ReportBlock.css
Labels: Moved to Final Review

#2926 Pallavi Fixed ability to interact with deadline check-in-box
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
Labels: Moved to Final Review, Medium Priority

#3155 Koushica - Fix delay in the hour count update for the individual task
  src/components/TeamMemberTasks/actions.js
  src/components/TeamMemberTasks/reducer.js
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
Labels: High Priority - Please Review First

#2864 Sai_Preetham_Name_Overflow_On_Dashboard
  src/components/SummaryBar/SummaryBar.css
  src/components/SummaryBar/SummaryBar.jsx
Labels: Low Priority

#3362 Sai preetham add functions material list bmdashboard
  src/components/BMDashboard/ItemList/ItemListView.css
  src/components/BMDashboard/ItemList/ItemListView.jsx
  src/components/BMDashboard/ItemList/ItemsTable.jsx
  src/components/BMDashboard/MaterialList/MaterialListView.jsx
Labels: High Priority - Please Review First

#2786 Calvin- Fix Bug 85 Phase 2: Inventory Type List (/bmdashboard/inventory/types)
  src/components/BMDashboard/shared/CheckTypes.jsx
Labels: High Priority - Please Review First

#3254 Nikhil update equipment tool
  src/components/App.jsx
  src/components/BMDashboard/Tools/EquipmentUpdate.css
  src/components/BMDashboard/Tools/EquipmentUpdate.jsx
  src/components/BMDashboard/Tools/EquipmentUpdateForm.css
  src/components/BMDashboard/Tools/EquipmentUpdateForm.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3396 Vinay - Let a user know through a popup that Permissions have been changed for them
  src/components/Header/Header.jsx
  src/components/PopUpBar/PopUpBar.css
  src/components/PopUpBar/PopUpBar.jsx
  src/components/PopUpBar/__tests__/PopUpBar.test.jsx
  src/components/common/Loading/Loading.jsx
Labels: High Priority - Please Review First

#1710 Jiayu --> Miguel Adding Issue Form
  src/components/BMDashboard/Issue/Issue.css
  src/components/BMDashboard/Issue/Issue.jsx
  src/components/BMDashboard/Issue/index.js
  src/routes.js
Labels: High Priority - Please Review First

#3197 Ziddi - issue log form in bmdashboard
  src/components/BMDashboard/Issue/Issue.css
  src/components/BMDashboard/Issue/Issue.jsx
  src/components/BMDashboard/Issue/index.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3163 Ziddi i icon in permisison management
  src/components/PermissionsManagement/RolePermissions.css
  src/components/PermissionsManagement/RolePermissions.jsx
  src/components/PermissionsManagement/UserRoleTab.css
Labels: High Priority - Please Review First

#3423 Yu adjust reports chart UI
  src/components/Reports/TotalReport/TotalReportBarGraph.css
  src/components/Reports/TotalReport/TotalReportBarGraph.jsx
Labels: High Priority - Please Review First

#3474 Shashank Fixed extra space in profile page
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.css
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: do not review

#2826 Honglin taking over for Ram - Update WeeklySummariesReport.jsx from a class component to a function component
  src/components/WeeklySummariesReport/WeeklySummariesReport.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummaryRecepientsPopup.jsx
  src/components/WeeklySummariesReport/__tests__/GeneratePdfReport.test.js
  src/components/WeeklySummariesReport/__tests__/WeeklySummariesReport.test.js
  src/components/WeeklySummariesReport/__tests__/__snapshots__/GeneratePdfReport.test.js.snap
Labels: High Priority - Please Review First

#3373 Calvin - Fix task time update
  src/components/Header/DarkMode.css
  src/components/Timelog/TimeEntryForm/TimeEntryForm.jsx
  src/components/Timelog/Timelog.css
Labels: Moved to Final Review

#2426 Deepthi Fix SEND EMAILS PAGE UI issues for 375px and up
  src/components/Announcements/Announcements.css
Labels: High Priority - Please Review First, Moved to Final Review

#3489 Haoyue job posting application age bar chart
  package-lock.json
  package.json
  src/components/ApplicantsChart/AgeChart.jsx
  src/components/ApplicantsChart/ApplicantsAgeChart.jsx
  src/components/ApplicantsChart/TimeFilter.jsx
  src/components/ApplicantsChart/api.js
  src/components/ApplicantsChart/data.js
  src/components/ApplicantsChart/index.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3118 Haoyue faq tool implementation
  .github/workflows/pull_request_test.yml
  package-lock.json
  package.json
  src/components/Faq/FaqHistory.jsx
  src/components/Faq/FaqManagement.jsx
  src/components/Faq/FaqSearch.jsx
  src/components/Faq/UnansweredFaqs.jsx
  src/components/Faq/api.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/common/ProtectedRoute/ProtectedRoute.jsx
  src/routes.js
  src/utils/URL.js
  src/utils/routePermissions.js
Labels: High Priority - Please Review First

#3148 Shraddha Shahari - Fix the inability to send out emails from send emails tab
  src/components/Announcements/index.jsx
Labels: High Priority - Please Review First, Urgent Priority

#2893 Sheetal M - Add unit test for monthlyDashboardDataReducer.js
  src/reducers/__tests__/monthlyDashboardDataReducer.test.js
Labels: Moved to Final Review

#3119 Sheetal M - Test cases for action weeklySummariesReport
  src/actions/__tests__/weeklySummariesReportActions.test.js
Labels: Moved to Final Review, do not review

#3057 Sheetal M - Test cases for action weeklySummaries.js
  src/actions/__tests__/weeklySummariesAction.test.js
Labels: Moved to Final Review

#2933 Yili - Fix the issue for non-Owner/Admin accounts that have the 'Edit Team 4-Digit Codes' permission, allowing them to edit the team code
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#3407 Samman_SharePDF button for phase II
  package-lock.json
  package.json
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummaryHeader.jsx
  src/components/TotalOrgSummary/AccordianWrapper/AccordianWrapper.jsx
  src/components/TotalOrgSummary/TotalOrgSummary.css
Labels: High Priority - Please Review First

#3421 Dhrumil-added-test-cases-ToggleSwitch
  src/components/UserProfile/UserProfileEdit/__tests__/ToggleSwitch.test.js
Labels: Moved to Final Review

#3274 Ziddi - Added asterisk for the users to identify them as mandatory fields. Added warning messages to fill the mandatory inputs where ever required.
  src/actions/__tests__/weeklySummariesAction.test.js
  src/actions/__tests__/weeklySummariesReportActions.test.js
  src/components/Announcements/index.jsx
  src/components/BMDashboard/Lesson/LessonForm.jsx
  src/components/Badge/AssignBadge.jsx
  src/components/Badge/CreateNewBadgePopup.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Header/DarkMode.css
  src/components/PermissionsManagement/NewRolePopUp.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
  src/components/Projects/AddProject/AddProject.jsx
  src/components/Projects/AddProject/__tests__/AddProject.test.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Reports/LostTime/AddLostTime.jsx
  src/components/Reports/reportsPage.css
  src/components/TeamLocations/AddOrEditPopup.jsx
  src/components/Teams/CreateNewTeamPopup.jsx
  src/components/UserManagement/setupNewUserPopup.jsx
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
  src/reducers/__tests__/monthlyDashboardDataReducer.test.js
  src/reducers/__tests__/teamsTeamMembersReducer.test.js
Labels: High Priority - Please Review First

#3052 Nishita_develop_frontend_for_event_participation_analysis
  src/components/CommunityPortal/Reports/Participation/DropOffTracking.jsx
  src/components/CommunityPortal/Reports/Participation/EventParticipation.jsx
  src/components/CommunityPortal/Reports/Participation/MyCases.css
  src/components/CommunityPortal/Reports/Participation/MyCases.jsx
  src/components/CommunityPortal/Reports/Participation/NoShowInsights.jsx
  src/components/CommunityPortal/Reports/Participation/Participation.css
  src/components/CommunityPortal/Reports/Participation/mockData.jsx
  src/routes.js
Labels: High Priority - Please Review First, Moved to Final Review

#2888 Nikhitha/Sharadha - Team Member Task Section Freeze/Shakes on small screens
  src/components/TeamMemberTasks/style.css
Labels: High Priority - Please Review First

#3361 Guirong-Total Org Summary - Share as PDF Feature
  package-lock.json
  package.json
  src/components/Announcements/index.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/OwnerMessage/OwnerMessage.css
  src/components/OwnerMessage/OwnerMessage.jsx
  src/components/Timer/Countdown.module.css
  src/components/Timer/Timer.jsx
  src/components/Timer/Timer.module.css
  src/components/TotalOrgSummary/TotalOrgSummary.css
  src/components/TotalOrgSummary/TotalOrgSummary.jsx
Labels: High Priority - Please Review First

#3413 Sriram fix other's dashboard view
  src/components/Badge/Badge.jsx
  src/components/Badge/NewBadges.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Header/Header.jsx
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#2901 Sriram new unit test for new user popup from changao
  src/components/UserManagement/NewUserPopup.jsx
  src/components/UserManagement/__tests__/NewUserPopup.test.js
Labels: Medium Priority

#2874 Sriram - Add Projects Page Inventory sort button
  src/actions/projects.js
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
Labels: High Priority - Please Review First, High Priority

#3083 Sriram takeover - jatin fix task date editing crashing webpage
  package-lock.json
  package.json
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: High Priority - Please Review First

#3484 Rahul - Abhinav_unit test_toggleswitch_cleanup (Rahul)
  issue-form-cleanup
Labels: High Priority - Please Review First

#3186 Sriram - Optimize loading time for WBS
  src/__tests__/mockAdminState.js
  src/actions/projectMembers.js
  src/components/Projects/Members/Members.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
  src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
  src/components/Projects/WBS/WBSDetail/components/__tests__/TagsSearch.test.js
  src/components/Reports/ProjectReport/ProjectReport.jsx
  src/components/Reports/TasksDetail/TasksDetail.jsx
  src/components/Reports/TasksTable/TasksTable.jsx
  src/constants/projectMembership.js
  src/reducers/__tests__/projectMembershipReducer.test.js
  src/reducers/projectMembershipReducer.js
  src/utils/URL.js
Labels: High Priority - Please Review First, High Priority

#3360 Rishwa - Set up routes and folder structure for HGN Help Dashboard
  src/components/HGNHelpSkillsDashboard/CommunityMembersPage.jsx
  src/components/HGNHelpSkillsDashboard/FeedbackModal.jsx
  src/components/HGNHelpSkillsDashboard/LandingPage.jsx
  src/components/HGNHelpSkillsDashboard/SkillsOverviewPage.jsx
  src/components/HGNHelpSkillsDashboard/UserProfilePage.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3420 sundar_grouped_bar_graph_named_paid_labor_cost_frontend
  package-lock.json
  package.json
  src/components/BMDashboard/WeeklyProjectSummary/PaidLaborCost/PaidLaborCost.css
  src/components/BMDashboard/WeeklyProjectSummary/PaidLaborCost/PaidLaborCost.jsx
  src/components/BMDashboard/WeeklyProjectSummary/PaidLaborCost/PaidLaborCostDatePicker.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
Labels: High Priority - Please Review First

#2975 ShreyaV Unit Testing for Add Task Modal WBS Component
  package-lock.json
  package.json
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/__tests__/AddTaskModal.test.js
Labels: High Priority - Please Review First, High Priority

#2941 modified the css file to make sure to the logo & message is always vi…
  src/components/Header/Header.css
  src/components/Header/Header.jsx
Labels: Needs New Developer

#3449 Rishwa skills dashboard user card
  src/components/HGNHelpSkillsDashboard/CommunityMembersPage.jsx
  src/components/HGNHelpSkillsDashboard/RankedUserList.jsx
  src/components/HGNHelpSkillsDashboard/UserCard.jsx
  src/components/HGNHelpSkillsDashboard/style/UserCard.css
  src/components/HGNHelpSkillsDashboard/style/avatar.png
  src/components/HGNHelpSkillsDashboard/style/email_icon.png
  src/components/HGNHelpSkillsDashboard/style/slack_icon.png
  src/routes.js
Labels: High Priority - Please Review First

#3357 Sai Moola - HGN Questionnaire Dashboard: Frontend: Create the Initial Help Request Modal
  src/components/LandingPage/HelpModal.css
  src/components/LandingPage/HelpModal.jsx
  src/components/LandingPage/HelpPage.jsx
  src/components/SummaryBar/SummaryBar.jsx
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3539 Sai Girish - Create Login Page for Listing homepage frontend
  src/components/LBDashboard/Home/Home.css
  src/components/LBDashboard/Home/Home.jsx
  src/components/LBDashboard/Home/data.js
  src/components/LBDashboard/LBProtectedRoute/LBProtectedRoute.jsx
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3448 Akshay - Fix - Disallow negative hours input in WBS Add Task form
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
Labels: High Priority - Please Review First

#3370 Sharadha- Registration by event type and location
  src/components/CommunityPortal/Activities/ActivitiesPage.jsx
  src/components/CommunityPortal/Activities/LatestRegistration.jsx
  src/components/CommunityPortal/Activities/MyEvent.jsx
  src/components/CommunityPortal/Activities/RegistrationForm.jsx
  src/components/CommunityPortal/Activities/ResourceMonitoring.jsx
  src/components/CommunityPortal/Activities/styles.css
  src/routes.js
Labels: High Priority - Please Review First
