Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-07, with the labels that each got.

#3592 Anirudh SK Job CC feature (All category)
  src/components/JobCCDashboard/JobCategoryCCModal.jsx
Labels: High Priority - Please Review First

#2915 Anirudh SK - Start/End date format, validation bug & date picker overflow issue fix
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.css
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
  src/components/Projects/WBS/WBSDetail/wbs.css
Labels: High Priority - Please Review First

#3248 Anirudh SK leaderboard tooltip issue
  package-lock.json
  src/actions/timeOffRequestAction.js
  src/components/LeaderBoard/LeaderBoard.container.jsx
  src/components/LeaderBoard/Leaderboard.jsx
  src/constants/timeOffRequestConstants.js
  src/reducers/timeOffRequestReducer.js
Labels: High Priority - Please Review First

#3712 Geeta - Updated people count in report
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
Labels: High Priority - Please Review First

#3673 Varun feature/force logout countdown
  src/actions/authActions.js
  src/components/Auth/PermissionWatcher.jsx
  src/components/Header/Header.jsx
  src/components/PopUpBar/PopUpBar.jsx
  src/components/Projects/WBS/__tests__/SameFolderTasks.test.js
  src/constants/auth.js
  src/hooks/useCountdown.js
  src/reducers/__tests__/authReducer.test.js
  src/reducers/authReducer.js
Labels: High Priority - Please Review First

#3376 Geeta - created blue square assigned functionality
  src/components/SummaryBar/SummaryBar.jsx
  src/components/UserManagement/UserManagement.jsx
  src/components/UserProfile/UserProfileModal/UserProfileModal.jsx
  src/components/UserProfile/UserProfileModal/__tests__/USerProfileModal.test.js
Labels: High Priority - Please Review First, Urgent Priority

#3688 Taariq fix weekly summary reports team code changes on refresh
  src/components/Badge/__tests__/NewBadges.test.js
  src/components/Projects/WBS/wbs.test.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Labels: High Priority - Please Review First

#3719 Shraddha - Fixed broken UI screen for send email page
  src/components/Announcements/Announcements.css
  src/components/Announcements/index.jsx
Labels: High Priority - Please Review First

#3732 Vaibhav Created longest open issues bar chart
  src/actions/bmdashboard/issueChartActions.js
  src/components/BMDashboard/Issues/issueCharts.css
  src/components/BMDashboard/Issues/openIssueCharts.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
  src/constants/bmdashboard/issueConstants.js
  src/reducers/bmdashboard/issueReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3721 Dhrumil added unit tests for AddConsumable
  src/components/BMDashboard/AddConsumable/__tests__/AddConsumable.test.jsx
Labels: High Priority - Please Review First

#3554 Varun fix weekly summary inactive users
  src/components/Badge/__tests__/NewBadges.test.js
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/setupTests.js
Labels: High Priority - Please Review First

#3548 Phase 2 Summary Dashboard: Create Expected v Actual Expense Graph in phase 2 dashboard - Sundar
  src/components/BMDashboard/WeeklyProjectSummary/ActualVsPlannedCost/ActualVsPlannedCost.css
  src/components/BMDashboard/WeeklyProjectSummary/ActualVsPlannedCost/ActualVsPlannedCost.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
  src/constants/bmdashboard/projectConstants.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3140 Sundar take over form Shreya: Frontend for Community Portal - Attendance Page
  package-lock.json
  package.json
  src/assets/images/profile.png
  src/components/CommunityPortal/Activities/ActivityAttendance.css
  src/components/CommunityPortal/Activities/ActivityAttendance.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3085 Sundar take over from Shreya L - Added Activity Agenda Page for the Community Portal
  src/assets/images/yoga-img.png
  src/components/CommunityPortal/Activities/ActivityAgenda.css
  src/components/CommunityPortal/Activities/ActivityAgenda.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3760 Dipti Task Number (#) column in the WBS tasks table should be left-al…
  src/components/Projects/WBS/WBSDetail/Task/Task.jsx
  src/components/Projects/WBS/WBSDetail/Task/task.css
Labels: High Priority - Please Review First

#3707 Guirong-Make pop-out timer look like expanded-view timer
  src/components/Timer/Timer.jsx
  src/components/Timer/TimerPopout.jsx
Labels: Moved to Final Review

#3486 Samman- Phase 2 Making the header of P5
  package-lock.json
  package.json
  src/components/BMDashboard/Issues/IssueDashboard.jsx
  src/components/BMDashboard/Issues/IssueHeader.css
  src/components/BMDashboard/Issues/IssueHeader.jsx
  src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.css
  src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.jsx
  src/components/CommunityPortal/Activities/Register/Register.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3679 Samman- Bug Fix for phase III nav bar.
  src/components/CommunityPortal/CPHeader/CPHeader.css
  src/components/CommunityPortal/CPHeader/CPHeader.jsx
Labels: High Priority - Please Review First

#2891 Ajay - Fix Project WBS list and Tab Preview Names
  src/components/App.jsx
  src/components/Projects/AddProject/AddProject.jsx
  src/components/Projects/Project/Project.jsx
  src/components/Projects/ProjectTableHeader/ProjectTableHeader.jsx
  src/components/Projects/Projects.jsx
  src/components/Projects/WBS/AddWBS/AddWBS.jsx
  src/components/Projects/WBS/wbs.jsx
  src/components/SearchProjectByPerson/SearchProjectByPerson.jsx
Labels: do not review

#3746 Rahul - PR Review Dash - Top 20 Most Popular PRs
  src/components/HGNPRDashboard/DurationFilter.css
  src/components/HGNPRDashboard/DurationFilter.jsx
  src/components/HGNPRDashboard/PRData.js
  src/components/HGNPRDashboard/PRReviewTeamAnalytics.css
  src/components/HGNPRDashboard/PRReviewTeamAnalytics.jsx
  src/components/HGNPRDashboard/ThemeContext.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3656 Anthony/fix save edits to other fields after using quick setup buttons
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#3043 Pratyush Phase 3 Error handling
  src/components/EventRegistration/TestEventRegistration.js
  src/routes.js
Labels: High Priority - Please Review First

#3810 Pratyush Phase 2 Summary Dashboard: Create a horizontal bar graph titled tools most susceptible to breakdown
  src/components/MostSusceptible/toolBreakdownChart.jsx
  src/routes.js
Labels: High Priority - Please Review First

#3194 Pratyush Phase 3 - Logging Virtual vs. In-Person Attendance
  src/components/AttendanceStats/AttendanceDashboard.jsx
  src/components/Badge/AssignBadge.jsx
  src/components/Badge/AssignTableRow.jsx
  src/components/Badge/BadgeManagement.jsx
  src/components/Badge/BadgeReport.jsx
  src/components/Badge/__tests__/AssignBadgePopup.test.jsx
  src/components/Badge/__tests__/AssignTableRow.test.jsx
  src/components/Badge/__tests__/BadgeDevelopment.test.jsx
  src/components/Badge/__tests__/BadgeHistory.test.jsx
  src/components/Badge/__tests__/BadgeImage.test.jsx
  src/components/Badge/__tests__/BadgeReport.test.jsx
  src/components/Badge/__tests__/CreateNewBadgePopup.test.jsx
  src/components/Badge/__tests__/DeleteBadgePopup.test.jsx
  src/components/Badge/__tests__/NewBadges.test.jsx
  src/components/Dashboard/Dashboard.test.jsx
  src/components/Dashboard/__tests__/Dashboard.test.jsx
  src/components/TeamMemberTasks/TeamMemberTaskIconsInfo.jsx
  src/components/TeamMemberTasks/__tests__/DiffedText.test.jsx
  src/components/TeamMemberTasks/__tests__/TaskCompletedModal.test.jsx
  src/components/TeamMemberTasks/components/TaskCompletedModal.jsx
  src/components/TeamMemberTasks/components/TaskDifferenceModal.jsx
  src/components/TeamMemberTasks/components/__tests__/TaskDifferenceModal.test.jsx
  src/components/TeamMemberTasks/reducer.jsx
  src/components/WeeklySummary/WriteForMeModal.jsx
  yarn.lock
Labels: High Priority - Please Review First

#3773 Nikhil migrate src/components/WeeklySummariesReport css to module css
  src/components/WeeklySummariesReport/TeamChart.css
  src/components/WeeklySummariesReport/TeamChart.jsx
  src/components/WeeklySummariesReport/TeamChart.module.css
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.module.css
Labels: High Priority - Please Review First, Urgent Priority

#3806 Dipti Fix the font color and text alignment in the Role “i” icon pop…
  src/components/PermissionsManagement/RolePermissions.css
  src/components/PermissionsManagement/RolePermissions.jsx
Labels: High Priority - Please Review First

#3652 Mrinalini Fix active QST retrieval and teams tab refresh
  src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
  src/components/UserProfile/TeamsAndProjects/AddTeamPopup.jsx
  src/components/UserProfile/TeamsAndProjects/TeamsTab.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First
