Repository OneCommunityGlobal/HighestGoodNetworkApp, pull requests merged in 2025-03, with the labels that each got.

#3033 Dhrumil - Bug - Fix People Report “Projects With Completed Hours” not being correct
  src/components/Reports/PeopleReport/__tests__/selectors.test.js
  src/components/Reports/PeopleReport/selectors.js
Labels: High Priority - Please Review First, high priority

#2853 Nikita create components for input methods for forms
  package-lock.json
  package.json
  src/actions/formActions.js
  src/components/Forms/Components/OptionMaker.jsx
  src/components/Forms/Components/OptionViewer.jsx
  src/components/Forms/Components/QuestionMaker.jsx
  src/components/Forms/Components/QuestionViewer.jsx
  src/components/Forms/Components/RichTextEditor.js
  src/components/Forms/FormEditor.jsx
  src/components/Forms/FormViewer.jsx
  src/constants/form.js
  src/reducers/formReducer.js
  src/reducers/index.js
  src/routes.js
  src/utils/enums.js
Labels: Moved to Final Review

#2289 Sriram taking over for Imran toggle request bio
  src/actions/weeklySummariesReport.js
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/WeeklySummariesReport/FormattedReport.jsx
  src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
  src/utils/URL.js
Labels: Needs New Developer, do not review

#3227 bhavpreet- QSC color not changing
  .babelrc
  package.json
  src/actions/__tests__/teams.js.test.js
  src/actions/team.js
  src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx
Labels: hotfix

#3144 Jatin Disallow Negative Time Logged
  src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx
Labels: High Priority - Please Review First

#3199 Anjali - Updated Material Dashboard
  src/actions/bmdashboard/materialsActions.js
Labels: High Priority - Please Review First

#2924 Samarth B Job CC feature
  src/components/JobCCDashboard/JobCCDashboard.css
  src/components/JobCCDashboard/JobCCDashboard.jsx
  src/components/JobCCDashboard/JobCCModal.jsx
  src/components/JobCCDashboard/JobCategoryCCModal.jsx
  src/components/UserProfile/BlueSquareLayout.jsx
  src/components/UserProfile/UserProfile.scss
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3258 Sundar Make the header and complete the basic structure of the Phase 2 Summary Dashboard
  src/components/App.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.css
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummary.jsx
  src/components/BMDashboard/WeeklyProjectSummary/WeeklyProjectSummaryHeader.jsx
  src/components/Header/Header.jsx
  src/languages/en/ui.js
  src/routes.js
Labels: High Priority - Please Review First

#3134 Calvin Fix Bug 195 href to “One Community Work Breakdown Structure” not working
  .vscode/settings.json
  src/components/Timelog/Timelog.css
  src/components/Timelog/Timelog.jsx
Labels: High Priority - Please Review First

#2928 Jatin create different question sets
  src/components/Collaboration/JobFormBuilder.css
  src/components/Collaboration/JobFormbuilder.jsx
  src/routes.js
  src/utils/URL.js
Labels: High Priority - Please Review First

#3122 Jinda all team actions
  src/actions/__tests__/allTeamsAction.js.test.js
Labels: Moved to Final Review

#3266 Dhrumil - 🔥 People Report “Projects With Completed Hours” not being correct
  src/components/Reports/PeopleReport/PeopleReport.jsx
  src/components/Reports/PeopleReport/__tests__/selectors.test.js
  src/components/Reports/PeopleReport/selectors.js
Labels: High Priority - Please Review First

#3086 jatin add spinning widget added to leaderboard before loading
  src/components/LeaderBoard/Leaderboard.jsx
Labels: High Priority - Please Review First

#3251 Manoj Add edit ability and limit link type
  src/components/TeamMemberTasks/ReviewButton.jsx
Labels: High Priority - Please Review First

#3231 Bhavpreet - Create Listing Overview frontend
  src/assets/images/mapIcon.png
  src/components/LBDashboard/ListOverview/ImageCarousel.css
  src/components/LBDashboard/ListOverview/ImageCarousel.jsx
  src/components/LBDashboard/ListOverview/ListOverview.jsx
  src/components/LBDashboard/ListOverview/Listoverview.css
  src/routes.js
Labels: High Priority - Please Review First, Moved to Final Review

#2947 Samarth B - Fixed Linting component/Teams
  .eslintignore
  .prettierignore
  src/components/Teams/CreateNewTeamPopup.jsx
  src/components/Teams/DeleteTeamPopup.jsx
  src/components/Teams/InfoModal.jsx
  src/components/Teams/MembersAutoComplete.jsx
  src/components/Teams/Team.jsx
  src/components/Teams/TeamMembersPopup.jsx
  src/components/Teams/TeamStatusPopup.jsx
  src/components/Teams/TeamTableHeader.jsx
  src/components/Teams/TeamTableSearchPanel.jsx
  src/components/Teams/Teams.jsx
  src/components/Teams/TeamsOverview.jsx
  src/components/Teams/ToggleSwitch/ToggleSwitch.jsx
  src/components/Teams/__tests__/Teams.test.js
Labels: High Priority - Please Review First

#3152 Vijay Anand - Added unit test all users time entries action
  src/actions/__tests__/allUsersTimeEntries.test.js
Labels: Moved to Final Review

#3126 Vijay Anand - Added unit test owner message action
  src/actions/__tests__/ownerMessageAction.test.js
Labels: Moved to Final Review

#3065 Vijay Anand - Added unit test userProfile action creators
  src/actions/__tests__/userProfileActions.test.js
Labels: Moved to Final Review

#3047 Vijay Anand - Added unit test wbs action creators
  src/actions/__tests__/wbsActions.test.js
Labels: Moved to Final Review

#3026 Vijay Anand - Added unit test task actions
  src/actions/__tests__/taskActions.test.js
Labels: Moved to Final Review

#3014 Vijay Anand - Add unit test for project action creator
  src/actions/__tests__/projectActions.test.js
  src/actions/project.js
Labels: Moved to Final Review

#3011 Vijay Anand - Added unit test for title action creator
  src/actions/__tests__/titleAction.test.js
Labels: Moved to Final Review

#2951 Vijay Anand - Add unit test for timeEntriesForSpecifiedPeriodReducer
  src/reducers/__tests__/timeEntriesForSpecifiedPeriodReducer.test.js
Labels: Moved to Final Review

#2884 Vijay Anand - Add unit test for weeklySummaryRecipientsReducer
  src/reducers/__tests__/weeklySummaryRecipientsReducer.test.js
Labels: Moved to Final Review

#2880 Vijay Anand - Add unit test for projectReportReducer file
  src/reducers/__tests__/projectReportReducer.test.js
Labels: Moved to Final Review

#2859 Vijay Anand - Added unit test for roleReducer.js
  src/reducers/__tests__/roleReducer.test.js
Labels: Moved to Final Review

#2844 Vijay Anand - Add unit test for handleSuccessReducer
  src/reducers/__tests__/handleSuccessReducer.test.js
Labels: Moved to Final Review, do not review

#2903 Vijay Anand - Unit test notificationReducer file
  src/reducers/__tests__/notificationReducer.test.js
Labels: Moved to Final Review

#3215 Add R icon to profile page
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First

#3263 Akshay - Fix - Total-Report-Components
  src/components/Reports/Reports.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/Reports/reportsPage.css
  src/utils/URL.js
Labels: High Priority - Please Review First, Moved to Final Review

#3298 Calvin-Fix-Auto-Save
  src/components/UserProfile/QuickSetupModal/AssignSetupModal.jsx
  src/components/UserProfile/UserProfile.jsx
  src/components/UserProfile/UserProfileModal/EditLinkModal.jsx
Labels: High Priority - Please Review First, Urgent Priority

#3200 Michael - Make User Management Table Rows Shorter
  src/components/UserManagement/UserManagement.jsx
  src/components/UserManagement/UserTableFooter.jsx
  src/components/UserManagement/__tests__/UserTableFooter.test.js
  src/components/UserManagement/usermanagement.css
Labels: Medium Priority

#3308 Sundar Add ability to accept spaces in Profile>Name>firstname and lastname fields
  src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
Labels: High Priority - Please Review First

#2900 Strallia: Add workflow for closing PRs from forks
  .github/workflows/close-fork-pr.yml
Labels: High Priority - Please Review First

#3223 jinda-test-weeklySummariesReportRecepients
  src/actions/__tests__/weeklySummariesReportRecepients.js.test.js
Labels: Moved to Final Review

#3256 jinda-test-allUserProfilesBasicInfoReducer.js
  src/actions/__tests__/blueSquareEmailBCCAction.js.test.js
Labels: Moved to Final Review

#3022 Koushica - Add confirmation modal and function for scheduling time off in the following week
  src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx
Labels: High Priority - Please Review First, Moved to Final Review, High Priority

#3307 bhavpreet - listing overview add back
  src/components/LBDashboard/ListingOverview/ImageCarousel.css
  src/components/LBDashboard/ListingOverview/ImageCarousel.jsx
  src/components/LBDashboard/ListingOverview/ListOverview.jsx
  src/components/LBDashboard/ListingOverview/Listoverview.css
  src/routes.js
Labels: Hotfix

#3179 Honglin optimize app for Opera browser
  src/actions/badgeManagement.js
  src/actions/wbs.js
  src/components/BMDashboard/ConsumableList/ConsumableListView.jsx
  src/components/BMDashboard/Equipment/Add/AddTypeForm.jsx
  src/components/BMDashboard/ItemList/SelectItem.jsx
  src/components/BMDashboard/MaterialList/MaterialListView.jsx
  src/components/BMDashboard/ReusableList/ReusableListView.jsx
  src/components/BMDashboard/Tools/ToolsList.jsx
  src/components/Collaboration/Collaboration.jsx
  src/components/Projects/Members/Members.jsx
  src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx
  src/components/Reports/TotalReport/TotalPeopleReport.jsx
  src/components/Reports/TotalReport/TotalProjectReport.jsx
  src/components/TaskEditSuggestions/Components/TaskEditSuggestionRow.jsx
  src/components/TeamMemberTasks/TeamMemberTask.jsx
  src/components/UserManagement/DropDownSearchBox.jsx
  src/components/UserManagement/SetupHistoryPopup.jsx
Labels: High Priority - Please Review First, High Priority

#3211 Neha - Progress bar formatting fix
  src/components/SummaryBar/SummaryBar.jsx
Labels: Medium Priority

#3247 vinay: blue square editing issue
  src/components/UserProfile/BlueSquares/BlueSquare.jsx
  src/components/UserProfile/UserProfile.jsx
Labels: High Priority - Please Review First, Moved to Final Review

#3336 Brijesh_fix_button_layout
  src/App.css
Labels: High Priority - Please Review First, Moved to Final Review

#3214 Vinay/fix permission management log
  src/components/PermissionsManagement/PermissionChangeLogTable.jsx
  src/components/PermissionsManagement/PermissionsConst.js
  src/components/PermissionsManagement/PermissionsManagement.jsx
  src/components/PermissionsManagement/UserPermissionsPopUp.jsx
Labels: High Priority - Please Review First
